### ISSUE TITLE
[QUESTION] How to Customize the E1744

### ISSUE THREAD

**Issue by XRyu** [xaviml/controllerx#101]
Hi, i am just starting and building my second a little more functional switch with controllerx.
How would i change the configuration to make a IKEA E1744 do this with a light:

Left turn: Dim down
Right turn: Brighten up
1 click: Toggle between (pre-defined) Warm- and Cold-White
1 click and hold: Toggle light on/off (<- is "hold" even possible for this dimmer switch?)
2 click: change color-temperature by turning, after stopping get back to beforementioned behavior

**Comment by xaviml** [comment]
Hi @XRyu,

Thank you for the question. First of the "click and hold" action is not supported for this controller. You can see the supported actions in [here](https://xaviml.github.io/controllerx/controllers/E1744). I will comment on each of the action you want to have:
> Left turn: Dim down
   Right turn: Brighten up

This is what the default controller is already doing, so it is easy to integrate with ControllerX

> 1 click: Toggle between (pre-defined) Warm- and Cold-White
This is easy to do if your light support xy color, otherwise, there is no easy way to do it unless you get your head around this and using [CallServiceController](https://xaviml.github.io/controllerx/others/custom-controllers#custom-service-controller).

> 1 click and hold: Toggle light on/off (<- is "hold" even possible for this dimmer switch?)
As I said the "hold" action is not supported by this controller, but if you wanted the same but with double click (something that is supported) could be easily done with ControllerX.

> 2 click: change color-temperature by turning, after stopping get back to beforementioned behavior
I will need a better explanation on this since as I understood the left/right turn was for the brightness.

Having said this, this is how the config would look like with left/right turn and 2 clicks to turn off:
```yaml
example_app:
  module: controllerx
  class: CustomLightController
  controller: < controller_id >
  integration: deconz
  light: < light entity >
  mapping:
    2001:hold_brightness_up # Right turn
    3001: hold_brightness_down # Left turn
    2003: release # Stop right turn
    3003: release # Stop left turn
    1004: toggle # 2 clicks
```
This assumes you have the controller integrated with `deCONZ`. Otherwise, you will need to change the keys from the mapping attribute.

Regards,
Xavi M.

**Comment by XRyu** [comment]
Hey Xavi, thank you for the very fast response :)

Thank you for the detailed help :)
I am not sure, if the lights support xy-color, they work fine in HA and i can set color temperature. Assuming it works, how would i implement it in controllerx? :)

So, as click and hold is not possible i thought what i would love to do:

1 click: Toggle light on/off (this is out of the box i guess :D)
2 click: Toggle between (pre-defined) Warm- and Cold-White

BONUS IF ANY WAY POSSIBLE ;):
3 click: "switch to alternate behavior" - instead of the default dimming-behavior when turning left/right - change color-temperature by turning turning left makes light colder (more blueish) and right make it warmer (more reds), after stopping and some seconds not moving the knob get back to beforementioned behavior (so Dim Down/Brighten Up)

I am using z2m, not deconz, how would i need to write for this? :)

**Comment by xaviml** [comment]
Hi @XRyu,

> 1 click: Toggle light on/off (this is out of the box i guess :D)

This is something easy to do as I already showed you in the configuration before

> 2 click: Toggle between (pre-defined) Warm- and Cold-White

This is possible, however, ControllerX is stateless, but you can use callback constraints for this. Assuming you have an input_boolean called `input_boolean.light_colortemp_mode` you can use the configuration down below. This input boolean will help you to have control on the state for the color temperature switch.

> 3 click: "switch to alternate behavior"

This is possible and the same reason as before, you are able to do it if HA controls the state of the app. Assuming you have an input_boolean called `input_boolean.light_mode` then you can have a configuration as followed:

```yaml
example_app:
  module: controllerx
  class: CustomLightController
  controller: sensor.yourcontroller_action
  integration: z2m
  light: light.my_light
  mapping:
    rotate_right: hold_brightness_up # Right turn
    rotate_left: hold_brightness_down # Left turn
    rotate_stop: release # Stop right turn
    rotate_stop: release # Stop left turn
    play_pause: toggle # 1 clicks
  constrain_input_boolean: input_boolean.light_mode,on

example_app2:
  module: controllerx
  class: CustomLightController
  controller: sensor.yourcontroller_action
  integration: z2m
  light: light.my_light
  mapping:
    rotate_right: hold_color_up # Right turn
    rotate_left: hold_color_down # Left turn
    rotate_stop: release # Stop right turn
    rotate_stop: release # Stop left turn
    play_pause: toggle # 1 clicks
  constrain_input_boolean: input_boolean.light_mode,off

example_app3:
  module: controllerx
  class: CustomLightController
  controller: sensor.yourcontroller_action
  integration: z2m
  light: light.my_light
  min_color_temp: <cold temp; 153 is the coolest, 500 is the warmest>
  mapping:
    skip_forward: on_min_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.light_colortemp_mode,on

example_app4:
  module: controllerx
  class: CustomLightController
  controller: sensor.yourcontroller_action
  integration: z2m
  light: light.my_light
  max_color_temp: <warm temp; 153 is the coolest, 500 is the warmest>
  mapping:
    skip_forward: on_full_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.light_colortemp_mode,off

example_app5:
  module: controllerx
  class: CallServiceController
  controller: sensor.yourcontroller_action
  integration: z2m
  light: light.my_light
  mapping:
    skip_forward: # 2 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.light_colortemp_mode
    skip_backward: # 3 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.light_mode
```

These are few takeaways about this configuration before you try it straight away:
- If there is too much boilerplate, you can make use of YAML anchors, however, AppDaemon might complain since the anchors are not skipped from PyYAML and AppDaemon will parse them as applications. More information [here](https://github.com/AppDaemon/appdaemon/issues/1003).
- I used the z2m integration as you said you were using z2m, however, I strongly recommend you to take a look to the mqtt integration since you might have a much better experience. The z2m integration interacts with the HA sensors and this slows down the process, if you use the MQTT integration, you will skip the HA machine state and interact directly with your MQTT broker. More information [here](https://xaviml.github.io/controllerx/others/integrations#mqtt).
- I have tested this configuration out. I have a symfonisk controller integrated with deCONZ and it works flawlessly as you described in the last comment.
- There has been a discussion about the real mapping for this controller with Z2M, so the mappings ("rotate_left", "rotate_right", etc.) might be wrong. Please check your z2m logs to see the events fired for each action. More information [here](https://github.com/xaviml/controllerx/issues/105). Can you maybe help me by telling me which mapping your symfonisk controller has and which version of zigbee2mqtt you are using? Thanks!

Let me know if you have any more questions. For the moment, I will close this issue, but we can follow up in this thread if you need help.

Cheers,
Xavi M.

**Comment by xaviml** [comment]
Sorry @XRyu,

I forgot the following:

> after stopping and some seconds not moving the knob get back to beforementioned behavior (so Dim Down/Brighten Up)

This is something you can use HA automations, you will need to set a timer that whenever the `input_boolean.light_mode` goes to off, activate a timer so after X seconds, will set the `input_boolean.light_mode` back to `on`. Note that when the input boolean is `on` the controller will control the brightness and not the color temperature (config `example_app`)

Cheers,
Xavi M.

**Comment by XRyu** [comment]
Hi Xavi, wow, thats a very comprehensive example and i am truly thankful! :) Great Work!

Right now i have set up your examples for my setup, just for error-search here is my code:
i have created two input booleans in the helper section of HA, "input_boolean.esszimmer_colortemp_mode" and "input_boolean.esszimmer_light_mode",
my lights are named "light.wohnzimmer_filament_leuchten" and my symfonisk is named: "sensor.drehdimmschalter_a_action"

`
esstisch_licht:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    rotate_right: hold_brightness_up # Right turn
    rotate_left: hold_brightness_down # Left turn
    rotate_stop: release # Stop right turn
    rotate_stop: release # Stop left turn
    play_pause: toggle # 1 clicks
  constrain_input_boolean: input_boolean.esszimmer_light_mode,on

esstisch_licht__bei_LightModeOff:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    rotate_right: hold_color_up # Right turn
    rotate_left: hold_color_down # Left turn
    rotate_stop: release # Stop right turn
    rotate_stop: release # Stop left turn
    play_pause: toggle # 1 clicks
  constrain_input_boolean: input_boolean.esszimmer_light_mode,off

esstisch_licht__bei_ColortempModeOn:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  min_color_temp: 153
  mapping:
    skip_forward: on_min_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,on

esstisch_licht__bei_ColortempModeOff:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  max_color_temp: 500
  mapping:
    skip_forward: on_full_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,off

esstisch_licht__ModusSwitch:
  module: controllerx
  class: CallServiceController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    skip_forward: # 2 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_colortemp_mode
    skip_backward: # 3 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_light_mode`


currently this does not work here, nothing gets changed when rotating or clicking the symfonisk. Before, the minimal-config as of this worked as expected:
` esstisch_licht:
   module: controllerx
   class: E1744LightController
   controller: sensor.drehdimmschalter_a_action
   integration: z2m
   light: light.wohnzimmer_filament_leuchten`


> I used the z2m integration as you said you were using z2m, however, I strongly recommend you to take a look to the mqtt integration since you might have a much better experience. The z2m integration interacts with the HA sensors and this slows down the process, if you use the MQTT integration, you will skip the HA machine state and interact directly with your MQTT broker. More information here.

I will definitive will have a look at this when i get the current state working :) first the function, performance comes second.

> There has been a discussion about the real mapping for this controller with Z2M, so the mappings ("rotate_left", "rotate_right", etc.) might be wrong. Please check your z2m logs to see the events fired for each action. More information here. Can you maybe help me by telling me which mapping your symfonisk controller has and which version of zigbee2mqtt you are using? Thanks!

Of course! As i just had no reaction by the script, i setup an change-trigger and debug node in NodeRED and just had a look at what it shows as action:
The payloads are:
- brightness_move_up
- brightness_move_down
- brightness_stop
- toggle  -  1 click
- brightness_step_up  - 2 click
- brightness_step_down  - 3 click

my symfonisk controller is (reported by Z2M) version: 2.1.022 and an update is avaiable right now. I will try to make the OTA and report back :)

**Comment by XRyu** [comment]
Not sure, as my OTA is currently running, so i wont restart Z2M, but MAYBE this is the key factor where the action-value might be an other: https://www.zigbee2mqtt.io/devices/E1744.html#legacy-integration

**Comment by xaviml** [comment]
Hi @XRyu,

First of all, thank you for confirming the actions that z2m fires, since it is something that needs to be updated on the documentation. The problem you have with the configuration is that I gave it to you with the old device mapping (rotate_left, rotate_right, skip_forward, etc...) so we need to change that. This is the configuration:

```yaml
esstisch_licht:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_move_up: hold_brightness_up # Right turn
    brighness_move_down: hold_brightness_down # Left turn
    brightness_stop: release # Stop right turn
    brightness_stop: release # Stop left turn
    toggle: toggle # 1 clicks
  constrain_input_boolean: input_boolean.esszimmer_light_mode,on

esstisch_licht__bei_LightModeOff:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_move_up: hold_color_up # Right turn
    brighness_move_down: hold_color_down # Left turn
    brightness_stop: release # Stop right turn
    brightness_stop: release # Stop left turn
    toggle: toggle # 1 clicks
  constrain_input_boolean: input_boolean.esszimmer_light_mode,off

esstisch_licht__bei_ColortempModeOn:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  min_color_temp: 153
  mapping:
    brightness_step_up: on_min_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,on

esstisch_licht__bei_ColortempModeOff:
  module: controllerx
  class: CustomLightController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  max_color_temp: 500
  mapping:
    brightness_step_up: on_full_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,off

esstisch_licht__ModusSwitch:
  module: controllerx
  class: CallServiceController
  controller: sensor.drehdimmschalter_a_action
  integration: z2m
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_step_up: # 2 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_colortemp_mode
    brightness_step_down: # 3 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_light_mode
```

You can use ``` to wrap some code or configuration. So you can do:

\`\`\`yaml
Some YAML configuration...
\`\`\`

I will also reopen this issue until we get this working on your side :+1:

**Comment by XRyu** [comment]
Hey Xavi, thank you for the great support :)
After changing these, it looks good - but one issue right now. When i true to turn the lights on - so issuing the "toggle" action on the controller, the lights turn on, and seem to get turned off directly :D not sure if this happens because of the way Z2M handles this? Shouldn't the new legacy:false config dont have the problem with doubled actions?

**Comment by xaviml** [comment]
It highly likely is the way z2m handles the events. Could you share z2m logs when you click to toggle?

**Comment by XRyu** [comment]
Hey Xavi, sorry it took me so long! Work weeks have been extra-hard the last weeks so please bear with me :)

I just switched my z2m to debug - clicked the switch - and turned back to log level info and extracted what was in between :)
Is still very much log.. but hopefully you can see something interesting in there?

[log - extract for xavi.txt](https://github.com/xaviml/controllerx/files/5074536/log.-.extract.for.xavi.txt)

**Comment by xaviml** [comment]
Hi @XRyu,

Sorry to answer late on this. I see in the logs that your controller fires toggle action twice when pressed (unless that is what the logs show). You could use `action_delta`, documentation says:

```
This is the threshold time between the previous action and the next one (being the same action). If the time difference between the two actions is less than this attribute, then the action won’t be called. I recommend changing this if you see the same action being called twice.
```

Be default is 300ms, you could try changing it to 500ms or 600ms. So if the same action is triggered more than 1 time within that period of time, then it will not trigger N times, just once. You will need to place this attribute for the configurations where `toggle` appears. You can read more about it in [here](https://xaviml.github.io/controllerx/start/configuration).

**Comment by XRyu** [comment]
Hey @xaviml, thank you! the latest Z-Stack Firmware from Koen seems to fixed the behavior. I now also switched to the MQTT-integration and everything works fine with this config below (for anyone who else would like this) as this is the most functional case i have seen for the 1744 until now :D

```yaml

esstisch_licht:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/Dreh-Dimmschalter - Esstisch (A)/action
  integration: mqtt
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_move_up: hold_brightness_up # Right turn
    brightness_move_down: hold_brightness_down # Left turn
    brightness_stop: release # Stop right turn
    toggle: toggle # 1 clicks
  constrain_input_boolean: input_boolean.esszimmer_light_mode,on

esstisch_licht__bei_LightModeOff:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/Dreh-Dimmschalter - Esstisch (A)/action
  integration: mqtt
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_move_up: hold_colortemp_up # Right turn
    brightness_move_down: hold_colortemp_down # Left turn
    brightness_stop: release # Stop right turn
    toggle: 
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_light_mode
  constrain_input_boolean: input_boolean.esszimmer_light_mode,off

esstisch_licht__bei_ColortempModeOn:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/Dreh-Dimmschalter - Esstisch (A)/action
  integration: mqtt
  light: light.wohnzimmer_filament_leuchten
  min_color_temp: 153
  mapping:
    brightness_step_up: on_min_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,on

esstisch_licht__bei_ColortempModeOff:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/Dreh-Dimmschalter - Esstisch (A)/action
  integration: mqtt
  light: light.wohnzimmer_filament_leuchten
  max_color_temp: 500
  mapping:
    brightness_step_up: on_full_color_temp # 2 clicks
  constrain_input_boolean: input_boolean.esszimmer_colortemp_mode,off

esstisch_licht__ModusSwitch:
  module: controllerx
  class: CallServiceController
  controller: zigbee2mqtt/Dreh-Dimmschalter - Esstisch (A)/action
  integration: mqtt
  light: light.wohnzimmer_filament_leuchten
  mapping:
    brightness_step_up: # 2 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_colortemp_mode
    brightness_step_down: # 3 clicks
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.esszimmer_light_mode
```


again - many thanks for your great work! :)
