### ISSUE TITLE
[BUG] wrong specified states for IKEA 1744?

### ISSUE THREAD

**Issue by liselotte111** [xaviml/controllerx#105]
# Bug report

## Description

My IKEA 1744 did not work. I checked ikea.py and saw "brightness_move_down" in stead of "rotate_left". Same for all the other states. I changed all the states to the ones reported by zigbee2mqtt. But might be easier for others if you changed it?

```
class E1744MediaPlayerController(MediaPlayerController):
    # Different states reported from the controller:
    # brightness_move_down, brightness_move_up, brightness_stop,
    # toggle, brightness_step_up, brightness_step_down


    def get_z2m_actions_mapping(self) -> TypeActionsMapping:
        return {
            "rotate_left": MediaPlayer.HOLD_VOLUME_DOWN,
            "rotate_right": MediaPlayer.HOLD_VOLUME_UP,
            "rotate_stop": MediaPlayer.RELEASE,
            "play_pause": MediaPlayer.PLAY_PAUSE,
            "skip_forward": MediaPlayer.NEXT_TRACK,
            "skip_backward": MediaPlayer.PREVIOUS_TRACK,
        }
```

## Additional information

* Devices involved:
  * Model: [IKEA 1744 ] as [Media Player]
  * ...
* Integration: `mqtt`
* AppDaemon version: [v4.0.3 ]
* ControllerX version: [v3.3.0]
## AppDaemon app configuration

```
volumeknop2:
  module: controllerx
  class: E1744MediaPlayerController
  controller: zigbee2mqtt/0xec1bbdfffe8b8e02/action
  integration: mqtt
  media_player: media_player.denon_ceol
  volume_steps: 25
  delay: 150
```
