### ISSUE TITLE
[BUG] E1810 dim down does not work

### ISSUE THREAD

**Issue by TheSpirit** [xaviml/controllerx#1055]
# Bug report

I own two E1810. One works perfectly, the other one works too except the dim-down button.
The working one show as zhaquirks.ikea.fivebtnremote.IkeaTradfriRemote**2**
while the one with the not working dim-down buttons shows as zhaquirks.ikea.fivebtnremote.IkeaTradfriRemote**1**

## Additional information

- Devices involved:
  - Model: [ IKEA E1810 ]
- Integration: zha
- AppDaemon version: v4.4.2
- ControllerX version: v4.7.0
- HACS version (if installed from there): 2.0.1
- Home Assistant Core version: 2024.9.2

## AppDaemon app configuration

```yaml
licht_laura:
  module: controllerx
  class: E1810Controller
  controller: 00:0d:6f:ff:fe:4a:e7:94
  integration: zha
  light: light.oberlicht_laura_licht
```
