### ISSUE TITLE
Use of HA templating for app configuration

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#108]
# Feature Request

### Is your feature request related to a problem?

As of now, the configuration does not allow you to send any template as HA automation do.

### Describe the solution / feature you'd like

AppDaemon has a method to render a template using HA plugin. These are the fields that are worth to use templating:
- `controller`
- `data` from the `mapping` attribute
- `light`, `media_player`, etc

In general, we could give the support for templating for all entries if possible.

### Additional context

For example, a configuration with templating could be:
```yaml
example_app:
  module: controllerx
  class: E1810MediaPlayerController
  integration: z2m
  controller: sensor.my_controller
  media_player: {{ states(‘sensor.current_media_player’) }}
```
