### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by mietzen** [xaviml/controllerx#1123]
# Question

I got a group containing two IKEA Lamp that support colors. From HA I can change the color for both lamps using the group:

<img src="https://github.com/user-attachments/assets/9619d3e8-e2e2-4959-b5e0-ecc2b2ab7ea5" width="300"/>

Using a E2002LightController with ControllerX I'm able to control the brightness but not the color. I tried adding `supported_color_modes: rgb` but had no luck.

I want to achieve the same as in your video: https://x.com/xaviml93/status/1227573383489085440

But with a lamp group and a E2002LightController. Is this possible? 

## Additional information

- Devices involved:
  - E2002LightController as Controller 
  - TRADFRI bulb GU10 CWS 345lm as Light
  - TRADFRI bulb E14 CWS globe 806lm as Light
- Integration: zha
- AppDaemon version:  0.16.7
- ControllerX version: 4.28.0
- HACS version (if installed from there): 2.0.1
- Home Assistant Core version: 2024.12.5

## AppDaemon app configuration

```yaml
lampen:
  module: controllerx
  class: E2002LightController
  supported_color_modes: rgb
  controller: 2c:11:65:ff:fe:94:a6:26
  integration:
    name: zha
  light: light.zimmer_lampen
  min_brightness: 10
```
