### ISSUE TITLE
CustomControl being deprecated, then how about the MFKZQ01LMLightController 

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#116]
# Question

I have a Xiaomi Magic cube set up as per the recommandation in the docs (use custom controller).
But the changelog in the latest version describes that custom controller is being deprecated?

## Additional information

* Devices involved:
  * Model: MFKZQ01LMLightController 
* Integration: deconz
* AppDaemon version: 4  0.2.6
* ControllerX version: 3.4.0
* HACS version: 1.3.3
* Home Assistant Core version: 0.114

## AppDaemon app configuration

```yaml
lians_magic_cube1:
  module: controllerx
  class: CustomLightController
  controller: lians_magic_cube
  integration:
    name: deconz
    type: gesture
  light: light.dinnertable_control
  mapping:
    6: toggle
    7: click_brightness_up
    8: click_brightness_down
    3: on_full_color_temp
    4: on_min_color_temp
```

## Additional Context

Now I don't see a warning in the log about deprecation which sort of is strange.
But as you can see, I have only 5 gestures mapped in the controllerx, I then have some handled in node-red.
If I change it to just LightController as you describe in the changelog, and I keep the mapping list, will it still only map those 5 gestures, and leave the rest alone to my node-red and automations?

**Comment by xaviml** [comment]
Hi @fribse,

Short answer: Nothing is broken, everything should be working as it already was.

Long answer:
The deprecation is just an internal change that needed to be done. Your configuration will keep working as it already was, however, you should change "CustomLightController" by "LightController" since in the future I will drop all the Custom* classes. This change couples together the custom feature with the controller base class. So you could change "CustomLightController" to "MFKZQ01LMLightController" as well. Also, you can now add call services in the mapping without needing to create a new configuration with "CallServiceController".

Thanks,
Xavi M.

**Comment by fribse** [comment]
Thankyou Xavi, you are a star, and I'm still very much impressed by the script, it has removed so many automations for me, and everything work very smoothly with this. I recommend it to everyone that is in need of a easy setup of the zigbee controllers.

I'll see if I have understood your answer correctly.
I did understand that it wouldn't fail now, but I would rather use some time now to understand it, instead of fixing it when it break :-)

As I understood your answer the config can simply be changed to this:

```
lians_magic_cube1:
  module: controllerx
  class: MFKZQ01LMLightController
  controller: lians_magic_cube
  integration:
    name: deconz
    type: gesture
  light: light.dinnertable_control
  mapping:
    6: toggle
    7: click_brightness_up
    8: click_brightness_down
    3: on_full_color_temp
    4: on_min_color_temp
```

And because I haven't set up mappings for the rest of the gestures, they are automatically excluded, or?
As I have the mappings set to the most common stuff (the 'default' setting in your script I guess) would it be better to just use exclude, and let the default mappings take over?

The last line is a bit puzzling for me, are you saying that I can call a HA service directly from controllerx? I couldn't find where that is described how do to in the docs, can you help me with that?

**Comment by xaviml** [comment]
Hi @fribse,

Thank you very much for the appreciation :)

> And because I haven't set up mappings for the rest of the gestures, they are automatically excluded, or?

Very good question. Since I didn't want to introduce any breaking changes, I decided that it will work as it did, so once you add the `mapping`, it will remove the default mapping. Answer to the question: Yes, they are excluded.

You can also put: `class: LightController` and it will work the same too.

> The last line is a bit puzzling for me, are you saying that I can call a HA service directly from controllerx? I couldn't find where that is described how do to in the docs, can you help me with that?

Sure! You can find your answer in [here](https://xaviml.github.io/controllerx/others/custom-controllers#call-service-controller). You can also find some examples in [here](https://xaviml.github.io/controllerx/examples/). Although all example should work, some of them could be refactored and be reduced to just one configuration. Here is an example for your configuration:
```yaml
lians_magic_cube1:
  module: controllerx
  class: MFKZQ01LMLightController
  controller: lians_magic_cube
  integration:
    name: deconz
    type: gesture
  light: light.dinnertable_control
  mapping:
    6: toggle
    7: click_brightness_up
    8: click_brightness_down
    3: on_full_color_temp
    4: on_min_color_temp
    2:
      service: script.your_script
      data:
        attribute1: 10
    1:
      - service: script.your_first_script
      - service: script.your_second_script
```

You can add any service you can find in "Developer Tools > Service" in Home Assistant.

I hope this helped you clarified everything, I will close this issue, but you can keep asking in here if you need.

Cheers,
Xavi M.
