### ISSUE TITLE
Implement direct MQTT group set commands from ControllerX

### ISSUE THREAD

**Issue by htvekov** [xaviml/controllerx#118]
# Feature Request

### Is your feature request related to a problem?

Nope 🙂

### Describe the solution / feature you'd like

With the recent 'upgrade' of ControllerX MQTT integration, I would love if you could expand and add the possibility in ControllerX (for z2m MQTT integration) to skip HA commands completely and control light groups/devices directly from ControllerX using MQTT group/device set commands
- For large group of lights (eg. 8 bulbs)  zigbee network gets completely overloaded and flooded with some typical 32-40 commands pr. sec. when dimming whole HA light group
- Dimming is also not completely in sync, with some bulbs always 'limping' behind - trying to catch up. Same goes for toggling large groups. On/off not completely syncronised.
- Using group set commands, dimming and toggling lights are so syncronized that it almost brings tears to your eyes 😂😉
This is the major reason why i still have my large light groups on my Hue bridge and not on my z2m network. The group commands dims and toggle lights completely in sync.
- Expected speed improvement as a bonus - No HA state machine involved (unless app is using a `constrain_input_boolean`)

### Describe alternatives you've considered

As a test I've added a custom controller to control `toggle` commands of one of my medium sized light groups in the utility room. Can't do much more than direct MQTT toggling from ControllerX, as dimming is called from ControllerX core code). This works perfectly and completely in sync 🤗

### Additional context

Below my current yaml for toggling MQTT group.

```yaml
controller_switchmode11_toggle_utility:
  module: controllerx
  class: LightController
  controller: utility_cmnd # Tasmota switchmode 11/12 switch controller
  integration:
    name: z2m
    listen_to: mqtt
    action_key: action
  light: group.utility_light
  add_transition_turn_toggle: false
  mapping:
    toggle:
      service: mqtt.publish
      data:
        topic: zigbee2mqtt/utility/set
        payload: "{\"state\":\"TOGGLE\"}"
```

Below idea for indicating in apps.yaml that MQTT group set calls should be used by adding a `send_to` key which when set to MQTT will read `light` key as a z2m device/group friendly name and not a HA entity

```yaml
controller_switchmode11_toggle_utility:
  module: controllerx
  class: LightController
  controller: utility_cmnd # Tasmota switchmode 11/12 switch controller
  integration:
    name: z2m
    listen_to: mqtt
    send_to: mqtt # Default ha (Home assistant)
    action_key: action
  light: utility # z2m friendly name for device or group (identical MQTT command)
  add_transition_turn_toggle: false
  mapping:
    toggle:
```

Simple error handling for non existing devices / groups can be done by checking z2m log topic:

```
zigbee2mqtt:info  2020-08-22 00:27:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"utilit"}}'
zigbee2mqtt:error 2020-08-22 00:27:39: Entity 'utilit' is unknown
```

Ciao !

**Comment by xaviml** [comment]
Hi @htvekov,

Sorry for the delay, I have been very busy at work lately. As I mentioned before, this won't be an easy task since ControllerX core concept is to gather the button events (input) through any source (z2m, deconz, zha, ...), but the communication once the input is treated is done through HA (output). The same way we have an `integration` attribute to state the source of the controller event, I would suggest for this a new attribute (TBD) to specify the way ControllerX communicates externally. By default will be HA as it is currently implemented, then we could have one for MQTT. However, I implemented the external communication with HA due to have an standard API, so with the same call ControllerX works for any light, media player, etc, as long as it works with HA. If I add MQTT, I will need to think of a flexible way for the user to specify the calls.

For the moment, I will leave this ticket open since it is something I would love to implement.

Cheers,
Xavi M.

**Comment by htvekov** [comment]
Hi' Xavi.

No worries 😎

Thought for a minute that you perhaps was sick ?😷
Glad it was only work! 😆

I also have given this some thoughts before making the suggestion. I known appdaemon is a direct HA extension. But still I believe it makes sense to be able to send commands as well directly through MQTT as this is a full blown, very versatile integration platform on its own as well as HA is, that doesn't need much (if any) attention once its build.

If you initially restricted outbound commands to the zigbee2mqtt platform, it would narrow down the work as the command set is quite restricted and JSON objects are quite similar to the ones used with HA already. Just a thought.

Anyway, if you decide to go on with the project at some time, I'm here for beta testing 😃

Did you see my notes about the `click` events issues that pop up now everywhere as z2m in latest version has deprecated the events ? This will for sure give a lot of questions for the next couple of months... 🙄

Have a lovely weekend, Xavi ! 🍻😎

**Comment by xaviml** [comment]
Hi Henning,

> Thought for a minute that you perhaps was sick ?
Glad it was only work! 

Thanks for worrying :) Lucky me, I am all healthy and just busy at work. I hope that you and your loved ones are well :smile: 

> If you initially restricted outbound commands to the zigbee2mqtt platform, it would narrow down the work as the command set is quite restricted and JSON objects are quite similar to the ones used with HA already. Just a thought.

This is an option, you are right. If so, your implementation would make more sense since it could be tight to the integration itself.

> Anyway, if you decide to go on with the project at some time, I'm here for beta testing smiley

Thanks! I will probably need it if I do so, you are good at spotting my most weird bugs.. haha I would like to set up integration tests in my test suite, so I will be more confident on making changes without breaking anything (or at least, break less things haha)

> Did you see my notes about the click events issues that pop up now everywhere as z2m in latest version has deprecated the events ? This will for sure give a lot of questions for the next couple of months...

Yes, I saw your comment, thank you for pointing that out. I hope it doesn't give too many problems until the stable version is released.

Also, thank you for taking care of the GitHub issues and the comments from the community forum. Now that I caught up with GitHub, I will check the community forum.

**Comment by htvekov** [comment]
Yes, we're all safe and sound here 👍😃

Z2m send commands as initial MQTT enhancement would be a more structured task, as the commands are already in place, set and vedefined. A general full MQTT implementation would be somewhat more 'loose' as commands could be absolutely anything - depending on the device you're communicating with. Just payload commands. Payload commands with JSON objects or what whatever. 

I've updated to latest stable z2m release 1.14.4 (was to curious not to 😉). Click events are (for now) only deprecated  if legacy:off is set for the device in devices.yaml. Otherwise both click and action events are fired. Will increase number of MQTT messages, but no breaking changes that way.  I believe that the new device rename option will give more issues than benefits though, if not used with care. Renaming a device in devices.yaml should remove old HA entity and create new with revised name (with HA discovery on of course). If done by unexperienced user, then all automations will most likely break.

I tried to answer those where I had knowledge to help and left all the DeCONZ and ZHA issues to you 😉

Ciao !

**Comment by xaviml** [comment]
Hi @htvekov,

I just released a beta version [v4.21.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.21.0b0) with the support of Z2M Light Controller which enables and solves this issue.

You can download from HACS enabling beta versions on ControllerX. Please, let me know if you find any problems. I will be releasing the non-beta version next week or the next.

You can read more about it [here](https://controllerx.netlify.app/controllerx/others/zigbee2mqtt-light-controller/).

Regards,
Xavi M.

**Comment by HerrmannsdoerferS** [comment]
Hi @xaviml ,
first thanks for your great work. 👍 

i've installed the beta version and struggled with the new z2m settings.

now i realised that the mqtt topic ist different. so my button actions never gets noticed.

is it possible to define the mqtt topics? in my case it has to be "topic: z2m/Office/set" instead of the default topic "zigbee2mqtt".

Best regards,
Sven

**Comment by xaviml** [comment]
Hi @HerrmannsdoerferS ,

I was not aware that the default topic could be changed. Can only the "zigbee2mqtt" part be changed in the topic? Or also the "set"?

I will add a new argument to pass to specify a custom topic and allow the topic you use.

Regards,
Xavi M.

**Comment by HerrmannsdoerferS** [comment]
Hi @xaviml ,
as far as i know it is only possible to change the "base_topic" in zigbee2mqtt, so it is used for get/set statements.

thanks for the quick reply and fix 👍 

Best regards,
Sven

**Comment by xaviml** [comment]
Hi @HerrmannsdoerferS,

I just released [ControllerX v4.21.0b1](https://github.com/xaviml/controllerx/releases/tag/v4.21.0b1) with a new attribute, `base_topic`. It allows you to specify the base topic to be sent to Zigbee2MQTT and by default is `zigbee2mqtt`. It is now included in the beta docs: https://controllerx.netlify.app/controllerx/start/type-configuration/#zigbee2mqtt-light-controller

Regards,
Xavi M.

**Comment by HerrmannsdoerferS** [comment]
Hi @xaviml ,

thanks for the quick release.

I have installed the new version and tested the following setting:
```yaml
  class: HueDimmerZ2MLightController
  integration: z2m
  controller: sensor.dimmer_esszimmer_action
  base_topic: z2m
  light:
    name: Esstisch
    mode: mqtt
```

this works as expected, but uses the ha entity of the controller.

when i try to do everything over mqtt with the following config it doen't work. am i missing something? 🤔 
```yaml
class: HueDimmerZ2MLightController 
  integration:
    name: z2m
    listen_to: mqtt
  controller: Dimmer Esszimmer
  base_topic: z2m
  light:
    name: Esstisch
    mode: mqtt   
 ```

Regards,
Sven

**Comment by xaviml** [comment]
Hi @HerrmannsdoerferS ,

I see what is happening.. so the integration part is a separate module from the controller itself. The z2m already has an attribute for the `base_topic` called `topic_prefix`, so you will need to add it inside the integration `topic_prefix: z2m`. This should work.

However, since I realised we already have the `topic_prefix`, I will move the `base_topic` inside `light` and rename it to `topic_prefix` to match the existing one in the integration block. I will do this for the next beta version.

Sorry for the confusion and thank you for the testing.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @HerrmannsdoerferS,

I just released [ControllerX v4.21.0b2](https://github.com/xaviml/controllerx/releases/tag/v4.21.0b2) with the fix mentioned in the previous comment. This means that you can now have the following configuration for your setup:

```yaml
example_app:
  class: HueDimmerZ2MLightController 
  integration:
    name: z2m
    listen_to: mqtt
    topic_prefix: z2m
  controller: Dimmer Esszimmer
  light:
    name: Esstisch
    mode: mqtt
    topic_prefix: z2m
```

Let me know if it works. In theory, this should work with only the following components:

```
Zigbee2MQTT <> MQTT broker <> AppDaemon (ControllerX)
```

This means that HA is not necessary for this communication. You can even try to restart Home Assistant and you will see that the controller can still interact with the light.

Regards,
Xavi M.
