### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by i4mr000t** [xaviml/controllerx#1185]
Cannot get my IKEA dimmer to work with groups.

My App:

```
wz_dimmer:
  module: controllerx
  class: E1810Z2MLightController
  controller: WZ Dimmer
  integration:
    name: z2m
    listen_to: mqtt
    
  light:
    name: group.wohnzimmer_gu10
    mode: mqtt
```
  
In z2m there is a message when I push the button that entity group.wohnzimmer_gu10 is unknown but it’s there.

Need help please

**Comment by i4mr000t** [comment]
This is also not working:

```
wz_dimmer:
  module: controllerx
  class: E1810Z2MLightController
  controller: WZ Dimmer
  integration:
    name: z2m
    listen_to: mqtt
    topic_prefix: z2m
  light:
    name: Wohnzimmer GU10
    mode: mqtt
    topic_prefix: z2m
```
 
As mentioned here: https://github.com/xaviml/controllerx/issues/118#issuecomment-1151478419

I don’t see anything in the logs when I press the button on the dimmer

**Comment by i4mr000t** [comment]
Solved it. 

```
wz_dimmer:
  module: controllerx
  class: E1810Z2MLightController
  controller: WZ Dimmer
  integration:
    name: z2m
    listen_to: mqtt
  light:
    name: Wohnzimmer GU10
    mode: mqtt
```
    
Don’t know if it was topic_prefix not set or missing friendly name for group in HA under MQTT Devices. 

Now it’s working.
