### ISSUE TITLE
Integration mqtt is not working

### ISSUE THREAD

**Issue by MarcE85** [xaviml/controllerx#123]
# Bug report

## Description

If i change the integration from z2m to mqtt the integration stops to work.

## Additional information

* Devices involved:
  * Model: DoubleKeyWirelessAqaraController
  * Model: TRADFRI bulb E14 W op/ch 400lm by IKEA of Sweden.
* Integration: mqtt
* AppDaemon version: 4.0,1
* ControllerX version: 3.4.0
* HACS version: 1.5.2
* Home Assistant Core version: v0.114.4

## AppDaemon app configuration

```yaml
controller_left_switch_parents:
  module: controllerx
  class: DoubleKeyWirelessAqaraController
  controller: zigbee2mqtt/remote.sleep.xiaomi/action
  light: light.0x000b57fffe8f2d22_light
  #integration: z2m
  integration: mqtt
  #manual_steps: 7
  actions:
    - left
    - left_double
    - left_long
```

**Comment by htvekov** [comment]
Hi' @MarcE85 

Only thing that springs to my mind is the odd `friendly name` for your controller.
Is your controllers `friendly name` : `remote.sleep.xiaomi` ?

Here's only of my ControllerX used sensors `entity_id` and `friendly name` from HA and MQTT setup in apps.yaml:

![image](https://user-images.githubusercontent.com/45469813/91892217-89d46580-ec92-11ea-8488-ac3cba8771bd.png)

```yaml
rasmus_controller:
  module: controllerx
  class: E1743Controller #Ikea on/off remote
  controller: 'zigbee2mqtt/Rasmus Dimmer/click' # Friendly name used in MQTT integration
  integration: mqtt
  #controller: sensor.0x14b457fffe4dc048_click  # Entity_id z2m integration
  #integration: z2m
  smooth_power_on: true
  add_transition: false
  light: light.rasmus_loft
```

MQTT integration uses the entity `friendly name` as identifier

Ciao !

**Comment by MarcE85** [comment]
> Hi' @MarcE85
> 
> Only thing that springs to my mind is the odd `friendly name` for your controller.
> Is your controllers `friendly name` : `remote.sleep.xiaomi` ?
> 
> Here's one of my ControllerX used sensors `entity_id` and `friendly name` from HA and MQTT setup in apps.yaml:
> 
> ![image](https://user-images.githubusercontent.com/45469813/91892217-89d46580-ec92-11ea-8488-ac3cba8771bd.png)
> 
> ```yaml
> rasmus_controller:
>   module: controllerx
>   class: E1743Controller #Ikea on/off remote
>   controller: 'zigbee2mqtt/Rasmus Dimmer/click' # Friendly name used in MQTT integration
>   integration: mqtt
>   #controller: sensor.0x14b457fffe4dc048_click  # Entity_id z2m integration
>   #integration: z2m
>   smooth_power_on: true
>   add_transition: false
>   light: light.rasmus_loft
> ```
> 
> MQTT integration uses the entity `friendly name` as identifier.
> 
> Ciao !

Hey @htvekov ,

yes the friendly_name is remote.sleep.xiaomi.

![image](https://user-images.githubusercontent.com/12865687/91962140-6c43e200-ed0c-11ea-8096-7350a3174e70.png)

But i think that this is not the problem, because the click action is registered. But the Light (light.0x000b57fffe8f2d22_light) won't toggle it's state.

Regards Marc

**Comment by htvekov** [comment]
Hi' @MarcE85 

I had one DoubleKeyWirelessAqaraController in the drawer. Pulled it out and had it configured without any problem (see below)

Payload command is `click` and NOT `action` in my z2m sensor. Can't really understand why you have action ?

You say that click action is registered. Registered where ? Both in appdeamon and z2m logs ?
Have you checked that friendly name in z2m logs match your HA friendly name / friendly name used in ControllerX ?

![image](https://user-images.githubusercontent.com/45469813/92027276-9b853e00-ed62-11ea-9017-6572cc209931.png)

```
[zigbee2mqtt:info  2020-09-02 21:24:15: MQTT publish: topic 'zigbee2mqtt/Xiaomi Aqara double wall switch', payload '{"battery":100,"voltage":3045,"linkquality":102,"click":"left"}'
zigbee2mqtt:info  2020-09-02 21:24:15: MQTT publish: topic 'zigbee2mqtt/Xiaomi Aqara double wall switch', payload '{"battery":100,"voltage":3045,"linkquality":102,"click":""}'
zigbee2mqtt:info  2020-09-02 21:24:15: MQTT publish: topic 'zigbee2mqtt/Xiaomi Aqara double wall switch/click', payload 'left'
zigbee2mqtt:info  2020-09-02 21:24:15: MQTT publish: topic 'zigbee2mqtt/Office bed lamp', payload '{"state":"ON","color":{"x":0.491,"y":0.39},"brightness":175,"update_available":false,"linkquality":94}'
```

```yaml
controller_left_switch:
  module: controllerx
  class: DoubleKeyWirelessAqaraController
  #controller: sensor.0x00158d00031348bf_click
  controller: zigbee2mqtt/Xiaomi Aqara double wall switch/click
  light: light.0x90fd9ffffe838cb3_light # Color bulb office
  #integration: z2m
  integration: mqtt
  manual_steps: 7
  actions:
  - left
  - left_double
  - left_long
```
