### ISSUE TITLE
[FEATURE REQUEST] TOGGLE_FULL_BRIGHTNESS

### ISSUE THREAD

**Issue by kroimon** [xaviml/controllerx#124]
# Feature Request

### Is your feature request related to a problem?

I have a Home Assistant automation for my lights that reacts to a motion sensor. When no motion is detected for a certain amount of time, the lights get dimmed to 50% for a few minutes, then turned off automatically. This leaves the last set brightness at 50%, so turning them on later using my remote control (IKEA 5-Button Remote with combined on/off button) will always turn them back on to only 50% brightness.

### Describe the solution / feature you'd like

I would love to have a TOGGLE_FULL_BRIGHTNESS action that will turn off the light of it is currently on and turn it on at full brightness if it is currently off.

### Describe alternatives you've considered

Using the existing ON_FULL_BRIGHTNESS action will not allow me to manually turn off the lights using the toggle button on the remote. If there is another way to tell the lights to always turn on at full brightness, I might consider that.

**Comment by htvekov** [comment]
Hi' @kroimon 

You could split your app in two and use a `constrain_input_boolean` in order to map toggle to `on_full_brightness` when toggling from lights off.

Example below works perfectly here with my setup.

```yaml
office_test_from_off:
  module: controllerx
  class: E1810Controller
  controller: 'zigbee2mqtt/Office Ikea 5 button/action' #Ikea 5 button remote
  integration: mqtt
  transition: 500
  automatic_steps: 8
  delay: 400
  add_transition_turn_toggle: false
  light: light.0x680ae2fffe924460_light
  constrain_input_boolean: light.0x680ae2fffe924460_light,off # This whole configuration will work when the light is on
  mapping:
    toggle: on_full_brightness
    inc-dec: sync

office_test_from_on:
  module: controllerx
  class: E1810Controller
  controller: 'zigbee2mqtt/Office Ikea 5 button/action' #Ikea 5 button remote
  integration: mqtt
  transition: 500
  automatic_steps: 8
  delay: 400
  add_transition_turn_toggle: false
  light: light.0x680ae2fffe924460_light
  constrain_input_boolean: light.0x680ae2fffe924460_light,on # This whole configuration will work when the light is on
  
```

Ciao !

**Comment by xaviml** [comment]
Hi @kroimon,

@htvekov is totally right, you can achieve this by splitting your configuration in 2. The first one you can leave it as it is, but adding: `constrain_input_boolean: light.your_light,on`. Then create a copy of that configuration and add a `mapping` attribute and the `constrain_input_boolean` like:

```yaml
example_app:
  ...
  mapping:
    toggle: on_full_brightness
  constrain_input_boolean: light.your_light,off
```

I hope this helped :)
Xavi M.
