### ISSUE TITLE
[FEATURE REQUEST] Toggle some entity based on other entity

### ISSUE THREAD

**Issue by chbndrhnns** [xaviml/controllerx#125]
# Feature Request

### Is your feature request related to a problem?

Here is my scenario for which I see no solution as of now.
- I have deconz lights and groups in HA
- in one room, there might be a mixture of motion-controlled and non-motion-controlled lights
- if motion turns a light on, all groups where this light belongs to is on (even if the other lights in the group are still off)
- Now, I switch on another light group manually using a controllerx mapping
- This basically turns off the motion-controlled light and requires another press to turn on the whole group

### Describe the solution / feature you'd like

For an entity A, I'd like to be able to configure a different entity B (probably a group) which is used to decide if a group is actually currently on or off. B would not include the motion-controlled light.

### Describe alternatives you've considered

Maybe I am missing some feature in HA or controllerx which allows such a behavior already. I am happy to learn about that!

**Comment by xaviml** [comment]
Hi @chbndrhnns,

It seems that this can be solved with callback constraints, but I didn't quite understand the problem itself. The problem is that ControllerX turns off the whole group and you need to press again to turn on all the lights? So the behaviour you are expecting is the following:
- If 1 or more lights (but not all) are on and you press the toggle button, you want the off lights to turn on.
- If all lights are off and you press the toggle button, you want the off lights to turn on.
- If all lights are on and you press the toggle button, you want the off lights to turn off.

Is this correct? If so, the solution is to change a setting on the group of lights (assuming you are using the [Group integration](https://www.home-assistant.io/integrations/group/)). You will need to add the `all: true` attribute, this way when toggling, it will turn off only if all lights are on.

Let me know if this is what you were seeking.

Regards,
Xavi M.

**Comment by chbndrhnns** [comment]
> Is this correct?

Yes. The difficulty is probably that I am using Deconz groups that do not have that `all` option IIRC. The advantage of deconz groups is that they have less delay and a single command to deconz is sufficient to toggle a group.

That is why I suggested for a specific controllers event to be able to separate the entity that is watched for the current status from the entity that is actually toggled.

I also do not know about callback constraints. What is it?

**Comment by xaviml** [comment]
> The difficulty is probably that I am using Deconz groups that do not have that all option IIRC

I think you are correct, but I am not 100% sure. The option you have to fix this is to create a HA group with `all: true` to just use it for callback constraints. They allow you to disable/enable configuration depending on the state of an entity. Imagine you have this group created in HA with the same lights, then your config would look like:

```yaml
# This app will turn OFF the lights if the group is "on", meaning that ALL lights are on
example_app_on:
  module: controllerx
  class: YourControllerClass
  controller: your_controller_id
  integration: deconz
  light: light.your_group_light
  mapping:
   1002: "off" # The 1002 is the event for the toggle (it might need to be changed) 
  constrain_input_boolean: group.your_new_ha_group,on

# This app will turn ON the lights if the group is "off", meaning that not ALL lights are on
example_app_on:
  module: controllerx
  class: YourControllerClass
  controller: your_controller_id
  integration: deconz
  light: light.your_group_light
  mapping:
   1002: "on" # The 1002 is the event for the toggle (it might need to be changed) 
  constrain_input_boolean: group.your_new_ha_group,off
```

The group you create on HA (group.your_new_ha_group) is just to see the state of the lights. The problem is that you will need to maintain both groups (HA and deconz). I cannot think of another way of doing this right now, unless deconz group allows something similar.

I will leave this issue as solved since there is nothing I can do on ControllerX for this and what I mentioned should solve the problem you had. Let me know if you try :)

Cheers,
Xavi M.
