### ISSUE TITLE
[QUESTION] Prevent volume change on player stopped in a group

### ISSUE THREAD

**Issue by mario-tux** [xaviml/controllerx#130]
# Question

I'm using a IKEA E1744 controller to control a group of chromecast devices (two sony speakers with embedded support). I created a group of media_players in HA and let ControllerX to control it. It looks to work better in this way instead to assign the Chromecast group media_player: the play/pause action works even with a single speaker activated.

I noted that ControllerX changes the volume level even when the speaker doesn't play anything: this can be annoying when the children plays with the controller when there is no music... the surprise arrives when I play something...

The question: would be possible to prevent the volume change when the player/s in the group is/are stopped? I know that I could use `constrain_input_select: media_player.single_speaker,playing` but it doesn't work with a group of players.

## Additional information

* Devices involved:
  * Model: IKEA E1744
* Integration: `deconz`
* AppDaemon version: v4.0.5
* ControllerX version: v3.4.0
* HACS version (if installed from there): v1.5.2
* Home Assistant Core version: v0.114.4

## AppDaemon app configuration

```yaml
night_zone_media_controller:
  module: controllerx
  class: E1744MediaPlayerController
  controller: night_zone_media_controller
  integration: deconz
  media_player: group.night_zone_current_players
  volume_steps: 30
  delay: 150
  #constrain_input_select: group.night_zone_current_players,playing
```

**Comment by xaviml** [comment]
Hi @mario-tux,

Thank you for your question. My first recommendation would be using the `contrain_input_select` as you are tried. I am curious that is not working for you, is the state of the `group.night_zone_current_players` `playing` when the media players are playing and `paused` or `idle` when they are not playing anything?

The only problem I see with `constrain_input_select: group.night_zone_current_players,playing` is that if you pause the media player, then you cannot play back again because it is marked to only work when `playing`. For this, you will need to configurations, one that works as normal when `playing` and another one that ignores the volume change actions when `paused` or `idle`:

```yaml
night_zone_media_controller_playing:
  module: controllerx
  class: E1744MediaPlayerController
  controller: night_zone_media_controller
  integration: deconz
  media_player: group.night_zone_current_players
  volume_steps: 30
  delay: 150
  constrain_input_select: group.night_zone_current_players,playing

night_zone_media_controller_paused:
  module: controllerx
  class: E1744MediaPlayerController
  controller: night_zone_media_controller
  integration: deconz
  media_player: group.night_zone_current_players
  volume_steps: 30
  delay: 150
  excluded_actions: [2001, 3001, 2003, 3003]
  constrain_input_select: group.night_zone_current_players,paused,idle
```

This way you can keep using the 1, 2, 3 clicks when the media players are paused or idle.

Investigate why the state for `group.night_zone_current_players` doesn't change since that is the only way I can come up with for you to solve the problem you have.

Regards,
Xavi M.

**Comment by mario-tux** [comment]
> Thank you for your question. My first recommendation would be using the `contrain_input_select` as you are tried. I am curious that is not working for you, is the state of the `group.night_zone_current_players` `playing` when the media players are playing and `paused` or `idle` when they are not playing anything?

I got two players: `media_player.display` (a Google Nest Hub Max) and `media_player.stereo` (a Chromecast Audio hooked to an old fashion HiFi). They are grouped in a Chomecast group seen by HA as a further `media_player.zona_giorno`. I created a custom group of entities in order to make it work as I wanted: `group.living_zone_current_players`. 
The group `group.living_zone_current_players` for me got always the state `off` so it can't work with `contrain_input_select` but it was useful to send the commands to all the players belonging to it.
The Chromecast group `media_player.zona_giorno` usually works with ControllerX but, if I use just one player (launched music only on the Display) or selectively (in different steps) I activate the single players, the group player stay off.

Inspired by your suggestion, what works for me is the following:

```
living_zone_media_controller_1:
  module: controllerx
  class: E1744MediaPlayerController
  controller: living_zone_media_controller
  integration: deconz
  media_player: media_player.stereo
  volume_steps: 30
  delay: 150
  constrain_input_select: media_player.stereo,playing

living_zone_media_controller_1bis:
  module: controllerx
  class: E1744MediaPlayerController
  controller: living_zone_media_controller
  integration: deconz
  media_player: media_player.stereo
  volume_steps: 30
  delay: 150
  excluded_actions: [2001, 3001, 2003, 3003]
  constrain_input_select: media_player.stereo,paused,idle

living_zone_media_controller_2:
  module: controllerx
  class: E1744MediaPlayerController
  controller: living_zone_media_controller
  integration: deconz
  media_player: media_player.display
  volume_steps: 30
  delay: 150
  constrain_input_select: media_player.display,playing

living_zone_media_controller_2bis:
  module: controllerx
  class: E1744MediaPlayerController
  controller: living_zone_media_controller
  integration: deconz
  media_player: media_player.display
  volume_steps: 30
  delay: 150
  excluded_actions: [2001, 3001, 2003, 3003]
  constrain_input_select: media_player.display,paused,idle
```

Not really elegant but it looks to work. Any kind of support to manage this kind of scenario by ControllerX? Thanks.

**Comment by xaviml** [comment]
Hi @mario-tux,

I dug a little bit on this issue and I found [this](https://community.home-assistant.io/t/is-there-a-better-way-to-do-this/146656). The problem I would say that relies on a missing config in HA than ControllerX itself. As they say, there is no way that the group can handle the different states of the media players. This is why they ended up suggesting creating a sensor template to indicate the state of the media players. So this is the sensor you will need in HA:

```yaml
sensor:
  - platform: template
    sensors:
      media_state:
        friendly_name: "Media State"
        value_template: >
          {% if is_state('media_player.display' , 'playing')
            or is_state('media_player.stereo' , 'playing') %}
              playing
          {% else %} off {% endif %}
```

Then you can just simplify your apps.yaml as:

```yaml
night_zone_media_controller_playing:
  module: controllerx
  class: E1744MediaPlayerController
  controller: night_zone_media_controller
  integration: deconz
  media_player: group.night_zone_current_players
  volume_steps: 30
  delay: 150
  constrain_input_select: sensor.media_state,playing

night_zone_media_controller_off:
  module: controllerx
  class: E1744MediaPlayerController
  controller: night_zone_media_controller
  integration: deconz
  media_player: group.night_zone_current_players
  excluded_actions: [2001, 3001, 2003, 3003]
  constrain_input_select: sensor.media_state,off
```

It still has the problem that you need to update the sensor template if you want to add new media players in the group, but it simplifies the apps.yaml. I hope this helps, I will leave ticket as closed.

Regards,
Xavi M.
