### ISSUE TITLE
[QUESTION] How to Customize the WXCJKG13LM

### ISSUE THREAD

**Issue by tioan** [xaviml/controllerx#132]
How can i set up a WXCJKG13LM for the following:

button_1_single 🠖 toggle light_1
button_1_double 🠖
button_1_triple 🠖 
button_1_hold 🠖 Brighten up light_1
button_1_release 🠖 
button_2_single 🠖 toggle light_2
button_2_double 🠖 
button_2_triple 🠖 
button_2_hold 🠖 Brighten up light_2
button_2_release 🠖 
button_3_single 🠖 toggle switch__socket_1
button_3_double 🠖 
button_3_triple 🠖 
button_3_hold 🠖 Dim down light_1
button_3_release 🠖 
button_4_single 🠖 toggle switch_socket_2
button_4_double 🠖 
button_4_triple 🠖 
button_4_hold 🠖 Dim down light_2
button_4_release 🠖 
button_5_single 🠖 Sonos join group 
button_5_double 🠖 Sonos Skip backward
button_5_triple 🠖  Sonos leave group
button_5_hold 🠖 Sonos Volume down
button_5_release 🠖 
button_6_single 🠖 Sonos Play/Pause
button_6_double 🠖 Sonos Skip forward
button_6_triple 🠖 
button_6_hold 🠖 Sonos Volume up
button_6_release 🠖

**Comment by xaviml** [comment]
Hi @tioan,

To achieve what you want, you will need to have different configurations mapping each button with its related entity:

```yaml
example_app_light_1:
  module: controllerx
  class: LightController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.light_1
  mapping:
    button_1_single: toggle
    button_1_hold: hold_brightness_up
    button_1_release: release
    button_3_hold: hold_brightness_down
    button_3_release: release
    button_3_single: # We could have this one in a different configuration, but this is shorter
      service: switch.toggle
      data:
        entity_id: switch__socket_1
    button_4_single: # We could have this one in a different configuration, but this is shorter
      service: switch.toggle
      data:
        entity_id: switch__socket_2

example_app_light_2:
  module: controllerx
  class: LightController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.light_2
  mapping:
    button_2_single: toggle
    button_2_hold: hold_brightness_up
    button_2_release: release
    button_4_hold: hold_brightness_down
    button_4_release: release

example_app_sonos:
  module: controllerx
  class: MediaPlayerController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.light_2
  mapping:
    button_5_double: previous_track
    button_5_hold: hold_volume_down
    button_5_release: release
    button_6_single: play_pause
    button_6_double: next_track
    button_6_hold: hold_volume_up
    button_6_release: release
```

The only thing I could not do was:
- button_5_single 🠖 Sonos join group
- button_5_triple 🠖 Sonos leave group

Is this `join` and `leave` something you can do with HA call services (from Developer Tools > Services)? If so, you can do something like:

```yaml
example_app_sonos:
  ...
  mapping:
   ...
   button_5_single:
     service: sonos.join
     data:
       sonos_group: xyz
   button_6_single:
     service: sonos.leave
     data:
       sonos_group: xyz
```

I obviously made up the service and the data, but you can fill it in with the real service and data.

Regards,
Xavi M.

**Comment by tioan** [comment]
```yaml

workroom_light_naddi:
  module: controllerx
  class: LightController
  controller: sensor.0x04cf8cdf3c75b0b2_action
  integration: z2m
  light: light.schreibtisch_naddi
  mapping:
    button_1_single: toggle
    button_1_hold: hold_brightness_up
    button_1_release: release
    button_3_hold: hold_brightness_down
    button_3_release: release
    button_3_single: # We could have this one in a different configuration, but this is shorter
      service: switch.toggle
      data:
        entity_id: switch__socket_1

workroom_light_mattheus:
  module: controllerx
  class: LightController
  controller: sensor.0x04cf8cdf3c75b0b2_action
  integration: z2m
  light: light.schreibtisch_mattheus
  mapping:
    button_2_single: toggle
    button_2_hold: hold_brightness_up
    button_2_release: release
    button_4_single: # We could have this one in a different configuration, but this is shorter
      service: switch.toggle
      data:
        entity_id: switch.work_room_desk_mattheus_switch
    button_4_hold: hold_brightness_down
    button_4_release: release

workroom_sonos:
  module: controllerx
  class: MediaPlayerController
  controller: sensor.0x04cf8cdf3c75b0b2_action
  integration: z2m
  media_player: media_player.arbeitszimmer
  volume_steps: 100
  delay: 100
  mapping:
    button_5_double: previous_track
    button_5_hold: hold_volume_down
    button_5_release: release
    button_6_single: play_pause
    button_6_double: next_track
    button_6_hold: hold_volume_up
    button_6_release: release

```

Works great, thx @xaviml
