### ISSUE TITLE
Multiple click events

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#144]
# Feature Request

### Is your feature request related to a problem?

Some controllers support double click by default, so when clicked twice, it will fire a special event for it. However, other controllers just support 1 click and not multiple, and since ControllerX controls the flow of the coming events, a multiple click handling events could be integrated, so the clicks are processed from ControllerX and not from the controller itself. This means that any controller with just support for 1 click will be able to be used for multiple clicks.

### Describe the solution / feature you'd like

By default, no controller will support this new feature (yet), but user will be able to configure from yaml configuration. Imagine we have the E1810 integrated with z2m. This controller fires a `toggle` action when the middle button is clicked, and we could change the default behaviour to turn on the light when clicked, instead of toggled:

```yaml
example_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.your_controller
  integration: z2m
  light: light.bedroom
  mapping:
      toggle: "on"
```

This is something we can already do with ControllerX. Now imagine that we want to call a script when toggle is clicked twice. We cannot naturally do this since the controller does not support such behaviour. For this I proposed to introduced a new token `$` to indicate on the key of the mapping how many times it is clicked:

```yaml
example_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.your_controller
  integration: z2m
  light: light.bedroom
  mapping:
      toggle: "on"
      toggle$2:
          service: my_script
```

Users will be able to indicate on the right of `$` how many clicks are needed to fire the specified event. Note that `toggle` and `toggle$1` is the same and if both are present behaviour might not be as expected. 

To achieve this, ControllerX will listen if any new event is coming in within a period of time and if not then, it will fire the event. So, if an action has a multiple click event attached the 1-click one will be affected by a small delayed before being fired, but if there is no multiple clicks for the specific event, just the 1 click, then no delay will be applied.

**Comment by xaviml** [comment]
This has been now added to ControllerX v4.0.0b1. I have tested this myself, but I would appreciate it if this gets tested by more people. Thanks :)

**Comment by htvekov** [comment]
Hi' Xavi.

Tested as well. Working ok - but I can't call $2 or $3 commands simultaneously. Only working every other time ?
First toggle$2 OK. Next toggle$2 or toggle$3 will not fire. Only 'standard' toggle command is fired. Next toggle $2/$3 fires ok again and so on.

Btw. You have to be REALLY quick on your fingers to activate double/triple action 😁 What is max delay between clicks to activate multiple clicks - 100 ms. or so ??

I would suggest that the hardcoded delay could be custom configured by user in yaml.

Ciao !

**Comment by htvekov** [comment]
I'm an idiot 🙄🙄🙄 contrain_input_booleans used in configuration... 😖
Working perfectly - every time 👍👍

**Comment by xaviml** [comment]
Hey @htvekov,

Thanks for testing out, do you still have issues after realising you had a callback constraint?

$2, $3, etc cannot be used simultaniously. I mean, if you hit the button 3 times, the $2 won't be fired, just $3. 

Regarding the delay, there is a new attribute called `multiple_click_delay`, which by default is 1000. This is the time (in milliseconds) that waits to know if another click will be fired. Imagine the next scenario:
- Button is clicked
- After 500ms button is clicked
- After 200ms button is clicked
- After 800ms button is clicked
- After 3000ms button is clicked

This will fire $3 (the first 3 clicks) and a $1 (the last click) because was pressed 3 seconds after.

I left this setting to 1000ms which is a big delay, but a safe number to wait for several clicks. You can play with it since it will vary on your network workload.

This is all explain in a new page in the documentation side, but it is not shown yet since it is a beta release, sorry for this.

I hope this clarifies some things and you can find the right setting for your setup if you are interested on this feature.

Cheers,
Xavi M.

**Comment by Paul-Vdp** [comment]
Hi Xavi,

Running latest beta, but cannot get the new multiclick to work at all. The multiclicks just are not detected ...
Could it be that this functionality is not yet added to EVERY class and/or EVERY integration ?
FYI: I'm trying to  use it with my Hue dimmers and z2m/mqtt ...

**Comment by xaviml** [comment]
Hi @Paul-Vdp,

The multi-click is independent from any class, it should work with any Controller class. Have you restarted AppDaemon addon/server after updating ControllerX? If after a restart is still not working, could you share in here your configuration and the AppDaemon logs to see what the problem might be?

Cheers,
Xavi M.

**Comment by Paul-Vdp** [comment]
Hi @xaviml,

I can confirm I restarted AD before testing.
Failing config:
```
light_remote:
#  log_level: ERROR
  module: controllerx
  class: LightController
  controller: Light Remote
  integration:
    name: z2m
    listen_to: mqtt
  light: light.evening_lights
  manual_steps: 10
  mapping:
    on-press: 'on'
    on-press$2:
      service: script.light_remote_climate
      data:
        function: turn_on
    up-press: click_brightness_up
    down-press: click_brightness_down
    off-press:
      service: script.light_remote_onoff
      data:
        function: turn_off
    off-press$2:
      service: script.light_remote_climate
      data:
        function: turn_off
    off-hold-release:
      service: script.light_remote_goodnight
      data:
        function: goodnight
```

This log excerpt shows only the single clicks are recognized. Notice also that two clicks within a one-second period are not recognized as a double-click as intended, but as two separate single clicks ...
````
2020-10-07 14:55:45.835233 INFO light_remote:   - function: turn_off
2020-10-07 14:55:45.832591 INFO light_remote: 🤖 Service: [1mscript.light_remote_onoff[0m
2020-10-07 14:55:45.829480 INFO light_remote: 🏃 Running `(>, [('script/light_remote_onoff', {'function': 'turn_off'})])` now
2020-10-07 14:55:45.826679 INFO light_remote: 🎮 Button event triggered: `off-press`
2020-10-07 14:55:45.031225 INFO light_remote:   - function: turn_off
2020-10-07 14:55:45.028164 INFO light_remote: 🤖 Service: [1mscript.light_remote_onoff[0m
2020-10-07 14:55:45.023867 INFO light_remote: 🏃 Running `(>, [('script/light_remote_onoff', {'function': 'turn_off'})])` now
2020-10-07 14:55:45.021088 INFO light_remote: 🎮 Button event triggered: `off-press`
````

Thx for looking into it.

Cheers,
Paul
