### ISSUE TITLE
[QUESTION] Possible to simplify configuration - action_delay dependt on  constrain_input_boolean

### ISSUE THREAD

**Issue by tioan** [xaviml/controllerx#148]
# Question

Hi, is there an way to simplify this working configuration?
Something like action_delay dependt on constrain_input_boolean.
If constrain_input_boolean,on the action_delay if input_boolean dont match dont apply the action_delay

## Additional information

* Devices involved:
  * Model: IKEA 1743 ] as LightController
* Integration: Choose from z2m
* AppDaemon version: v4.0.3.1
* ControllerX version: 3.5.0
* HACS version (if installed from there): 1.6.0
* Home Assistant Core version: 0.115.6

## AppDaemon app configuration

```yaml
kitchen_cabinet:
  module: controllerx
  class: E1743Controller
  controller: sensor.kitchen_cabinet_action
  integration: z2m
  light: light.hangeschrank
  constrain_input_boolean: light.decke_kuche,on

kitchen_cabinet_delayed:
  module: controllerx
  class: E1743Controller
  controller: sensor.kitchen_cabinet_action
  integration: z2m
  light: light.hangeschrank
  action_delay:
    "off": 4
  constrain_input_boolean: light.decke_kuche,off
```

**Comment by xaviml** [comment]
Hi @tioan,

Thanks for opening this ticket. I am afraid, there is no way to reduce this configuration as of now with ControllerX. This is because the `constrain_input_boolean` is part of AppDaemon and not ControllerX. 

However, I don't see the use of this configuration. The "off" action is delayed when the light is "off", so:
- If it is on, and off is pressed, then it will turn off instantly.
- If the light is off and off is pressed, then it will turn off the light (which is already off) in 4 seconds.

I think the `constrain_input_boolean` attributes are inverted, this is what I meant.

What I don't understand why you use the constraint since the off button turns the light off and it doesn't toggle it. So the configuration could be reduced to:

```yaml
kitchen_cabinet_delayed:
  module: controllerx
  class: E1743Controller
  controller: sensor.kitchen_cabinet_action
  integration: z2m
  light: light.hangeschrank
  action_delay:
    "off": 4
```

Cheers,
Xavi M.
