### ISSUE TITLE
[FEATURE REQUEST] Night mode

### ISSUE THREAD

**Issue by grostim** [xaviml/controllerx#149]
# Feature Request

I would love a "night mode" preset allowing to adjust the behaviour of a controller during certain hours.
Something similar to the option in entity_controller:
https://danobot.github.io/ec-docs/config-basic/night-mode/

For exemple a switch button could be mapped to on_full_brightness by default and on_min_brightness during night mode.

**Comment by xaviml** [comment]
Hi @grostim,

Thank you for opening this ticket. This is a configuration-specific, so it can be already done with callback constraints from AppDaemon using the [time constraint](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#time). The configuration would look like the following (assuming the ControllerX v4.0.0 which will b released this week):

```yaml
day_app:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.your_controller
  light: light.your_light
  merge_mapping:
    toggle: toggle_full_brightness
  constrain_start_time: sunrise + 00:45:00
  constrain_end_time: sunset - 00:45:00

night_app:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.your_controller
  light: light.your_light
  merge_mapping:
    toggle: toggle_min_brightness
  constrain_start_time: sunset - 00:45:00
  constrain_end_time: sunrise + 00:45:00
```

Notice that this will not work with previous versions of ControllerX due to `merge_mapping` and the new predefined actions `toggle_full_brightness` and `toggle_min_brightness`.

Since this is already possible to do and is a specific configuration not part of a default use, this ticket will remain closed.

Cheers,
Xavi M.
