### ISSUE TITLE
Is it possible to disable light control based on a HA sensor?

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#154]
# Question

I want to disable a button for halloween, is there an easy way of doing that (apart from just commenting it out in the config)?

## Additional information

* Devices involved:
  * Model: IKEA 1743 as remote
  * light group from HA.
* Integration: deconz
* AppDaemon version:  4  0.3.1
* ControllerX version: 4.1.0
* HACS version: 1.6.0
* Home Assistant Core version: 0.116.4

## AppDaemon app configuration

```yaml
bathroom:
  module: controllerx
  class: E1743Controller
  controller: bathroom_dimmer
  integration: deconz
  light: light.all_bathroom
```

**Comment by xaviml** [comment]
Hi @fribse,

By "button" you mean the whole controller or an action? I guess you mean the whole E1743 controller for example.

There is an open PR in AppDaemon that I created for that (https://github.com/AppDaemon/appdaemon/pull/1004). The proposal is to add the option to add a dot (".") in front of the name to invalidate the app. However, the PR hasn't been taking care of yet.

My workaround is to either comment the whole block, somewhat not very convenient, or add something to the configuration to not make it work. The latter is the one I used most often, but it makes the AppDaemon logs crash a bit since config is not correct. I normally add numbers to the light entity, so by adding a 2 like `light: light.all_bathroom2`, the configuration will stop working. Or you could add something to `module: controllerx`. The problem with this workaround is that is not self explanatory and your future self will be confused by how the configuration is not working :/

Anyway, I hope this helped you with your needs.

Cheers,
Xavi M.

**Comment by fribse** [comment]
Ok, so I have to do it on the day manually, that's ok.

**Comment by sreknob** [comment]
Why not use appdaemon constraints and a simple toggle in HASS as an input Boolean (especially if this is something you’re going to do more than once)
See the appdaemon docs [here](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#time)

**Comment by fribse** [comment]
Geeez, that is brilliant, just what I was looking for, but I must admit, I haven't read the entire documentation :-D

**Comment by fribse** [comment]
Now it would only work then?

I entered this:

```
bathroom:
  module: controllerx
  class: E1743Controller
  constrain_input_boolean: input_boolean.halloween,off
  controller: bathroom_dimmer
  integration: deconz
  light: light.all_bathroom
```

And I've created an input_boolean.halloween, that is set to on currently (which should disable it).

But I don't see any change 😢
