### ISSUE TITLE
Add switch controller to additional controllers

### ISSUE THREAD

**Issue by TheModin** [xaviml/controllerx#161]
Would it be possible to add switch controller to e.g WXKG02LMLightController?
I would love to be able to control Trådfri outlets with the Aqara switch.

**Comment by xaviml** [comment]
Hi @TheModin,

No problem. I will add a SwitchController to this device. In the meantime, you can use SwitchController class. Something like:

```yaml
  example_app:
    module: controllerx
    class: SwitchController
    controller: sensor.your_controller_action
    integration: z2m
    switch: switch.your_switch
    mapping:
      single_left: "on"
      single_right: "off"
```

In mapping, you can define the behaviour you desire. You can see the actions you can define in the mapping in [here](https://xaviml.github.io/controllerx/others/custom-controllers), and in [here](https://xaviml.github.io/controllerx/controllers/WXKG02LM) you will find the actions your controller fire depending on your integration.

Regards,
Xavi M.
