### ISSUE TITLE
[FEATURE REQUEST] Legacy Hue Dimmer Remote support

### ISSUE THREAD

**Issue by spelech** [xaviml/controllerx#180]
# Feature Request

### Is your feature request related to a problem?

Versions past 3.3.0 drop support for the zha_events of the older Hue Dimmer (step_##_##) .  Only option is to use older versions which may lack critical updates and code updates

### Describe the solution / feature you'd like

Implement HueDimmerControlLegacy which utilizes the older mappings.

### Describe alternatives you've considered

I have tried replacing the zha_mappings for HueDimmer with the older version events but only "On" and Release/"Stop" are recognized.  I believe this may be related to how some items in controller.py operate with the newer versions.

**Comment by xaviml** [comment]
Hi @spelech,

As a general rule for ControllerX, I just keep the latest mapping versions for the default mappings. There are of course exceptions to the rules, I would happily implement this Legacy mapping if needed. However, I would like to see if we can solve this by just setting the old mapping to your YAML code, which you said you tried. So the old mapping defined in Python code was:

```python
return {
      "on": Light.ON,
      "step_0_30_9": Light.CLICK_BRIGHTNESS_UP,
      "step_0_56_9": Light.HOLD_BRIGHTNESS_UP,
      "step_1_30_9": Light.CLICK_BRIGHTNESS_DOWN,
      "step_1_56_9": Light.HOLD_BRIGHTNESS_DOWN,
      "off_with_effect_0_0": Light.OFF,
      "stop": Light.RELEASE,
}
```

This is translated to the YAML code as:

```yaml
example_app:
  module: controllerx
  class: LightController
  controller: XX:XX:XX:XX:XX:XX
  integration: zha
  light: light.your_light
  mapping:
    "on": "on"
    "step_0_30_9": click_brightness_up
    "step_0_56_9": hold_brightness_up
    "step_1_30_9": click_brightness_down
    "step_1_56_9": hold_brightness_down
    "off_with_effect_0_0": "off"
    "stop": release
```

It is important to use `LightController` and not `HueDimmerController` in the `controller` field because if `HueDimmerController` is used, then it will not parse the actions (like "step_0_30_9") correctly.

It goes without saying that my recommendation is that you upgrade the firmware for your controller. With the old firmware, it is not possible to hold the on and off buttons as you can see in the mapping.

If this configuration does not work for you, just let me know with the AppDaemon logs so we can figure out what the problem is.

Regards,
Xavi M.
