### ISSUE TITLE
[BUG] WXKG12LM - Deconz returns 1007 (and not 1006) when shaken

### ISSUE THREAD

**Issue by cntnry** [xaviml/controllerx#184]
# Bug report

## Description
deCONZ gives "1007" as the event ID when shaking a WXKG12LM controller. ControllerX is configured to expect "1006" with this action. I don't know if this is a mistake or if there has been changes in deCONZ recently?

## Additional information

* Devices involved:
  * Model: WXKG12LMLightController
* Integration: deconz
* AppDaemon version: v4.0.5
* ControllerX version: v4.1.0
* HACS version (if installed from there): v1.6.2
* Home Assistant Core version: v0.118.3
* deCONZ version: v2.05.88

## AppDaemon app configuration

```yaml
soverom_lys:
    module: controllerx
    class: WXKG12LMLightController
    controller: smart_switch
    integration: deconz
    light: light.soverom_lys
```

## Logs

```
{
    "event_type": "deconz_event",
    "data": {
        "id": "smart_switch",
        "unique_id": "00:15:8d:00:02:5d:71:df",
        "event": 1007
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-23T21:47:13.555268+00:00",
    "context": {
        "id": "461a682f3191a936ed86192a1d699521",
        "parent_id": null,
        "user_id": null
    }
}
```
