### ISSUE TITLE
[FEATURE REQUEST] Cycle through multiple Entities

### ISSUE THREAD

**Issue by cdrfun** [xaviml/controllerx#185]
# Feature Request

### Is your feature request related to a problem?

No

### Describe the solution / feature you'd like

It would be awesome, if you could define a list of lights (or even a light group) and cycle through them. Example Workflow: Having 3 lights configured using the Ikea E1810. Clicking left/right would cycle through the lights and make the selected light blink slightly. Following controls are only applied on the selected light.

### Describe alternatives you've considered

From reading the docs I think this might be possible to achieve, but I think it would require a significant amount of configuration overhead and would not be very easy to do.

**Comment by xaviml** [comment]
Hi @cdrfun,

In my opinion, this is a very specific use case (for a specific controller) that can be solved with split configurations, so it is not in the scope to be implemented in this project. However, I can help with the configuration if needed.

First of all, you will need to create an input_select (e.g. input_select.my_lights) from HA that will indicate the light you will be switching. Let's say you create it with 3 options: light1, light2, light3.

Then you can use a configuration like the following:

```yaml
select_light_app:
  module: controllerx
  class: Controller
  controller: sensor.my_controller_action
  integration: z2m
  mapping:
    arrow_left_click:
      service: input_select.select_previous
      data:
        entity_id: input_select.my_lights
    arrow_right_click:
      service: input_select.select_next
      data:
        entity_id: input_select.my_lights

light_app_1:
  module: controllerx
  class: Controller
  controller: sensor.my_controller_action
  integration: z2m
  light: light.light1
  constrain_input_select: input_select.my_lights,light1
  excluded_actions: [arrow_left_click, arrow_right_click]

light_app_2
  module: controllerx
  class: Controller
  controller: sensor.my_controller_action
  integration: z2m
  light: light.light2
  constrain_input_select: input_select.my_lights,light2
  excluded_actions: [arrow_left_click, arrow_right_click]

light_app_3:
  module: controllerx
  class: Controller
  controller: sensor.my_controller_action
  integration: z2m
  light: light.light3
  constrain_input_select: input_select.my_lights,light3
  excluded_actions: [arrow_left_click, arrow_right_click]
```

I know this is long, but if you look at it closely it makes sense and it can be extended to other possibilities. This will make the arrow left/right clicks to switch between lights and then have the 3 apps that will work one or another depending on the selected light.

Regarding blinking slightly the light is selected, I would recommend creating an HA automation for that, so that when the input select changes (it could be changed through Lovelace as well for example), it makes the new selected light blink/flash.

I am happy to help you further with this here, but I will close the ticket.

Regards,
Xavi M.
