### ISSUE TITLE
[QUESTION] Change only WW Led in a RGBWW configuration?

### ISSUE THREAD

**Issue by Nornode** [xaviml/controllerx#217]
# Question

Can I define controllerX to change the white value for a LED light strip instead of the RGB?

## Additional information

* Devices involved:
  *  E1744 as light
  *  espHome device controlling a SK6812 lightstrip with RGBWW configuration
* Integration: z2m
* AppDaemon version: latest
* ControllerX version: latest
* HACS version (if installed from there): latest
* Home Assistant Core version: 2020.12.0

## AppDaemon app configuration

```
symfoni_dinner_table:
  module: controllerx
  class: E1744LightController
  controller: sensor.symfoni_01_action
  integration: z2m
  light: light.dinner_table_light
```

## Additional Context

Changing the RGB white causes a very cold, not nice, light in the living room, and unfortunately unrelated disturbances on the LED list. Just changing the WarmWhite leds would be much appreciated instead of all RGB leds.

**Comment by xaviml** [comment]
Hi @Nornode,

The `E1744LightController` only changes the brightness of the light. So, do you mean that you want to change the white value instead of the brightness? If so, you could refine the mapping your self with `merge_mapping` attribute:

```yaml
symfoni_dinner_table:
  module: controllerx
  class: E1744LightController
  controller: sensor.symfoni_01_action
  integration: z2m
  light: light.dinner_table_light
  merge_mapping:
    brightness_move_down: hold_white_value_down
    brightness_move_up: hold_white_value_up
    brightness_step_up: on_full_white_value
    brightness_step_down: on_min_white_value
```

This changes all the brightness actions to white value actions.

Regards,
Xavi M.
