### ISSUE TITLE
Support for Lutron Picos with updated native integration

### ISSUE THREAD

**Issue by sreknob** [xaviml/controllerx#246]
# Feature Request

Hi Xavi!

It appears that recently the native integration for Lutron hubs has been updated to include Picos when using the PRO hub. The custom component that is in use for ControllerX uses sensors as that was the custom component exposed.

In the updated native integration, Picos are no longer exposed as sensors with a state but events instead, similar to the other integrations.

The event format is now json returned for each button `press` and `release` triggers under `lutron_caseta_button_event` as per the [updated integration docs.](https://www.home-assistant.io/integrations/lutron_caseta/#pico-and-shade-remotes)

The format is:

```json
{
    "serial": 28786608,
    "type": "FourGroupRemote",
    "button_number": 4,
    "device_name": "Shade Remote",
    "area_name": "Upstairs Hall",
    "action": "press"
}
```

I presume with this available in the native integration, people will slowly be moving over to it. I haven't yet because the custom controller works so well, but I'm willing to jump ship for the native integration if my ControllerX can come with me 👍 

I can take a stab at adding it, but I won't be able to for a week or so. Just wanted to let you know in case you see people trying the get the native integration working with ControllerX and aren't having success! If you get time to look over this, it would be awesome... what would take me hours would probably take you 5 minutes! 🥇 

Thanks!
Blake

**Comment by xaviml** [comment]
Hi @sreknob,

Thank you for informing me about it. This is indeed an easy addition since I can give support for a new integration type. If I understand correctly, the important values are `button_number` and `action`.

I will add this new integration to the dev branch, so once you have the events for one of your controllers, you can let me know of the events fired for each button to integrate the controller.

Let's keep this ticket to add the new integration and a first device.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @sreknob,

I create a PR (#249) for this request. I will wait for you to provide a mapping for a controller to add it in there. Then I will release an alpha version, so you can try it out. The new integration key is `lutron_caseta`, and it parses the event to create an action like this: `button_<number>_<action type>`. So your action event would be parsed as `button_4_press`.

Once you have the controller integrated with Lutron Caseta, I will ask you to see if all events contain `buton_number` and `action`, I am assuming so in the code.

Regards,
Xavi M.

**Comment by sreknob** [comment]
Incredible Xavi, thank you so much for working on this.
Indeed, the action and button numbers are the parts required. It also returns the device type, but we shouldn't need to use that.
It looks like the actions are defined in the [device_trigger.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/lutron_caseta/device_trigger.py) of the integration if that's easy for you to look at. It's probably best for this to be complete as I only have the 2 and 5 button remotes.
I will have to wait till later to try out the integration as I've already broken zha enough times today while playing with firmware...

**Comment by xaviml** [comment]
Thank you @sreknob, I will see if I can add the integration for the 2 and 5 button ones. However, I would appreciate it if you could validate that it works since I do not have the controller. I will let you know once I add this to the PR.

**Comment by sreknob** [comment]
Thanks Xavi, I will certainly do this.
The two that I am referring to that I _believe_ I have are:
```json
PICO_2_BUTTON_BUTTON_TYPES = {
    "on": 2,
    "off": 4,
}
```
and
```json
PICO_3_BUTTON_RAISE_LOWER_BUTTON_TYPES = {
    "on": 2,
    "stop": 3,
    "off": 4,
    "raise": 5,
    "lower": 6,
}
```

**Comment by xaviml** [comment]
Hi @sreknob,

I released ControllerX v4.7.0b0 with the new support of the Lutron Caseta integration and added it for the 2 and 5 button controller. This would be the configuration for the 2 buttons one:

```yaml
example_app:
    module: controllerx
    class: LutronPJ22BLightController # LutronPJ23BRLLightController for the 5 button one
    controller: controller_id # the serial id
    integration: lutron_caseta
    light: light.your_light
```

Let me know if this works as expected, once you have time to try it out :)

Thanks,
Xavi M.

**Comment by sreknob** [comment]
Xavi, working beautifully! You are a genius, I had no doubts it would work perfectly the first time!!

I've posted my configs below for my Picos with multiple functions, just in case it's helpful for someone migrating and so I can perhaps pick your brain for a moment.

The basement one just adds the ability of the off button to turn off all the lights rather than just the lamps in the first controller. Seeing that I hadn't updated these configs in a very long time, I reviewed them to see if there were ways to make them shorter. Is there a better way to do what I'm doing here? I can't use `merge_mapping` as I still want the lamps to turn off as well. Actually, I just realized that I CAN use `merge_mapping` and just add an additional service call to turn the lamps off as well. Thanks for talking this out with me, it was very helpful. LOL!

The Office Lamp/3D printer one uses 4 of the buttons to control the lamp next to my printer, the middle button toggles the power to my printer, but only if it is not actively printing. Currently I use `constrain_input_boolean` to make sure it's not accidentally turned off while a print is in process (by my children). Is there a better way to do this with the new templates function and `merge_mapping` rather than two separate controllers? Just asking seeing that I have you here :-) I WAS able to clean this config up by using `exclude` however, very nice!

Thanks again!
Blake

<details><summary>New Configs</summary>
<p>

```yaml
#################################################
#             Basement Stairs Pico              #
#################################################

BasementLampsPico:
  module: controllerx
  class: LutronPJ23BRLLightController
  integration: lutron_caseta
  controller: 42987341
  light: light.basement_lamps
  smooth_power_on: true
  
BasementLampsPicoOFF:
  module: controllerx
  class: Controller
  integration: lutron_caseta
  controller: 42987341
  mapping:
    "button_4_press":
      - service: light.turn_off
        data:
          entity_id: light.basement_exercise_area
      - service: light.turn_off
        data:
          entity_id: light.basement_pool_table
      - service: light.turn_off
        data:
          entity_id: light.basement_play_area

#################################################
#           Office Pico / 3D Printer            #
#################################################

3DPrinterPower:
  module: controllerx
  class: Controller
  integration: lutron_caseta
  controller: 42842413
  constrain_input_boolean: binary_sensor.tevo_tornado_printing,off
  mapping:
    "button_3_press": # Favourite Button
      service: switch.toggle
      data:
        entity_id: switch.octopowerbar_1

OfficeWorkLight:
  module: controllerx
  class: LutronPJ23BRLLightController
  integration: lutron_caseta
  controller: 42842413
  light: light.office_work_light
  smooth_power_on: true
  exclude:
    "button_3_press"

```
</p>
</details>

<details><summary>OLD Configs</summary>
<p>

```yaml
#################################################
#             Basement Stairs Pico              #
#################################################

BasementLampsPico:
  module: controllerx
  class: LutronCasetaProPicoLightController
  integration: state
  controller: sensor.basement_stairs_pico
  light: light.basement_lamps
  smooth_power_on: true
  
BasementLampsPicoOFF:
  module: controllerx
  class: Controller
  integration: state
  controller: sensor.basement_stairs_pico
  mapping:
    "4":
      - service: light.turn_off
        data:
          entity_id: light.basement_exercise_area
      - service: light.turn_off
        data:
          entity_id: light.basement_pool_table
      - service: light.turn_off
        data:
          entity_id: light.basement_play_area

#################################################
#           Office Pico / 3D Printer            #
#################################################

3DPrinterPower:
  module: controllerx
  class: Controller
  integration: state
  controller: sensor.office_pico
  constrain_input_boolean: binary_sensor.tevo_tornado_printing,off
  mapping:
    "2": # Favourite Button
      service: switch.toggle
      data:
        entity_id: switch.octopowerbar_1

OfficeWorkLight:
  module: controllerx
  class: LightController
  integration: state
  controller: sensor.office_pico
  light: light.office_work_light
  smooth_power_on: true
  mapping:
    "1": "on_full_brightness"
    "8": "hold_brightness_up"
    "16": "hold_brightness_down"
    "4": "off"
    "0": "release"

```

</p>
</details>
