### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

### ISSUE THREAD

**Issue by jamescadd** [xaviml/controllerx#25]
Hello - I'm trying to use the E1744 controller with ZHA and ran into the following issue.  This is my first use of AppDaemon so I could have done something wrong, and I had to setup the appdaemon.yaml and apps.yaml manually, I believe because I installed the AppDaemon hass.io (home assistant now) plugin after I had installed controllerx via HACS.  Here is the log & apps.yaml config:

2020-02-08 16:20:40.115178 INFO AppDaemon: Initializing app test_controller using class E1744LightController from module controllerx
2020-02-08 16:20:40.116050 WARNING test_controller: ------------------------------------------------------------
2020-02-08 16:20:40.116359 WARNING test_controller: Unexpected error initializing app: test_controller:
2020-02-08 16:20:40.116629 WARNING test_controller: ------------------------------------------------------------
2020-02-08 16:20:40.117096 WARNING test_controller: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

test_controller:
  module: controllerx
  class: E1744LightController
  controller: (ieee address)
  integration: zha
  light: light.hue_color_lamp_1

**Comment by xaviml** [comment]
I am guessing this is a problem with your `appdaemon.yaml` configuration. It should look like this:
```yaml
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```
