### ISSUE TITLE
[BUG] invalid checksum - stops working after 2 seconds. 

### ISSUE THREAD

**Issue by xdenneboom** [xaviml/controllerx#250]
# Bug report

## Description
When everything is set up, the controller works. the wheel controls volume. but after a few seconds stops responding. None of my controllers work anymore, until I reboot the appDaemon or Homeassistant
Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

every action that is performed, results in the invalid checksum warning in the log. But it still works. When I get a warning in the AppDaemon log, things stop working. 

## Additional information 
* Devices involved:
  * IKEA E1744 as Media Player  
  * IKEA ICTCG1 as Light
* Integration: Choose from `zha`
* AppDaemon version: v4 0.4.3 
* ControllerX version: v4.6.0
* HACS version (if installed from there): v1.11.3
* Home Assistant Core version: 2021.2.3

## AppDaemon app configuration

```yaml
---
ikea_sonos_wheel:
  module: controllerx
  class: E1744MediaPlayerController
  controller: ec:1b:bd:ff:fe:8b:97:ea
  integration: zha
  media_player: media_player.living_room
  actions:
    - move_1_195 #Left turn
    - move_0_195 #Right turn
    - stop #Stop rotation
    - toggle #1 click

ikea_bathroom_wheel:
  module: controllerx
  class: ICTCG1Controller
  controller: 00:0b:57:ff:fe:90:70:83
  integration: zha
  light: light.bathroom
```

## Logs
**AppDaemon log:**
```text
🤖 Service: media_player.volume_set
  - entity_id: media_player.living_room
  - volume_level: 0.20
2021-02-20 18:16:53.336529 INFO ikea_sonos_wheel: 
🤖 Service: media_player.volume_set
  - entity_id: media_player.living_room
  - volume_level: 0.10
2021-02-20 18:16:53.734866 WARNING AppDaemon: callback idle has now completed
```

**Homeassistant log:** 
```
Invalid checksum: 0xdbfe, data: 0x98c840410441bf
6:16:23 PM – /usr/local/lib/python3.8/site-packages/zigpy_deconz/uart.py (WARNING) - message first occurred at February 19, 2021, 8:10:58 PM and shows up 292 times

Logger: zigpy_deconz.uart
Source: /usr/local/lib/python3.8/site-packages/zigpy_deconz/uart.py:83
First occurred: February 19, 2021, 8:10:58 PM (292 occurrences)
Last logged: 6:16:23 PM
Invalid checksum: 0xdbfe, data: 0x98c840410441bf
Invalid checksum: 0x3cfe, data: 0x98c440410441bf9c3cfe98c840010441bf9c
Invalid checksum: 0xf8fc, data: 0x98e840010441bf993cfe98ec40010441bf9d
Invalid checksum: 0x79fc, data: 0xd8a6700002d2f898e840010401c29d
Invalid checksum: 0xf2f8, data: 0xd8f6708004c8f8d8da700004c9f8d8fe700004c9f898e040410401c29df2f898e440010401c29c
```
```
[0x28e8:1:0x0008] Data remains after deserializing ZCL frame
6:16:20 PM – /usr/local/lib/python3.8/site-packages/zigpy/zcl/__init__.py (WARNING) - message first occurred at February 19, 2021, 8:24:43 PM and shows up 55 times
Logger: zigpy.zcl

Source: /usr/local/lib/python3.8/site-packages/zigpy/zcl/__init__.py:123
First occurred: February 19, 2021, 8:24:43 PM (55 occurrences)
Last logged: 6:16:20 PM
[0x28e8:1:0x0008] Data remains after deserializing ZCL frame
```

## Additional Context
I've initially had seperate scenes for the double and tripple press configured, but I commented that out to scope down the problem, which still persists.
