### ISSUE TITLE
[QUESTION] Is it possible to configure different entities for different endpoints?

### ISSUE THREAD

**Issue by bens0n** [xaviml/controllerx#255]
# Question
Is it possible to have different entities controlled by different endpoints by default? I have a dual-gang dimmer switch ([AU-A1ZBR2GW](https://auroralighting.com/gb/trade/ProductDetail/AU-A1ZBR2GW); [z2m implementation](https://github.com/Koenkk/zigbee-herdsman-converters/blob/48cc9d922253572131b9469e80c1c8efb2cb0256/devices.js#L15687-L15708); [under-development zha implementation](https://github.com/zigpy/zha-device-handlers/issues/795)) that I am writing a controller for. I would like each knob to control a different light group.  I can see in e.g. the [Legrand controllers](https://github.com/xaviml/controllerx/blob/dev/apps/controllerx/cx_devices/legrand.py) that we can automatically modify the zha mappings to include the endpoint, which will allow me to double-up the commands (on, off, brightness_step_up, ..., per endpoint), but by default I think these will all apply to the same entity. Do I have to then override all the commands for the second endpoint in the configuration via mapping, or is there a simple way to configure endpoint 1 entity and endpoint 2 entity independently?

**Comment by bens0n** [comment]
Having posted this, I have since answered my own question. Using the "actions" filter in the module configuration, you can assign which possible actions are assigned to each instance. Example attached below in case it's helpful to anyone.
```
living_room_lamps_controller:
  module: controllerx
  class: AUA1ZBR2GWLightController
  controller: 00:0d:6f:ff:fe:c1:c7:42
  integration: zha
  delay: 100
  light: light.living_room_lamps
  actions:
    - 2_toggle
    - 2_step_up
    - 2_step_down
    - 2_step_color_temp_up
    - 2_step_color_temp_down

living_room_overhead_light_controller:
  module: controllerx
  class: AUA1ZBR2GWLightController
  controller: 00:0d:6f:ff:fe:c1:c7:42
  integration: zha
  delay: 100
  light: light.living_room_overhead_lights
  actions:
    - 1_toggle
    - 1_step_up
    - 1_step_down
    - 1_step_color_temp_up
    - 1_step_color_temp_down
```
