### ISSUE TITLE
[NEW DEVICE] Magnet Sensor support

### ISSUE THREAD

**Issue by hollowboarder** [xaviml/controllerx#269]
# New Device Support

## Device Information

- Device Model: MCCGQ11M
- Device Description: Magnet Sensor 
- Device Manufacturer: Aqara 

#### Actions

button is pressed: 
"event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:03:21:ad:a9",
        "unique_id": "00:15:8d:00:03:21:ad:a9:1:0x0006",
        "device_id": "be3e021dfc508351ed4a112b3b4f9d38",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": 0
button is released:
"event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:03:21:ad:a9",
        "unique_id": "00:15:8d:00:03:21:ad:a9:1:0x0006",
        "device_id": "be3e021dfc508351ed4a112b3b4f9d38",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": 1

**Comment by xaviml** [comment]
Hi @hollowboarder,

As I mentioned to you through email, the aqara door sensor is not a controller, so it will not be added as a default controller. This doesn't mean that you cannot integrate it with ControllerX.

Imagine you have a `sensor.door_contact` that goes `on` and `off` depending on the state. A first and basic configuration you could have is the following:

```yaml
example_app:
  module: controllerx
  class: Controller
  controller: sensor.door_contact
  integration: state
  light: light.your_light
  mapping:
    "on": "on"
    "off": "off"
```

This will turn on/off the light depending on the state of the door contact. A second and more advanced configuration could be the following:

```yaml
example_app:
  module: controllerx
  class: Controller
  controller: sensor.door_contact
  integration: state
  light: light.your_light
  action_delta: 1000
  mapping:
    "on": hold_brightness_toggle
    "on$2": "off"
    "off": release
  constrain_input_boolean: light.your_light,on

example_app_2:
  module: controllerx
  class: Controller
  controller: sensor.door_contact
  integration: state
  light: light.your_light
  action_delta: 1000
  mapping:
    "on": "on"
  constrain_input_boolean: light.your_light,off
```

The first configuration will work the following when light is "on":
- brightness up/down your light when door contact state is "on"
- stops the brightness up/down when door contact state is "off"
- turns off the light when door contact state goes "on" twice within a second (`action_delta`)

The second configuration will work the following when the light is "off":
- Turn on the light when door contact state is "on"

You might need some configuration tweaking, but this is a first implementation I would recommend you for what I know.

Let me know what you think, and if you have problems with it. Happy to help further.

Regards,
Xavi M.

**Comment by hollowboarder** [comment]
Hey Xavi!

thanks a lot. I tried but no progress

i tried the following code:
`example_app:
  module: controllerx
  class: Controller
  controller: binary_sensor.lumi_lumi_sensor_magnet_aq2_dd00a001
  integration: state
  light: light.bf15d2cca618a48e8etalr
  mapping:
    "on": "on"
    "off": "off"`

also tried it this way:

`example_app:
  module: controllerx
  class: Controller
  controller: 00:15:8d:00:01:a0:00:dd
  integration: state
  light: llight.bf15d2cca618a48e8etalr
  mapping:
    "on": "on"
    "off": "off"`

the light dont respond to the magnet sensor
Have i made a mistake there ?

**Comment by xaviml** [comment]
Hi @hollowboarder,

Does the `binary_sensor.lumi_lumi_sensor_magnet_aq2_dd00a001` takes `on` and `off` states?

Could you maybe share the AppDaemon logs when it initiazes and press the button?

The first configuration is the way to go. It seems right to me, so there should be some communication not working properly.

Regards,
Xavi M.

**Comment by hollowboarder** [comment]
this is what the log tells me when i save the apps.yaml
seems something wrong, but i have no clue whats wrong there ?

2021-04-03 22:34:37.423266 WARNING example_app: ------------------------------------------------------------
2021-04-03 22:34:37.423881 WARNING example_app: Unexpected error running initialize() for example_app
2021-04-03 22:34:37.424443 WARNING example_app: ------------------------------------------------------------
2021-04-03 22:34:37.425611 WARNING example_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 101, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 117, in init
    self.actions_mapping = self.parse_action_mapping(custom_mapping)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 241, in parse_action_mapping
    return {event: parse_actions(self, action) for event, action in mapping.items()}
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 241, in <dictcomp>
    return {event: parse_actions(self, action) for event, action in mapping.items()}
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/__init__.py", line 30, in parse_actions
    return [_parse_action(controller, action) for action in actions]
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/__init__.py", line 30, in <listcomp>
    return [_parse_action(controller, action) for action in actions]
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/__init__.py", line 35, in _parse_action
    return PredefinedActionType(controller, {"action": action})
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/base.py", line 15, in __init__
    self.initialize(**action)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 35, in initialize
    raise ValueError(
ValueError: Cannot use predefined actions for `Controller` class.
2021-04-03 22:34:37.426174 WARNING example_app: ------------------------------------------------------------

**Comment by xaviml** [comment]
Sorry, the `class` should be `LightController`, not `Controller`.

**Comment by hollowboarder** [comment]
works :) but for switch on the light i have to hold the button down. if i release the button the light went off. is there any solution for following behavior:
button press (sensor state off -> to -> sensor state on) : light on
button press (sensor state off -> to -> sensor state on) : light off (if light was on previosly)

**Comment by xaviml** [comment]
Not sure what the behaviour of sensor is, and how the switch work. But sounds like the state is always "off", and you have a toggle switch (so it bounces back to original possition after pressing), so it goes to "on" while you are pressing. Is that correct?

What you are looking for is that when "on" is fired, you want the light to toggle, so:

```yaml
example_app:
  module: controllerx
  class: LightController
  controller: binary_sensor.lumi_lumi_sensor_magnet_aq2_dd00a001
  integrate: state
  light: light.bf15d2cca618a48e8etalr
  mapping:
    "on": "toggle"
```

**Comment by hollowboarder** [comment]
exactly.. this is what behaviour of the switch is! always "off" and when press "on"...
i get this log ?


2021-04-03 23:03:04.066815 WARNING example_app_3: ------------------------------------------------------------
2021-04-03 23:03:04.068098 WARNING example_app_3: Unexpected error running initialize() for example_app_3
2021-04-03 23:03:04.069132 WARNING example_app_3: ------------------------------------------------------------
2021-04-03 23:03:04.070614 WARNING example_app_3: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 101, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 125, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 39, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py", line 18, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 105, in init
    self.integration = self.get_integration(self.args["integration"])
KeyError: 'integration'
2021-04-03 23:03:04.072233 WARNING example_app_3: ------------------------------------------------------------

**Comment by xaviml** [comment]
Sorry, I typed `integrate` instead of `integration`. I just changed the `mapping` side of the configuration.

**Comment by hollowboarder** [comment]
works! you are the best !! 

on this behaviour for the switch how i should change the second solution with dimming on "holding" button down.. is there any chance to get it working like this:

button press short (sensor state off -> to -> sensor state on) : light on
button press long (sensor state off -> to -> sensor state on) : light dims up
button press long again in lets say 1sec. (sensor state off -> to -> sensor state on) : light dims down
button press short (sensor state off -> to -> sensor state on) : light off (if light was on previosly)

**Comment by xaviml** [comment]
Also, once you get the basic configuration working, then the more advanced one should be something different now that I know how it behaves.

Since ControllerX just knows "on" and "off", there is no way to distinguish short press from long one. So, I would recommend 1 press for toggling the light, and 2 presses to dim the light:

```yaml
example_app:
  module: controllerx
  class: LightController
  controller: binary_sensor.lumi_lumi_sensor_magnet_aq2_dd00a001
  integratation: state
  light: light.bf15d2cca618a48e8etalr
  multiple_click_delay: 500 # default
  mapping:
    "on": "toggle"
    "on$2": hold_brightness_toggle
    "off": release
```

So if I am not mistaken, with this you should be able to double-click, but keep the 2nd click press to dim the light, and release once you are satisfied with the brightness. For the better experience, you can play with the `multiple_click_delay`, which is the delay to recognize a click is double or not in your case.

Then, if you're interested in tinkering the light speed when dimming, then you can change `delay` (350 default) and/or `automatic_steps` (10 default). You can read more about them in [here](https://xaviml.github.io/controllerx/start/type-configuration).

Regards,
Xavi M.

**Comment by hollowboarder** [comment]
getting closer.. maybe one last "mal-function" when double-click and holding the second click the lights went off. 
Now it works like this:
single press: lights on
double press: dim up
double press: dim down
single press: lights off

is this the right way to enable smooth_power_on ?
  
smooth_power_on: true

**Comment by xaviml** [comment]
If the lights go off when double clicking, then you will need to put the `multiple_click_delay` higher. Also, since it is ControllerX who detects de double click (and not the device as other do), I recommend you to do an slow double click with a high `multiple_click_delay` (1000 for example).

The `smooth_power_on` it turns on the light to minimum brightness if the action is brightness up and the light was off. You could enable it, but then it would make more sense to double-click for toggle and 1 click for brightness up/down, which you could also try:

```yaml
example_app:
  module: controllerx
  class: LightController
  controller: binary_sensor.lumi_lumi_sensor_magnet_aq2_dd00a001
  integratation: state
  light: light.bf15d2cca618a48e8etalr
  multiple_click_delay: 500 # default
  mapping:
    "on$2": "toggle"
    "on": hold_brightness_toggle
    "off": release
```

My recommendation is that you play around with that configuration until you find the right settings, it is difficult to control different action with just 2 states, this is why you are having these problems.
