### ISSUE TITLE
[NEW DEVICE] Hue wall switch module

### ISSUE THREAD

**Issue by yveshass** [xaviml/controllerx#276]
- Device Model: RDM001
- Device Description: Hue wall switch module
- Device Manufacturer: Signify Netherlands B.V. (previously known as Philips)

deCONZ
1000 → Click
1001 → Hold
1002 → Click release
1003 → Hold release
2000 → Click
2001 → Hold
2002 → Click release
2003 → Hold release

"Taken from https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4566

devicemode | first input | second input
singlerocker | 1000, 1002 | --
singlepushbutton | 1000, 1001, 1002, 1003 | --
dualrocker | 1000, 1002 | 2000, 2002
dualpushbutton | 1000, 1001, 1002, 1003 | 2000, 2001, 2002, 2003

When configured as rocker, it will issue a x000/x002 each time you flip the rocker (to either position). The event duration for the x002 is 1 (for 100ms), but lastupdated suggests it follows the x000 faster than that.

When configured as pushbutton, it will issue a x000/x002 sequence on press/release, and an x000/x001/.../x001/x003 on press/hold/release, similar to the Hue dimmer switch and the Hue smart button. The eventduration increased with 8 for each x001, and they are issued pretty much every 800ms."

#### Notes

Click → Toggle
Hold → Brightness up/down with direction changes (only applicable if configured as pushbutton)

**Comment by oscfor** [comment]
Can we include it in z2m as well?

MQTT publish: topic 'zigbee2mqtt/Vind - rörelse', payload '{"battery":100,"linkquality":0,"occupancy":true,"voltage":3005}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press_release","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press_release'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press_release","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press_release'


MQTT publish: topic 'zigbee2mqtt/Vind - rörelse', payload '{"battery":100,"linkquality":0,"occupancy":true,"voltage":3005}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press_release","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press_release'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_press_release","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":null,"linkquality":0,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_press_release'

**Comment by xaviml** [comment]
Hi @yveshass and @oscfor,

Thank you for opening the issue. I will be adding this device for both integrations for the next release.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @oscfor,

I see in the zigbee2mqtt documentation and your logs that available actions are: "left_press, left_press_release, right_press, right_press_release". deCONZ has press, hold, and release for left and right (6 in total). However, for z2m I only see 4, so wondering which ones are they since hold does not make sense without a release.

Cheers,

**Comment by oscfor** [comment]
Hi @xaviml 

I have now tried again. Now I also get the "hold" state and "hold_release" 

Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_hold","battery":100,"device_mode":"dual_push_button","linkquality":42,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":"dual_push_button","linkquality":42,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_hold'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_hold","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_hold'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_hold","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_hold'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_hold","battery":100,"device_mode":"dual_push_button","linkquality":42,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":"dual_push_button","linkquality":42,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_hold'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"left_hold_release","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp', payload '{"action":"","battery":100,"device_mode":"dual_push_button","linkquality":39,"update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/Badrum knapp/action', payload 'left_hold_release'

**Comment by xaviml** [comment]
Device added in ControllerX [v4.11.0](https://github.com/xaviml/controllerx/releases/tag/v4.11.0)

**Comment by JDFS404** [comment]
Nice @xaviml for adding this, I just bought a couple of them and also have double push buttons (Jung 535EU). So I just set up the integration in `apps.yaml` but I was wondering, could you maybe change some settings to utilize the `dual_push_button` element of the Switch? I.e. `left_press` is for light1/group1 and `right_press` is for light2/group2? Because I just added the Switch and with both push buttons it's controlling only 1 group. Let me know your thoughts on this and how we can practical deal with this?

Btw thanks for making ControllerX, it's really really cool and so much better that I even tossed the Hue Bridge out of the equation!

**Comment by xaviml** [comment]
Hi @JDFS404,

ControllerX was first design that one app controls 1 light or group of lights, so with just using one app you cannot control different lights with different states. However, this doesn't mean you cannot configure it with 2 apps pointing to the same controller. This is an example of this controller using the left actions for 1 light, and the right actions for another light:

```yaml
example_app_light_1:
  module: controllerx
  class: Philips929003017102LightController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.light_1
  actions: [left_press, left_hold, left_hold_release]

example_app_light_2:
  module: controllerx
  class: Philips929003017102LightController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.light_2
  actions: [right_press, rightt_hold, right_hold_release]
```

Hope this helps :)

Regards,
Xavi M.

**Comment by JDFS404** [comment]
Perfect @xaviml this is what I was looking for! On another note, I am in the process of figuring it out, but need some guidance; I have another Hue Smart Switch close my entrance that I want to use as a master switch to toggle ALL my lights (in my `group.lights_all`). However, I want the switch to kill all the lights and not toggle it, i.e. if the kitchen lights are on and the rest is off, I don’t want this switch to turn on all the lights but NOT the kitchen lights (since they’re on they’re toggled to off). I think I have to do something with mapping, but perhaps you can help me out!

**Comment by xaviml** [comment]
Hi @JDFS404,

The Hue Smart switch already calls "on" and "off", and not "toogle". So could you please show your ControllerX config, so I can point you to how to fix this problem? To do so, you would need to use `merge_mapping` and change the event action to `off`. You can read more about it [here](https://xaviml.github.io/controllerx/advanced/custom-controllers).

Regards,
Xavi M.

**Comment by JDFS404** [comment]
Thanks again Xavi, perhaps I should look into `merge_mapping` combined with the actions for the right- and left presses. This is my code now for the different Hue Switch modules. I tried something with `merge_mapping`, but I got errors when combining it with the action right- and left presses. Curious how this can be solved :) :

```
# Configuration check
check_config:
  module: checkconfig
  class: CheckConfig

# Lampen en groepen
slaapkamer_controller:
  module: controllerx
  class: E1744LightController
  controller: zigbee2mqtt/IKEA Symfonisk/action
  integration: mqtt
  smooth_power_on: true
  light: group.slaapkamer_light
  
# Slimme muurschakelaars
woonkamer_switch_1:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_woonkamer_1/action
  integration: mqtt
  light: group.all_light
  actions: [right_press, right_hold, right_hold_release]
  
woonkamer_switch_2:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_woonkamer_1/action
  integration: mqtt
  light: group.keuken_light
  actions: [left_press, left_hold, left_hold_release]
  
woonkamer_switch_3:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_woonkamer_2/action
  integration: mqtt
  light: group.woonkamer_light
  actions: [right_press, right_hold, right_hold_release]
  
switch_woonkamer_4:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_woonkamer_2/action
  integration: mqtt
  light: group.eettafel_light
  actions: [left_press, left_hold, left_hold_release]
  
switch_eettafel:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_eettafel/action
  integration: mqtt
  light: group.eettafel_light
  actions: [right_press, right_hold, right_hold_release]
  
switch_gang:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: light.gang
  actions: [right_press, right_hold, right_hold_release]

switch_all:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  actions: [left_press, left_hold, left_hold_release]

switch_slaapkamer_1:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_slaapkamer/action
  integration: mqtt
  light: light.hue_bureau
  actions: [left_press, left_hold, left_hold_release]

switch_slaapkamer_2:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_slaapkamer/action
  integration: mqtt
  light: group.slaapkamer_light
  actions: [right_press, right_hold, right_hold_release]

```

**Comment by xaviml** [comment]
Hi @JDFS404,

Sorry for the confusion... I thought you were referring to the standard Hue Dimmer Switch. But you mean the switch module (which is the one from this ticket..). Don't know what I was thinking haha

You have these options to solve this, and they imply using the merge_mapping (o mapping):
- Use left click to turn off and right click to turn on (or vice versa).
- Use click to turn on and long press to turn off (or vice versa).

Since I see you use left and right separately, then, I would show you the second option:

```yaml
switch_all:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    left_press: "on"
    left_hold: "off"
```

The mapping will remove the default mapping and define the mapping define in the `mapping` attribute. The problem of this solution is that you lose the ability to dim the lights. So if you still want to dim the lights, then you could use double click (a functionality from ControllerX - https://xaviml.github.io/controllerx/advanced/multiple-clicks):

```yaml
switch_all:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  merge_mapping:
    left_press: "on"
    left_press$2: "off"
```

So 1 click will turn on the lights and 2 clicks will turn them off. The dimming will keep working because we used `merge_mapping` for this configuration.

Hope this helps, and happy to help further if needed :)

Regards,
Xavi M.

**Comment by JDFS404** [comment]
Hey Xavi,

Thanks again, much appreciate your help here. Donation's coming up!

So I just added your config to `apps.yaml` as follows (notice that gang = hallway, schakelaar = switch... I should change all my wordings to English to make troubleshoot easier):
```
switch_gang:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: light.gang
  actions: [right_press, right_hold, right_hold_release]

switch_all:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    left_press: "on"
    left_hold: "off"

switch_all:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  merge_mapping:
    left_press: "on"
    left_press$2: "off"
```
So the left side of the switch is working as intended :). When I switch all lights on and switch some of them off via other switches / HA / MQTT, I double click and everything turns off! However, I now am facing the issue that also `right_press` is triggered via `switch_all`:
```
🤖 Service: [1mlight.toggle[0m
  - entity_id: group.all_light
2021-05-22 10:43:36.207343 INFO switch_all: 🏃 Running `Predefined (toggle)` now
2021-05-22 10:43:36.191882 INFO switch_gang: 

🤖 Service: [1mlight.toggle[0m
  - entity_id: light.gang
2021-05-22 10:43:36.091799 INFO switch_gang: 🏃 Running `Predefined (toggle)` now
2021-05-22 10:43:36.029590 INFO switch_all: 🎮 Button event triggered: `right_press`
2021-05-22 10:43:35.906389 INFO switch_gang: 🎮 Button event triggered: `right_press`
2021-05-22 10:43:35.478731 INFO switch_all: 🏃 Running `Predefined (release)` now
2021-05-22 10:43:35.443877 INFO switch_gang: 🏃 Running `Predefined (release)` now
2021-05-22 10:43:35.419729 INFO switch_all: 
```
I also tried adding the same code for my `switch_gang` with `merge_mapping` and `right_press$2`, but then the left switch is also triggered... I'm feeling we're almost there!

**Comment by xaviml** [comment]
Hi @JDFS404,

I see that you have 2 applications with the same name (`switch_all`). So, you either have one or another, depending on how you want the lights to turn on/off. Either with click and long press, or with click and double click.

Also, I do not see the `right_press$2` in the configuration you shared, but it should be the same as the left one.

What I think is happening is that the configuration with `merge_mapping` should be changed to `mapping` and include the hold and release, because the `right_*` are also included. So:

```yaml
switch_all_left:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    left_press: "on"
    left_press$2: "off"
    left_hold: hold_brightness_toggle
    left_hold_release: release

switch_all_right:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    right_press: "on"
    right_press$2: "off"
    right_hold: hold_brightness_toggle
    right_hold_release: release
```

I hope this clarifies your issues.

Regards,
Xavi M.

**Comment by JDFS404** [comment]
@xaviml you're the best! It's now working as intended - albeit with a double click instead of a single click. I think to get it with a single click (like a toggle), the configuration would be a lot more advanced but since it's only concerning one switch in the hallway, it's not a big issue.

I even incorporated a third and fourth click to get another light on or off, I used the `mapping` again for this. Really cool stuff :)

**Comment by xaviml** [comment]
Hi @JDFS404,

Glad you got it working :) If you want just the switch to toggle the light with the press, you could do it with 2 configuration. This is an example for the left actions:

```yaml
switch_all_left_on:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    left_press: "off"
    left_hold: hold_brightness_toggle
    left_hold_release: release
  constrain_input_boolean: group.all_light,on

switch_all_left_off:
  module: controllerx
  class: Philips929003017102LightController
  controller: zigbee2mqtt/schakelaar_gang/action
  integration: mqtt
  light: group.all_light
  mapping:
    left_press: "on"
    left_hold: hold_brightness_toggle
    left_hold_release: release
  constrain_input_boolean: group.all_light,off
```

So the first configuration would work only when the `group.all_light` is on, so when pressed, it would turn off the lights. And the second configuration would only work when the lights are off, so when pressed, it would turn the lights on. In the case of having 1 light on and the rest off, the `group.all_light` would be `on` by default in Home Assistant, so all the lights (well, just the single light it was on) would turn off when pressed. No light should be turned on in this case as you were experiencing.

Hope this suits you better since no double click is needed, just the single as you were seeking.

Regards,
Xavi M.
