### ISSUE TITLE
E1743: only toggle and auto ON/OFF when dimming. Possible?

### ISSUE THREAD

**Issue by bartplessers** [xaviml/controllerx#289]
# Question

Hi @xaviml 
I finally implemented your controllerx. And I'm mad that I didn't do this earlier... :-)

Anyway never too late, so thanx a lot for sharing this feature!

I'm now testing with a simple IKEA E1743 remote.
Following question
- is it possible to assign the same command "TOGGLE" to both ON/OFF actions? So click on the button toggles the light, no matter where you pushed the button
- is it possible to turn OFF the light if the brightness level is below i.e. 10
- is it possible to turn ON the light if the brightness level is above 10

Same for E1744
What I want to achieve for this one: just standard behaviour as a classic dimmer: turn fully to the left to turn off. Turning right for turning it on.

## Additional information

* Devices involved:
Model: IKEA 1744, E1743   as Controller 

* Integration: 
Current version: 1.18.1-1 (Changelog)
Zigbee2mqtt add-on.

* AppDaemon
```
Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.6.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.4.6
 Home Assistant Supervisor: 2021.04.2
```

* ControllerX version:
`__version__ = "v4.10.0"
`

* Home Assistant Core version: [ eg. v0.105.4 ]
`core-2021.4.6`

**Comment by xaviml** [comment]
Hi @bartplessers,

Glad to hear from you, the first user of the first version of ControllerX (when not even the name existed yet haha). Please find the answers below:

> is it possible to assign the same command "TOGGLE" to both ON/OFF actions? So click on the button that toggles the light, no matter where you pushed the button

Yes, you need to leverage the `mapping` or `merge_mapping` attributes, so: 

```yaml
example_app:
  module: controllerx
  class: E1743Controller
  controller: sensor.your_controller_action
  integration: z2m
  light: light.your_light
  merge_mapping:
    "on": toggle
    "off": toggle
```

This will override the "on" and "off" actions to just toggle the light. You can see the E1743 mapping [here](https://xaviml.github.io/controllerx/controllers/E1743), and the predefined actions (like toggle) in [here](https://xaviml.github.io/controllerx/advanced/predefined-actions).

> is it possible to turn OFF the light if the brightness level is below i.e. 10
   is it possible to turn ON the light if the brightness level is above 10

This is not possible to do from ControllerX, but you could easily add automation for that in HA. I see the usage of turning off the light when brightness is below 10, but not the other one. If the light is off (because you want it to turn on) then there is no brightness, so brightness cannot be above 10. Does this mean that you do not want to turn on the light when the brightness is below 10? Either way, ControllerX does not support this, and my recommendation, for now, would be to have an HA automation for this.

> Same for E1744
What I want to achieve for this one: just standard behavior as a classic dimmer: turn fully to the left to turn off. Turning right for turning it on.

For this behaviour, you could define the `min_brightness` to 0, so the light will be turned off once it reaches the minimum brightness. And then you could modify the `brightness_move_up` action:

```yaml
example_app:
  module: controllerx
  class: E1744LightController
  controller: your_controller_id
  integration: z2m
  light: light.your_light
  min_brightness: 0
  merge_mapping:
    brightness_move_up:
      - "on"
      - delay: 0.2
      - hold_brightness_up
```

This should do the trick.

Regards,
Xavi M.
