### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by gaussey** [xaviml/controllerx#294]
# Question

is it possible using mapping to control volume on my media player with a light dimmer (ICTCG1)?

## Additional information

* Devices involved:
  ICTCG1
  
My current entry follows that is giving the error : ValueError: ICTCG1Controller class needs the `light` attribute

```volume_app:
  module: controllerx
  class: ICTCG1Controller
  controller: ikeadimmer
  integration:
    name: z2m
    listen_to: mqtt
    media_player: media_player.room1_main
    merge_mapping: 
       brightness_step_up: 
         - service: media_player.volume_set
           data:
             entity_id: media_player.room1_main
             data_template:
             volume_level: ‘{{ states.media_player.room1_main.attributes.volume_level + 5 }}’
```

**Comment by xaviml** [comment]
Hi @gaussey,

Each controller has different classes (for `class` attribute) that you can use. For this controller the following classes are supported:
- ICTCG1Controller (A light controller)
- ICTCG1MediaPlayerController (A media player controller)

You can see this in the device page: https://xaviml.github.io/controllerx/controllers/ICTCG1

Configuration would look like:

```yaml
example_app:
  module: controllerx
  class: ICTCG1Controller
  controller: ikeadimmer
  integration:
    name: z2m
    listen_to: mqtt
  media_player: media_player.room1_main
```

Also, `brightness_step_up` is not a mapping from this controller unless something changed. You can see the z2m mapping for this controller in the device page I mentioned before.

Regards,
Xavi M.
