### ISSUE TITLE
Is ControllerX compatible with lightgroups defined in HomeAssistant

### ISSUE THREAD

**Issue by bartplessers** [xaviml/controllerx#295]
# Question

I have a lightgroup, defined as follows:

```
# -------------------------------------------
light:
  - platform: group
    name: group_n01_p02_balk
    entities:
      - light.my_n01_p02_light_l14_balk_links
      - light.my_n01_p02_light_l15_balk_midden
      - light.my_n01_p02_light_l16_balk_rechts


```

and an ControllerX app defined as:

```
# ---------------------------------------------------------------
# BUREAU - balk
# ---------------------------------------------------------------
my_n01_p02_switch_r17_balk:
  module: controllerx
  class: E1743Controller
  integration: z2m
  controller: sensor.my_n01_p02_switch_r17_balk_action
  light: light.group_n01_p02_balk
  merge_mapping:
    "on": toggle
    "off": toggle

```

The "toggle" works perfect, however the "brightness_move_up" and "brightness_move_down" do not dim the lightgroup.
It works perfect when I adress the light individually. 

Is ControllerX compatible with lightgroups defined in HomeAssistant?

kind regards,
B

**Comment by xaviml** [comment]
Hi @bartplessers,

This is a problem that light group has and is that it does not expise the `brightness` attribute properly. For this reason, ControllerX only supports Group intrgration, and not Light Group integration. Read more about it in [FAQ#4](https://xaviml.github.io/controllerx/faq).

**Comment by bartplessers** [comment]
oh, sorry for my ignorance.
(aka RTFM :-) )

grtz
B

**Comment by xaviml** [comment]
No worries, I came back to this recently, and the Light Group works fine if the brightness and/or color_temp are exposed. What I found out is that it worked in some cases and not others, so this is why I sticked to the Group integration for this solution.

**Comment by bartplessers** [comment]
Hi @xaviml ,

sorry to harass you again, but now I defined a group

```
# -------------------------------------------
  my_n01_p02_balk:
    name: lamp bureau balk
    icon: mdi:lightbulb-group
    entities:
    - light.my_n01_p02_light_l14_balk_links
    - light.my_n01_p02_light_l15_balk_midden
    - light.my_n01_p02_light_l16_balk_rechts

```
But how to use this group in ControllerX?
It's not a light, so how to adress is? I tried
```
# ---------------------------------------------------------------
# BUREAU - balk
# ---------------------------------------------------------------
my_n01_p02_switch_r17_balk:
  module: controllerx
  class: E1743Controller
  integration: z2m
  controller: sensor.my_n01_p02_switch_r17_balk_action
  group: group.my_n01_p02_balk
  merge_mapping:
    "on": toggle
    "off": toggle
```
but this doesn't work.

What I also don't understand: in the GUI, a lightgroup exposes brightness, a group does not.

Lightgroup:
![2021-05-01_23-22-02](https://user-images.githubusercontent.com/10470708/116795296-40b00c00-aad4-11eb-9150-407821e8a933.png)

Do I miss something?
grtz
B
