### ISSUE TITLE
ValueError when render template is present in the entity name

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#305]
# Bug report

## Description

The render template feature does not work properly for the entity fields (light, media_player, etc). This happens when render template is used when the get_state function is called.

## Additional information

* Devices involved:
  * Model: [ eg. IKEA 1744 ] as [ Light | Media Player | Controller ]
  * ...
* Integration: `z2m`
* ControllerX version: 4.11.0

## AppDaemon app configuration

```yaml
example_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.controller_action
  light: "{{ states('input_select.lights') }}"
  # This is recommendable if the lights you want to loop through have different supported actions
  update_supported_features: true
  merge_mapping:
    arrow_left_click:
      - service: input_select.select_previous
        data:
          entity_id: input_select.lights
    arrow_right_click:
      - service: input_select.select_next
        data:
          entity_id: input_select.lights```
```

## Logs

```
ValueError: `supported_features` could not be read from `{{ states('input_select.lights') }}`. Entity might not be available.
```
