### ISSUE TITLE
[BUG] ZHA and E1810 won't work

### ISSUE THREAD

**Issue by wes1993** [xaviml/controllerx#317]
# Bug report
I have configured everything like in the wiki but wn't work

## Description
Seems that controllerx can't see the pressing button

## Additional information

* Devices involved:
  * Model: IKEA E1810
  * ...
* Integration: zha
* AppDaemon version: v4.0.8
* ControllerX version: v4.12.0
* HACS version (if installed from there): 1.12.4
* Home Assistant Core version: Home Assistant 2021.6.3

## AppDaemon app configuration

```yaml
LuciCamera:
  module: controllerx
  class: E1810Controller
  controller: ec:1b:bd:ff:fe:85:ea:f9
  integration: zha
  light: group.camera
  actions:
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
    - arrow_right_click
    - arrow_left_click
```

## Logs

```text
if i press the button this is the ZHA log:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "ec:1b:bd:ff:fe:85:ea:f9",
        "unique_id": "ec:1b:bd:ff:fe:85:ea:f9:1:0x0005",
        "device_id": "9931e8e61459908fdcd52ce99995ecf0",
        "endpoint_id": 1,
        "cluster_id": 5,
        "command": "press",
        "args": [
            256,
            13,
            0
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-06-08T15:50:32.692989+00:00",
    "context": {
        "id": "b9b54d38b33c867d5f43eda912905a38",
        "parent_id": null,
        "user_id": null
    }
}

The appdaemon log

2021-06-08 17:50:13.642414 INFO AppDaemon: Initializing app LuciCamera using class E1810Controller from module controllerx
2021-06-08 17:50:13.739637 INFO LuciCamera: 🎮 ControllerX v4.12.0
2021-06-08 17:50:13.766630 INFO AppDaemon: App initialization complete

No log in HA

```

## Additional Context

Seems that can't see that i have pressed the button

**Comment by xaviml** [comment]
Hi @wes1993,

The problem is that the `actions` contain events from zigbee2mqtt, and you are using zha. You can see the different events for each integration in the device page: https://xaviml.github.io/controllerx/controllers/E1524_E1810

In this case, it should be fixed by placing the right events:

```yaml
LuciCamera:
  module: controllerx
  class: E1810Controller
  controller: ec:1b:bd:ff:fe:85:ea:f9
  integration: zha
  light: group.camera
  actions:
    - hold_3329_0 # Arrow left hold
    - hold_3328_0 # Arrow right hold
    - release # Arrow release
    - press_256_13_0 # Arrow right click
    - press_257_13_0 # Arrow left click
```

Also, take into account that this would only make the arrows work, the rest of the button won't do anything with this configuration. It is normal to do so when you have already an automation for those buttons with HA or another ControllerX config.

Regards,
Xavi M.
