### ISSUE TITLE
[QUESTION] Link binary sensor as toggle light switch to a smart bulb?

### ISSUE THREAD

**Issue by jaddel** [xaviml/controllerx#329]
Can this integration be used to link a simple binary sensor as toggle light switch to a smart bulb? 

I don't if you are familiar with esphome but in there one could also build a trigger that sent's events to HA. Can we use those events to build something like a custom controller?

**Comment by xaviml** [comment]
Hi @jaddel,

Yes, that is totally possible with the state integration. This is a basic example of what you could do. Imagine you have a sensor in the bathroom with a smart light. You could connect them with the following configuration:

```yaml
example_app:
  module: controllerx
  class: LightController
  integration: state
  controller: binary_sensor.bathroom_sensor_occupancy
  light: light.bathroom
  mapping:
    "on": "on"
    "off": "off"
```

When the sensor detects movement, then the light will turn on. And when it does not detect movement, it will turn off.

Regards,
Xavi M.

**Comment by jaddel** [comment]
thanks for your reply. 

If i got it right, your example would mirror the state of the binary sensor to the light right? 
Could I also achieve a toggle behavior?

**Comment by xaviml** [comment]
Hi @jaddel,

What exactly you are trying to achieve? To toggle a loght when "on" is triggered?

Then, you can change the:

"on": "on"

For:

"on": toggle

Regards,
Xavi M.

**Comment by jaddel** [comment]
I would like to link a wall switch (binary_sensor....) to my smart bulbs. 
Expected behaviour: Every time I flip the wall switch the linked light toggles. 

```
living_room_wall_switch_remote:
  module: controllerx
  class: LightController
  integration: state
  controller: binary_sensor.top_mutual_shellyi3_remote
  light: light.lg_hall
  mapping:
    "on": "toggle"
    "off": "toggle"
```

This config is not working so far, could you help me to adjust it correctly? 

thank you.
