### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#342]
# Bug report

## Description

Home Assistant has deprecated some of the supported features from light integration: https://github.com/home-assistant/core/blob/26cb588ee2d54088d5750d9492057d8a7fe30592/homeassistant/components/light/__init__.py#L42

For this reason the color light might not work.

## Additional Context

While this bug is being fixed, the workaround is to manually set a value for supported_features like:

```yaml
office_light:
  module: controllerx
  class: E1810Controller
  controller: livingroom_controller
  integration:
    name: z2m
    listen_to: mqtt
  light: light.livingroom
  supported_features: 191
```
