### ISSUE TITLE
Possible to use multiple clicks on "on" action?

### ISSUE THREAD

**Issue by JDFS404** [xaviml/controllerx#346]
# Question

I have an E1812 controller, I want to use multiple clicks with Z2MQTT. Mapping is "on", so quotation marks give me errors when trying to use multiple clicks.

## Additional information

* Devices involved:
  * Model: IKEA 1812  as  Light Controller
* Integration: `z2m`
* AppDaemon version: newest
* ControllerX version: newest
* Home Assistant Core version: newest

## AppDaemon app configuration

```
---
# ControllerX config for Luxaflex
# 
powerview_bedroom:
  module: controllerx
  class: E1812LightController
  controller: zigbee2mqtt/shortcut_bedroom/action
  integration: mqtt
  light: light.bedroom_lights
  mapping:
    "on":
      service: scene.turn_on
      data:
        entity_id: scene.sleep

    "on"$2:
      service: scene.turn_on
      data:
        entity_id: scene.privacy

    "on"$3:
      service: scene.turn_on
      data:
        entity_id: scene.work
```

## Logs

```
2021-08-16 12:14:32.210779 INFO AppDaemon: Found 23 total apps
2021-08-16 12:14:32.144793 INFO AppDaemon: /conf/apps/controllers/cover/powerview.yaml added or modified
2021-08-16 12:14:32.118003 WARNING AppDaemon: File '/conf/apps/controllers/cover/powerview.yaml' invalid structure - ignoring
2021-08-16 12:14:32.115476 WARNING AppDaemon: expected , but found '' while parsing a block mapping
2021-08-16 12:14:32.114969 WARNING AppDaemon:   in "", line 16, column 9:
        "on"$2:
```

**Comment by xaviml** [comment]
Hi there,

Right syntax is "on$2" and "on$3".

Regards,
Xavi M.

**Comment by JDFS404** [comment]
Thanks! Tried this:
```
  mapping:
    "on":
      service: scene.turn_on
      data:
        entity_id: scene.sleep

    "on$2":
      service: scene.turn_on
      data:
        entity_id: scene.privacy

    "on$3":
      service: scene.turn_on
      data:
        entity_id: scene.work
```

And added ```mode: restart```, now I need to play with ```multiple_click_delay``` because it's still not triggering correctly but at least it's triggering!
