### ISSUE TITLE
[QUESTION] Possible to toggle between two different mappings?

### ISSUE THREAD

**Issue by tchesket** [xaviml/controllerx#359]
# Question

I have a lutron aurora dimmer that I'm using to control some lights. Right now, it is only possible to turn the lights on/off and control brightness. My idea is, what I would like to do is define a double-press action to switch back and forth from the wheel controlling the brightness, to controlling color. So basically when double clicking the (only) button on the dimmer, it should change the light from white to color, and the wheel should function to change the color. Double-clicking it again should change it back to white and the wheel controlling brightness. Is this possible to do?

## Additional information

* Devices involved:
  * Model: `Z31BRL (Lutron Aurora)` as `Light`
* Integration: `deconz`
* AppDaemon version: `v0.7.0`
* ControllerX version: `v4.16.0`
* HACS version (if installed from there): `v1.15.2`
* Home Assistant Core version: `core-2021.9.6`

## AppDaemon app configuration

```yaml
lutron_dimmer_x:
  module: controllerx
  class: Z31BRLLightController
  controller: friends_of_hue_dimmer
  integration: deconz
  light: light.bedroom_lights
```

**Comment by xaviml** [comment]
Hi @tchesket,

Yes, this is possible, but not something you can do out of the box with ControllerX. First of all, you will need and input_select or input_boolean in HA. I will go with an input_select because it is more extensible. You can create it through UI or YAML:

```yaml
controller_state:
  lights:
    options:
      - brightness
      - color
```

Then, your ControllerX configuration will look like the following:

```yaml
lutron_dimmer_x_change_state:
  module: controllerx
  class: Z31BRLLightController
  controller: friends_of_hue_dimmer
  integration: deconz
  light: light.bedroom_lights
  merge_mapping:
    1002$2:
      service: input_select.select_next
      entity_id: input_select.controller_state

lutron_dimmer_x_brightness:
  module: controllerx
  class: Z31BRLLightController
  controller: friends_of_hue_dimmer
  integration: deconz
  light: light.bedroom_lights
  mapping:
    2002: click_brightness_up
    3002: click_brightness_down
  constrain_input_select: input_select.controller_state,brightness

lutron_dimmer_x_color:
  module: controllerx
  class: Z31BRLLightController
  controller: friends_of_hue_dimmer
  integration: deconz
  light: light.bedroom_lights
  mapping:
    2002: click_color_up
    3002: click_color_down
  constrain_input_select: input_select.controller_state,color
```

So, the first configuration will toggle your light and toggle the state of `input_select.controller_state`. The second one will change your brightness if `input_select.controller_state` is `brightness`, and the 3rd one the same but for color.

The `constrain_input_select` is a feature from AppDaemon, so you can also use [others](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#appdaemon-constraints).

Hope this helps you achieve what you want.

Regards,
Xavi M.
