### ISSUE TITLE
[QUESTION] Merge Mapping to toggle switch

### ISSUE THREAD

**Issue by FabioEight** [xaviml/controllerx#361]
# Question

Hello, I read the documentation on the website and on the wiki, but I don't know if I'm doing right to manage a switch entity by double clicking the middle button of the IKEA E1810. I'm using it to already manage a lightbulb.

## Additional information

* Devices involved:
* Model: IKEA E1810 as light? 
* Integration: z2m
* AppDaemon version: last version
* ControllerX version: last version
* HACS version: last version
* Home Assistant Core version: last version

## AppDaemon app configuration
```
MultipulsanteIkea:
  module: controllerx
  class: E1810Controller
  controller: sensor.multipulsante_ikea_action
  integration: z2m
  light: light.lampada_camera_da_letto
  smooth_power_on: true
  merge_mapping:
    toggle$2:
        service: switch.circadian_lighting_luce_camera_da_letto
        
```
## Additional Context

As far as I understood, toggle$2 should refer to the double click of the E1810, but it's not really clear on the doc how to manage a switch. Is it possible since the it's already used to control a light?
Thanks!

**Comment by xaviml** [comment]
Hi @FabioEight,

So what you want is to call the `switch.toggle` service for the entity `switch.circadian_lighting_luce_camera_da_letto`. So it would look like:

```yaml
MultipulsanteIkea:
  module: controllerx
  class: E1810Controller
  controller: sensor.multipulsante_ikea_action
  integration: z2m
  light: light.lampada_camera_da_letto
  smooth_power_on: true
  merge_mapping:
    toggle$2:
        service: switch.toggle
        entity_id: switch.circadian_lighting_luce_camera_da_letto
```

You can read more about action types (service, predefined actions, scene, delay) [here](https://xaviml.github.io/controllerx/advanced/action-types).

Regards,
Xavi M.
