### ISSUE TITLE
[BUG] State Integration fires light toggle if the trigger sensor does a wifi reconnect.

### ISSUE THREAD

**Issue by jaddel** [xaviml/controllerx#366]
# Bug report

I'm using an esphome wifi integrated binary sensor to toggle my smart bulbs on and off.

When ever a sensor loses wifi and reconnects to the ha api the automation toggles the light.

Im actually not sure if the is a bug but I don't know where else to start.

Is there something I can do that it only toggles on an actual state change?

## Additional information

* AppDaemon version: latest
* ControllerX version: latest
* HACS version (if installed from there): latest
* Home Assistant Core version: latest

## AppDaemon app configuration

```
living_room_wall_switch_remote:
  module: controllerx
  class: LightController
  integration: state
  controller: binary_sensor.mid_mutual_shellyi3_remote
  light: light.lg_living_room
  mapping:
    "on": "toggle"
    "off": "toggle"
```

**Comment by jaddel** [comment]
> I could add a flag to the main configuration (e.g. `listen_from_null`) to control if an action should be fired if the previous event was null or empty

![image](https://user-images.githubusercontent.com/46263124/137100282-86d49eee-b87b-4d57-b415-5b012b24fa1e.png)

I think this is a god solution and I would appreciate it to see this implemented. 

The screen shot doesn't look very helpful though, could I provide anything else? I really know where to search for it..?

**Comment by xaviml** [comment]
Hi @jaddel,

Thank you for sharing this screenshot. I better understand your problem now. Although this seems to be an error/issue from the sensor, I will implement a generic solution that will work for you. I will add a new attribute where the user will be able to define the previous state of the fired action. So it would look something like this in your case:

```yaml
living_room_wall_switch_remote:
  module: controllerx
  class: LightController
  integration: state
  controller: binary_sensor.mid_mutual_shellyi3_remote
  light: light.lg_living_room
  previous_state:
    "on": "off"
    "off": "on"
  mapping:
    "on": "toggle"
    "off": "toggle"
```

So the "on" action will only get fired if the previous state was "off", and vice versa for the "off" one.

I can not assure when this will be implemented, but I know it is not difficult to implement, so when I get some time I will add such functionality.

I will keep you updated.

Regards,
Xavi M.

**Comment by jaddel** [comment]
I simulated a wifi reconnect on the binary sensor with the following configuration but the light's still toggle as soon as the sensor gets back online.

```
office_wall_switch_1:
  module: controllerx
  class: LightController
  integration: state
  controller: binary_sensor.office_wall_switch_1
  light: >- 
    {% if is_state('light.lg_internal_office_ceilig', 'on') %}
    {{"light.lg_internal_office_all"}}
    {% else %}{{"light.lg_office_ambient"}}{% endif %}
  previous_state:
    "on": "off"
    "off": "on"
  mapping:
    "on": "toggle"
    "off": "toggle"

office_wall_switch_2:
  module: controllerx
  class: LightController
  integration: state 
  controller: binary_sensor.office_wall_switch_2
  light: light.office_ceiling
  previous_state:
    "on": "off"
    "off": "on"
  mapping:
    "on": "toggle"
    "off": "toggle"
    
office_wall_switch_3:
  module: controllerx
  class: LightController
  integration: state 
  controller: binary_sensor.office_wall_switch_3
  light: light.office_ceiling_nightlight
  previous_state:
    "on": "off"
    "off": "on"
  mapping:
    "on": "toggle"
    "off": "toggle"
```
