### ISSUE TITLE
How do I map IKEA 1766 (cover control) inversed?

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#371]
# Question
Hi Xavi
Darned, I found something I know nothing about in your great product.
I'm building a button for the danish fuga, and apparently the engravings on these standard buttons are reverse of IKEA, so I need to have the 'up' (deconz 1002/1003) mappen to down/down relaease, and vice versa.
I have the actions 1002/1003 in seperate apps from 2002/2003 as shown in the config.

## Additional information

* Devices involved:
  * Model: IKEA 1766  Cover Controller
  * ...
* Integration: deconz
* AppDaemon version:  HA Addon 0.7.0
* ControllerX version: v4.16.0
* HACS version (if installed from there): 1.15.2
* Home Assistant Core version: 2021.10.3

## AppDaemon app configuration

This is the current version of the config, where the buttons are doing the 'wrong' thing :-)
```yaml
livingroom-big-cover-up:
  module: controllerx
  class: E1766CoverController
  controller: livingroom_cover_control
  integration: deconz
  cover: cover.livingroom_blind_big
  actions:
    - 1002
    - 1003

livingroom-big-cover-down:
  module: controllerx
  class: E1766CoverController
  controller: livingroom_cover_control
  integration: deconz
  cover: cover.livingroom_blind_big
  constrain_input_boolean: binary_sensor.livingroom_big_window_sensor,off
  actions:
    - 2002
    - 2003
```

## Logs

```text
(optional) Add relevant AppDaemon / Home Assistant logs which could help answering the question.
```

**Comment by xaviml** [comment]
Hi @fribse,

If what you want is to invert the open and close actions, you just need one configuration:

```yaml
office-cover:
  module: controllerx
  class: E1766CoverController
  controller: office_cover_control
  integration: deconz
  cover: cover.office_window_blind
  merge_mapping:
    1002: toggle_close
    2002: toggle_open
```

Not sure why you have 2 configurations, and one of them with `constrain_input_boolean: binary_sensor.livingroom_big_window_sensor,off`. Is there any specific reason for this that I missed? The above configuration inverts only `1002` and `2002` because `1003` and `2003` are both mapped with the `stop` action, so there is no need to invert them.

Regards,
Xavi M.
