### ISSUE TITLE
[QUESTION] Control only color temp. and double toggle via ControllerX, leave on/off to z2m to binding

### ISSUE THREAD

**Issue by FabioEight** [xaviml/controllerx#382]
# Question

Hello there, I'm looking for manage only light temperature and the double toggle on my E1810 via ControllerX.
The target is to be able to use the E1810 for controlling the lamp (on/off toggle and light intensity) via Zigbee2Mqtt binding, in this way I'm able to use the controller also if the hub is down.
In order to do so, I have to use "merge" and reconfigure toggle$2 and left/right buttons? 
Thanks!

## Additional information

* Devices involved:
  * Model: E1810  as Controller
  * ...
* Integration: Choose from `z2m`
* AppDaemon version: last
* ControllerX version: last
* HACS version (if installed from there): last
* Home Assistant Core version: last

## AppDaemon app configuration
The current config allows me to control both power/intensity/light temp and enable/disable circadian lighting service via double click.

```yaml
MultipulsanteIkea:
  module: controllerx
  class: E1810Controller
  controller: sensor.multipulsante_ikea_action
  integration: z2m
  light: light.lampada_camera_da_letto
  smooth_power_on: true
  merge_mapping:
    toggle$2:
        service: switch.toggle
        entity_id: switch.circadian_lighting_luce_camera_da_letto
```

**Comment by FabioEight** [comment]
Is it possible to overwrite a toggle to assign a button to a "none" action?

**Comment by xaviml** [comment]
Hi @FabioEight,

There are many ways you can achieve what you want. However, me recommendation would be to use `excluded_actions` attribute. This expects a list of actions to be excluded, so for example, you could do:

```yaml
MultipulsanteIkea:
  module: controllerx
  class: E1810Controller
  controller: sensor.multipulsante_ikea_action
  integration: z2m
  light: light.lampada_camera_da_letto
  smooth_power_on: true
  excluded_actions:
    - toggle
  merge_mapping:
    toggle$2:
        service: switch.toggle
        entity_id: switch.circadian_lighting_luce_camera_da_letto
```

Also, you can use `mapping` instead of `merge_mapping` to hard overwrite the whole default maaping.

You can read more about this configuration [here](https://xaviml.github.io/controllerx/start/configuration).

Regards,
Xavi M.
