### ISSUE TITLE
Control brightness for two lamps seperatelly

### ISSUE THREAD

**Issue by Papi77** [xaviml/controllerx#393]
# Question

Is it possible to fully control two light in a light group individually (both temperature & brightness)?
Example:
- toggle: switch on/off the entire light group
- toggle$2: switch on/off lamp1
- toggle$2: switch on/off lamp1
When a single lamp is switched on - all buttons (left/right & brightness up/down) work for that lamp only

Current behavior:
- toggle switches work as expected
- color change (arrows left/right) work as expected
- brightness DO NOT work as expected
-> Issue: When pressing brightness up/down - always ALL lamps are affected.

## Additional information

* Devices involved:
* Model: IKEA 1810 as Light
* Integration: z2m
* AppDaemon version: [ eg. v4.0.1 ]
* ControllerX version: v4.16
* HACS version v1.18
* Home Assistant Core version: 2021.11.5

## AppDaemon app configuration

livingroom_light_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.ikea_action
  integration: z2m 
  light: light.livingroom
  merge_mapping:
    toggle$2:
      service: light.toggle
      data:
        entity_id: light.sofa_light
    toggle$3:
      service: light.toggle
      data:
        entity_id: light.table_light

## Logs
N/A

## Additional Context

I have tried to use input_selectors and additional app configurations for individual lamps but was unsuccessful :(

**Comment by xaviml** [comment]
Hi @Papi77,

That is a tricky one, but I can see the use case. The only way I can think of achieving this would be to leverage callback constraints from AppDaemon. So have 1 config that does the toggling and then the other configs that change the brightness is the light is on. Here is an example for 2 lights:

```yaml
toggle_light_app:
  module: controllerx
  class: LightController
  controller: sensor.ikea_action
  integration: z2m
  mapping:
    toggle:
      service: light.toggle
      data:
        entity_id: light.light_1
    toggle$2:
      service: light.toggle
      data:
        entity_id: light.light_2

light_1_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.ikea_action
  integration: z2m
  light: light.light_1
  excluded_actions: [toggle]
  constrain_input_select: light.light_1,on

light_2_app:
  module: controllerx
  class: E1810Controller
  controller: sensor.ikea_action
  integration: z2m
  light: light.light_2
  excluded_actions: [toggle]
  constrain_input_select: light.light_2,on
```

The first app controls the toggle, and the other 2 will control everything else if the light is on.

Regards,
Xavi M.
