### ISSUE TITLE
E1810 stop working

### ISSUE THREAD

**Issue by mrslvd** [xaviml/controllerx#395]
# Question

IKEA E1810 stops working. I've noticed that in AppDeamon log warning is issued related with E1810 which is not working anymore 

## Additional information

* Devices involved:
  * Model: IKEA E1810 Controller
  * ...
* Integration: Choose from `z2m`
* AppDaemon version: [ 0.7.1 ]
* ControllerX version: [ v4.16.0 ]
* HACS version (if installed from there): [ 1.18.0 ]
* Home Assistant Core version: [ core-2021.12.5 ]

## AppDaemon app configuration

```yaml
livingroom_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.living_room_remote_5btn_zb_action
  integration: z2m
  //light: light.living_room_night_lamp1_zb_light
  light: light.living_room_night_lamp1_zb
```

## Logs

```AppDeamon
2021-12-27 12:38:24.450164 INFO livingroom_controller: 🎮 ControllerX v4.16.0
2021-12-27 12:38:24.544631 WARNING livingroom_controller: livingroom_controller: Entity sensor.living_room_remote_5btn_zb_action not found in namespace default
```
```z2m
Zigbee2MQTT:info  2021-12-27 12:39:29: MQTT publish: topic 'zigbee2mqtt/living_room_remote_5btn_zb/action', payload 'toggle'
```

## Additional Context

Add any other context or screenshots about the question here.
