### ISSUE TITLE
[FEATURE REQUEST] Configure min (and max?) value

### ISSUE THREAD

**Issue by jcassee** [xaviml/controllerx#41]
# Feature Request

### Is your feature request related to a problem?

I have a light that I do not want to go under a specific value. I use a Lovelace slider that gives me a range of 5-255 in steps of 5, but while ControllerX does support setting the step size, the minimal value is always 1.

### Describe the solution / feature you'd like

An extra configuration parameter `min_value` (?), and for symmetry maybe also `max_value`, that is used in the constructor of `MinMaxStepper`.

### Describe alternatives you've considered

I have considered using the [new `brightness_increase/_descrease` actions](https://www.home-assistant.io/blog/2020/02/26/release-106/#stepping-up-and-down-the-brightness-of-lights), but I would rather keep using ControllerX.

### Additional context

_none_

**Comment by xaviml** [comment]
Hi @jcassee ,

Since this will just extend the functionality, I will add this to ControllerX. I will also do it for color temperature.

**Comment by xaviml** [comment]
Hi @jcassee 

This has been added to v2.3.0b10. You can now download from HACS (clicking on "Show beta"). Four new attributes have been added to light controllers: `min_brightness`, `max_brightness`, `min_color_temp` and `max_color_temp`. So now your configuration would look like:
```yaml
example_app:
  module: controllerx
  class: <the device class>
  controller: <your controller_id>
  integration: <z2m | deconz | zha>
  light: <your light entity>
  min_brightness: 5
```

You can check the new attributes in [here](https://xaviml.github.io/controllerx/start/type-configuration). I will close this issue once you try it and give me the feedback back :)
