### ISSUE TITLE
[FEATURE REQUEST] Please add homematic integration

### ISSUE THREAD

**Issue by hvorragend** [xaviml/controllerx#421]
# Feature Request

### Is your feature request related to a problem?

I think that ControllerX can be used with other integrations, too.
For example: pyhomematic, zwave or similar.
I am using a lot of Homematic-remotes.
Link. https://www.home-assistant.io/integrations/homematic/

### Describe the solution / feature you'd like

With the homematic integration we can add several additional controllers.
And I can help you configuring the mappings.

### Describe alternatives you've considered

Alternatively I must use HA blueprints.

### Additional context

Example: Homematic Tasterschnittstelle (German)
Integration: pyhomematic
Controller: HM-PBI-4-FM
Each device has a name (e.g. "Kitchen Switch") and a serial number.

You can find more details about serial number, channels here:
https://www.home-assistant.io/integrations/homematic/#devices-with-buttons

**Mapping:**
Channel 1 - PRESS_SHORT

`2022-01-26 17:38:32 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=<serialnumber>:1, interface_id=homeassistant-rf, key=PRESS_SHORT, value=True`

Channel 2 - PRESS_SHORT

`2022-01-26 17:38:32 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=<serialnumber>:2, interface_id=homeassistant-rf, key=PRESS_SHORT, value=True`

Example YAML:
```
automation:
   trigger:
     platform: event
     event_type: homematic.keypress
     event_data:
       name: "Kitchen Switch"
       channel: 1
       param: PRESS_SHORT
   action:
     service: switch.turn_on
     target:
       entity_id: switch.Kitchen_Ambience
```

**Comment by xaviml** [comment]
Hi @hvorragend ,

That is a great idea and thank you for opening this feature request. Add an integration is quite straight forward and transparent of how the rest of ControllerX features work. I can create a homematic integration as long as you willing to test it since I do not have the right hardware for this. What I suggest is to merge the name of the action and the channel like: <action>_<channel>.

Do you have this controller? HM-PBI-4-FM which actions does it fire?

Regards,
Xavi M.

**Comment by hvorragend** [comment]
I am using different Homematic controller and I can help you as good as I can. 
I am not a python coder, but I am having some basic knowledge in several other languages. I should be able to create pull requests to extend more controllers. 

All Homematic-Controllers are having similar events. If you have a 4-gang-switch than you have four channels. 

And instead of 1001/1002/1003 we have the following parameters:
PRESS_SHORT
PRESS_CONT
PRESS_LONG
PRESS_LONG_RELEASE

The HM-PBI-4-FM just uses PRESS_SHORT, PRESS_CONT and PRESS_LONG. 

The controller HM-PB-6-WM55 sends PRESS_LONG_RELEASE additionally. 

This is an example event:
`
{
    "event_type": "homematic.keypress",
    "data": {
        "name": "Taster Esszimmer",
        "param": "PRESS_SHORT",
        "channel": 2
    },
    "origin": "LOCAL",
    "time_fired": "2022-01-30T14:55:04.049303+00:00",
    "context": {
        "id": "90e7eccccaa1680036f1f80021bd306c",
        "parent_id": null,
        "user_id": null
    }
}`

If you create the code templates, I will add the other stuff. 

BUT:
The more I think about it, I wonder if it couldn't be made more generic. Is it perhaps even possible to create a generic event integration for all other systems? Or doesn't this make any sense?

**Comment by xaviml** [comment]
Hi @hvorragend,

Thank you for the details. However, I would need to understand when the actions are fired. This is what I understand, but correct me or add more information if needed:

- `PRESS_SHORT`: Fired when the button is pressed
- `PRESS_CONT`: ???
- `PRESS_LONG`: Fired when the button is held
- `PRESS_LONG_RELEASE`: Fired when the button is released after `PRESS_LONG` was fired.

> The more I think about it, I wonder if it couldn't be made more generic. Is it perhaps even possible to create a generic event integration for all other systems? Or doesn't this make any sense?

I understand your request and share your thought, but for the ease of configuration, it makes more sense to have a specific integration for Homematic anyway. For example, the Zigbee2MQTT listens to state changes from HA, but so it does the generic State integration. On the other hand, we also have ZHA and Lutron listening to events, the same as we would do for Homematic. However, I still agree it would be nice to have a generic integration for event listening.

Regards,
Xavi M.

**Comment by hvorragend** [comment]
PRESS_CONT means "continue" and we can compare it with the hold action in other integrations.

**Comment by xaviml** [comment]
What would be the difference between `PRESS_CONT` and `PRESS_LONG`?

**Comment by xaviml** [comment]
I have another question regarding `HM-PBI-4-FM` and `HM-PB-6-WM55`, how many channels have each? Are the channels hardcoded in the devices? i.e. Can you change the channels of each device?

Are the channels a way to distinguish which button was pressed?

**Comment by xaviml** [comment]
I created PR [ #422 ] with the necessary changes for the Homematic integration and the addition of `HMPBI4FMLightController` and `HMPB6WM55LightController` devices. However, I still would need to understand the questions from above to finish the mapping found in [this file](https://github.com/xaviml/controllerx/blob/be9e9759d7706c6f62eb0cd50a3c97ea24f8fa90/apps/controllerx/cx_devices/homematic.py).

To my understanding, these controllers are for users to customize, so they do not come with a defined mapping, so I will be giving a generic default mapping, but I will recommend the use of `mapping` when using this controller.

**Comment by hvorragend** [comment]
> What would be the difference between `PRESS_CONT` and `PRESS_LONG`?

I'll have to take a closer look at that. So far I have used SHORT and LONG. I will check the device events and report back.

By the way: I used FHEM for several years until a few months ago. There we have a file where I can look up the configuration and events.
Example: https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/HMCCUConf.pm#L991

**Comment by hvorragend** [comment]
> I have another question regarding `HM-PBI-4-FM` and `HM-PB-6-WM55`, how many channels have each? Are the channels hardcoded in the devices? i.e. Can you change the channels of each device?
> 
> Are the channels a way to distinguish which button was pressed?

Yes, as you can see in the perl file above, the channels are hardcoded. I cannot change the channels.

**Comment by hvorragend** [comment]
I'm trying the following simple configuration and I'm getting warnings in the log.

```
whz_essz_tischleuchte:
  module: controllerx
  class: HMPBI4FMLightController
  controller: "Taster Esszimmer"
  integration: homematic
  light: light.tischleuchte_wohnzimmer
  mapping:
    PRESS_SHORT_1: toggle
```

Warning:

```2022-01-31 20:48:52.308036 WARNING whz_essz_tischleuchte: ------------------------------------------------------------
2022-01-31 20:48:52.308565 WARNING whz_essz_tischleuchte: Unexpected error in worker for App whz_essz_tischleuchte:
2022-01-31 20:48:52.308877 WARNING whz_essz_tischleuchte: Worker Ags: {}
2022-01-31 20:48:52.309136 WARNING whz_essz_tischleuchte: ------------------------------------------------------------
2022-01-31 20:48:52.310023 WARNING whz_essz_tischleuchte: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 108, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 147, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 63, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py", line 18, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 184, in init
    await self.integration.listen_changes(controller_id)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/homematic.py", line 15, in listen_changes
    await Hass.listen_event(
  File "/usr/lib/python3.9/site-packages/appdaemon/adapi.py", line 1899, in listen_event
    return await self.AD.events.add_event_callback(_name, namespace, callback, event, **kwargs)
TypeError: add_event_callback() got multiple values for argument 'name'
2022-01-31 20:48:52.310453 WARNING whz_essz_tischleuchte: ------------------------------------------------------------
```

**Comment by hvorragend** [comment]
Are there any news?  Can I help you?

**Comment by xaviml** [comment]
Hi @hvorragend,

Sorry for the delay on this. The problem for that was that the "name" cannot be used to filter in the listen_event method as done for zha or deconz since "name" is a reserved keyword for that method. I changed the filtering to be done in the event callback.

I have tried it first and I was able to reproduce same error, after the fix I was able to turn on the light with my Home Assistant instance by faking an event in the Developer Tools page.

Let me know if this works for you and if there is anything missing for the whole homematic integration and the device you have.

Regards,
Xavi M.

**Comment by hvorragend** [comment]
Absolutely awesome. Thanks very much. It runs smoothly.

Could you please add HM-PB-2-WM55-2, too?

- PRESS_SHORT
- PRESS_LONG
- PRESS_CONT
- PRESS_LONG_RELEASE

Thank you very much.

**Comment by xaviml** [comment]
Hi @hvorragend,

I am assuming that the channel of the (only) button for HM-PB-2-WM55-2 is 1, correct?

Regards,
Xavi M.

**Comment by hvorragend** [comment]
Nope. Two channels. 😄

**Comment by xaviml** [comment]
@hvorragend , I just pushed some changes:
- Added missing mapping to existing Homematic controllers
- Add HM-PB-2-WM55-2 support

I will be merging PR tomorrow and creating a beta release.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @hvorragend ,

I just released [ControllerX v4.19.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.19.0b0) with the homematic integration added. If no problems are raised with it, I will be releasing the non-beta version.

You can allow beta versions in HACS to download it from there.

Regards,
Xavi M.

**Comment by hvorragend** [comment]
I am having fun with ControllerX now 😄
Could you please add HM-Sen-MDIR-WM55, too?
Or should I create a PR?

We must use channels 1 (down) and 2 (up) here. 
Channel 0 is reserved for the embedded motion sensor. 
It is a momentary switch with two buttons. 
Only PRESS_SHORT and PRESS_LONG event. 
No CONT and no LONG_RELEASE.

**Comment by xaviml** [comment]
Hi @hvorragend,

I have added HM-Sen-MDIR-WM55 here: https://github.com/xaviml/controllerx/commit/40ee3dd94e9f0c01b07cb8808a3b6b4698b1b335

Once you get back to me on the PR #461, I will merge it all together and release a new beta version for you to test.

Regards,
Xavi M.

**Comment by hvorragend** [comment]
Damn, I am really sorry. There are differences between the events in FHEM and RaspberryMatic. 
But these are good news. 

Almost all switches have SHORT, LONG, CONT and LONG_RELEASE events. 
I went through my house and tested it in detail. 

But only the  HM-PBI-4-FM does not fire a LONG_RELEASE. I know that this is sad for the dimming action. 

So we have to extend the

**Comment by xaviml** [comment]
According to the code, we already set this up correctly. `HM-PBI-4-FM` does not have `LONG_RELEASE`: https://github.com/xaviml/controllerx/blob/6433a1fa3bc34ee7995fdbc946325b84dd45c15d/apps/controllerx/cx_devices/homematic.py#L19-L34

**Comment by hvorragend** [comment]
Yes, but we can extend the HMSenMDIRWM55LightController

**Comment by xaviml** [comment]
You are saying that HMSenMDIRWM55LightController also has CONT and LONG_RELEASE?

**Comment by xaviml** [comment]
So HMPBI4FMLightController is the only one with no `PRESS_LONG_RELEASE`, right? Does it have `PRESS_CONT`?

**Comment by hvorragend** [comment]
> You are saying that HMSenMDIRWM55LightController also has CONT and LONG_RELEASE?

Yes, that's what I mean here: https://github.com/xaviml/controllerx/issues/421#issuecomment-1100312790

I did not know this before.

**Comment by hvorragend** [comment]
> So HMPBI4FMLightController is the only one with no `PRESS_LONG_RELEASE`, right? 

Correct. 

> Does it have `PRESS_CONT`?

Yes.

**Comment by xaviml** [comment]
Review commit: https://github.com/xaviml/controllerx/commit/762223d871ad9bee9027bef31facd7652b63c18a

If it looks good, I will create beta release.

**Comment by xaviml** [comment]
The following version has been released with the latest changes [ControllerX v4.19.0b3](https://github.com/xaviml/controllerx/releases/tag/v4.19.0b3)

**Comment by hvorragend** [comment]
Hmm, I think there must be a small bug anywhere.

I am using the following controller-configuration:

```
esz_deckenleuchte:
  module: controllerx
  class: HMPBI4FMLightController
  controller: "Taster Esszimmer"
  integration: homematic
  light: light.deckenleuchte_wohnzimmer
  mapping:
    PRESS_SHORT_1:
      action: "off"
    PRESS_SHORT_2:
      action: "on"
      attributes:
        brightness: 254
        color_temp: 370
    PRESS_LONG_1:
      action: hold
      attribute: brightness
      direction: down
      mode: stop
      steps: 10
    PRESS_LONG_2:
      action: hold
      attribute: brightness
      direction: up
      mode: stop
      steps: 10
    PRESS_SHORT_2$2:
      service: scene.turn_on
      data:
        entity_id: scene.wohnzimmer_tv_modus
```

And somt older testing lines:

```
whz_tischleuchte_test1:
  module: controllerx
  class: HMPBI4FMLightController
  controller: "Taster Kinderzimmer"
  integration: homematic
  light: light.tischleuchte_wohnzimmer
  mapping:
    PRESS_SHORT_1: toggle
#    PRESS_CONT_1: toggle
#    PRESS_LONG_1: toggle


whz_tischleuchte_test2:
  module: controllerx
  class: HMPB2WM552LightController
  controller: "Wandtaster Stripes"
  integration: homematic
  light: light.tischleuchte_wohnzimmer
#  mapping:
#    PRESS_SHORT_1: "on"
#    PRESS_SHORT_2: "off"
#    PRESS_LONG_RELEASE: toggle
#    PRESS_CONT_1: toggle
```

If I press the button of the "Taster Esszimmer", other Controllers were executed:

```
2022-04-24 15:24:23.202847 INFO whz_tischleuchte_test2: 🎮 Button event triggered: `PRESS_SHORT_2`
2022-04-24 15:24:23.207187 INFO whz_tischleuchte_test2: 🏃 Running `Predefined (on)` now
2022-04-24 15:24:23.210673 INFO whz_tischleuchte_test2: 
🤖 Service: light.turn_on
  - entity_id: light.tischleuchte_wohnzimmer
2022-04-24 15:24:23.708099 INFO esz_deckenleuchte: 🎮 Button event triggered: `PRESS_SHORT_2`
2022-04-24 15:24:23.710072 INFO esz_deckenleuchte: 🏃 Running `Predefined (on)` now
2022-04-24 15:24:23.713338 INFO esz_deckenleuchte: 
🤖 Service: light.turn_on
  - entity_id: light.deckenleuchte_wohnzimmer
  - brightness: 254
  - color_temp: 370
```

Could it be that the events are not recognized properly?
