### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Phatant** [xaviml/controllerx#429]
# Question

Im struggling, i can see that the remote E2001 or known as [W2049 (IKEA)] is not supported but its still not working for me. 

my apps.yaml is as follows:

officeremote: 
  module: controllerx
  class: W2049LightController 
  controller: office_remote
  integration: z2m
  light: light.office

im also using Z2Mqtt in a docker on unraid. 

* Devices involved:
  * Model: W2049 (IKEA)
  * ...
* Integration: z2m 
* AppDaemon version: 4.0.8.1
* ControllerX version: 4.18.2
* HACS version (if installed from there): 1.22.0
* Home Assistant Core version: 2022.2.6

## AppDaemon app configuration

```yaml
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

## Logs

```text
(optional) Add relevant AppDaemon / Home Assistant logs which could help answering the question.
```

## Additional Context

Add any other context or screenshots about the question here.
