### ISSUE TITLE
[QUESTION] Dim down and stop at lowest brightness

### ISSUE THREAD

**Issue by clausw45** [xaviml/controllerx#436]
Using the E1743 controller to control a single light with default controllerX config. Is it possible to hold the off button to dim down and it automatically stops at the lowest brightness without turning the light off?

My config:

kaya_controller:
  module: controllerx
  class: E1743Controller
  controller: sensor.ikea_on_off_dimmer_kayas_vaerelse_action
  integration: z2m
  light: light.kayas_vaerelse_lamper

* Devices involved:
  * Model: IKEA 1744 as Light
* Integration: z2m
* AppDaemon version: latest
* ControllerX version: latest
* HACS version (if installed from there): latest
* Home Assistant Core version: latest

**Comment by xaviml** [comment]
Hi @clausw45,

> Is it possible to hold the off button to dim down and it automatically stops at the lowest brightness without turning the light off?

Yes, that is possible. In fact, it is what ControllerX does by default. It does not turn off the light when reaching the lowest brightness. It could be that you light integration turns off the light when it reaches brightness 1. You can change the mininum allowed brightness with `min_brightness`:

```yaml
kaya_controller:
  module: controllerx
  class: E1743Controller
  controller: sensor.ikea_on_off_dimmer_kayas_vaerelse_action
  integration: z2m
  light: light.kayas_vaerelse_lamper
  min_brightness: 2 # You can change this to any brightness (1-255). By default is 1.
```

More information on the light controller parameters [here](https://xaviml.github.io/controllerx/start/type-configuration#light-controller).

Regards,
Xavi M.
