### ISSUE TITLE
Loop between values

### ISSUE THREAD

**Issue by bartplessers** [xaviml/controllerx#449]
Hi

Originally, using the IKEA 5 button remote, and pressing right arrow, the colortemp of my light gets cooler, but at the end, colortemps starts getting warmer again. It’s a “loop” between coldest and warmest temperatures.

With ControllerX, the colortemp doesn’t change anymore at its coldest point. Then you have to press the left arrow to set light to warmer temp.

Is it possible to let the ControllerX behave the same as an original IKEA automation?

**Comment by bartplessers** [comment]
Hi @xaviml,
Have you got any time to take a look at this?

**Comment by xaviml** [comment]
Hi @bartplessers,

I am sorry to come late on this. This is totally possible with [Hold/Click modes](https://xaviml.github.io/controllerx/advanced/hold-click-modes). This is an example of my E1810 controller with that setting for my livingroom lamp:

```yaml
livingroom:
  module: controllerx
  class: E1810Controller
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.livingroom_lamp
  merge_mapping:
    arrow_right_hold:
      action: hold
      attribute: color_temp
      direction: up
      mode: loop
    arrow_left_hold:
      action: hold
      attribute: color_temp
      direction: down
      mode: loop
```

This overrides the `arrow_right_hold` and `arrow_left_hold` to loop when reaching the end. `mode` can be changed to `bounce` as well. You can read more about it [here](https://xaviml.github.io/controllerx/advanced/hold-click-modes), where you can read more about other options that might be more convenient or not.

Regards,
Xavi M.
