### ISSUE TITLE
[FEATURE REQUEST] Allow dimming while pressing the hold button (without release-event)

### ISSUE THREAD

**Issue by hvorragend** [xaviml/controllerx#471]
# Feature Request

### Is your feature request related to a problem?

Related with https://github.com/xaviml/controllerx/issues/421#issuecomment-1108125611

### Describe the solution / feature you'd like

It is currently dimmed by recognizing a long button. It is dimmed until a hold-release event occurs.
But if there are devices that continuously send a HOLD event, you could use this multiple event for dimming.

Would it be possible?

### Describe alternatives you've considered

No dimming possible without a long-hold-release event.

**Comment by xaviml** [comment]
Hi @hvorragend ,

Thank you for opening this ticket. If the controller keeps firing an event when the button is held, the `click` action can be used. So for example, if the action `PRESS_CONT` is being fired continously while a button is held, the following could be done:

```yaml
example_app:
  module: controllerx
  class: YourClass
  controller: your_controller
  integration: your_integration
  mapping:
    PRESS_CONT: click_brightness_up
```

Every time `PRESS_CONT` is released, it will run the `click` action which will make the brightness go up.

However, the hold functionality will not be available this way, and adding it will mean changing something at the core of the project, and it is not an easy task, but I will leave the ticket open to tackle it when I have the time to think and implement such a feature.

Regards,
Xavi M.

**Comment by hvorragend** [comment]
Thank you very much. 
I've tried `click_brightness_up` and `click_brightness_down` now. 

I don't have a continuous/smooth dimming during holding the button. I see that `PRESS_CONT` is send almost each second. But ControllerX just changes the brightness once. I have to click again and the lights are going darker again. 

I don't have other hold/release-mappings in this test-environment activated.

**Comment by hvorragend** [comment]
Please don't waste too much time for me. 
I also have the possibility to use a HA blueprint for my Homematic stuff. 

And all other Homematic-controller are working fine. 

AFAIK there is just one Homematic-controller without a long-release-event.

**Comment by xaviml** [comment]
Hi @hvorragend ,

You need to take into account that ControllerX, by default, will discard repeated events within certain period of time. This is defined with `action_delta` (300ms by default). You can read about this parameter [here](https://xaviml.github.io/controllerx/start/configuration/?h=action_delta#parameters).

I have tried the following with my setup with the help of Developer Tools and I experience the same as you, the brightness did not go up if I kept sending quick events:

```yaml
example_app:
  module: controllerx
  class: LightController
  controller: my_controller
  integration: homematic
  light: light.livingroom_lamp
  mapping:
    PRESS_CONT_1: click_brightness_up
```

However, when I added the `action_delta` attribute to 0, I was able to change the brightness quick enough:

```yaml
example_app2:
  module: controllerx
  class: LightController
  controller: my_controller
  integration: homematic
  light: light.livingroom_lamp
  action_delta:
    PRESS_CONT_1: 0
  mapping:
    PRESS_CONT_1: click_brightness_up
```

Note that you can just set `action_delta: 0` as well, but it will affect all events. If you want to specify the specific events (PRESS_CONT), you can use that syntax.

Regards,
Xavi M.
