### ISSUE TITLE
Adding switch class to TS044

### ISSUE THREAD

**Issue by kenchy** [xaviml/controllerx#476]
I wanted to use my TS044 to toggle some groups of mainly switches, so I added the following block to tuya.py

class TS0044SwitchController(SwitchController):
    # Different states reported from the controller:

    def get_z2m_actions_mapping(self) -> DefaultActionsMapping:
        return {
            "1_single": Switch.TOGGLE,
            "1_double": Switch.ON,
            "1_hold": Switch.OFF,
            "2_single": Switch.TOGGLE,
            "2_double": Switch.ON,
            "2_hold": Switch.OFF,
            "3_single": Switch.TOGGLE,
            "3_double": Switch.ON,
            "3_hold": Switch.OFF,
            "4_single": Switch.TOGGLE,
            "4_double": Switch.ON,
            "4_hold": Switch.OFF,
        }

I'm remapping the actions in apps.yaml. Is there a simpler way of doing this, I don't think I can use the standard SwitchController because of the non-standard actions, or would the mapping take care of that?

**Comment by xaviml** [comment]
Hi @kenchy,

We could implement a Switch Controller for this device, but you can also define your mapping with `mapping` on `apps.yaml`:

```yaml
example_app:
  module: controllerx
  class: SwitchController
  integration: z2m
  controller: sensor.your_sensor_action
  switch: switch.your_switch
  mapping:
    1_single: "on"
    2_single: "off"
    3_single: toggle
```

_This is just an example._

You can find predefined action of Switch Controller [here](https://xaviml.github.io/controllerx/advanced/predefined-actions#switch).

Hopefully this works for you.

Regards,
Xavi M.

**Comment by kenchy** [comment]
You are totally right and thank you. The following configuration worked for me:

emma_controller:
  module: controllerx
  class: SwitchController
  controller: sensor.emma_control_action
  switch: group.cupboard
  integration: z2m
  mapping:
    1_single:
      service: homeassistant.toggle
      data:
        entity_id: group.cupboard
    2_single:
      service: homeassistant.toggle
      data:
        entity_id: group.meecrowwaavay
    3_single:
      service: homeassistant.toggle
      data:
        entity_id: group.entertainment
    4_single:
      service: homeassistant.toggle
      data:
        entity_id: group.frontroomprint

No additional class required. Thanks for this module and making it so flexible. I would have given up on HA without it I think as replicating the basic light switch functionality would have required so much configuration!

**Comment by xaviml** [comment]
Hi @kenchy,

Glad you got it working, you can simplify the configuration by removing the `data` part:

```yaml
emma_controller:
  module: controllerx
  class: SwitchController
  controller: sensor.emma_control_action
  switch: group.cupboard
  integration: z2m
  mapping:
    1_single:
      service: homeassistant.toggle
      entity_id: group.cupboard
    2_single:
      service: homeassistant.toggle
      entity_id: group.meecrowwaavay
    3_single:
      service: homeassistant.toggle
      entity_id: group.entertainment
    4_single:
      service: homeassistant.toggle
      entity_id: group.frontroomprint
```

I will close the ticket for now.

Regards,
Xavi M.
