### ISSUE TITLE
[QUESTION] Sonos Favorites and e1744

### ISSUE THREAD

**Issue by immunity-anomaly** [xaviml/controllerx#487]
# Question

I use an IKEA e1744 as a sonos remote. Thanks to Controllerx I used to be able to adjust the volume, skip tracks and start/stop the music. I mapped the triple-click to "next_source" which used to allow me to cycle through my sonos favorites. This does not work any more in HA, but now there is a sonos_favorites sensor. Can you help me get it to cycle through my sonos favorites again? Unfortunately for some reason right now I cannot even get it to work with the merge_mapping command any more. I would be really happy if you could help me.

## Additional information

- Devices involved:
  - Model: IKEA 1744 ] as Media Player
  - HA 2022.5.5
- Integration: ZHA
- ControllerX version: 4.19.0
- HACS version 1.24.5
- Home Assistant Core 2022.5.4
- Home Assistant Supervisor 2022.05.2
- Sonos favorites sensor documentation: https://www.home-assistant.io/integrations/sonos
- 

## AppDaemon app configuration

It works like this:

```yaml
volume_symfonisk:
  module: controllerx
  class: E1744MediaPlayerController
  controller: 68:0a:e2:ff:fe:3e:02:2b
  integration: zha
  media_player: group.sonos_all 
  delay: 350
  volume_steps: 30
  merge_mapping:

```

but stops working if I add the "step_..."

```yaml
volume_symfonisk:
  module: controllerx
  class: E1744MediaPlayerController
  controller: 68:0a:e2:ff:fe:3e:02:2b
  integration: zha
  media_player: group.sonos_all
  delay: 350
  volume_steps: 30
  merge_mapping:
    step_0_1_0_0_0: media_player.play_pause 
     
```

Ideally, I want it to look something like this:

```yaml
volume_symfonisk:
  module: controllerx
  class: E1744MediaPlayerController
  controller: 68:0a:e2:ff:fe:3e:02:2b
  integration: zha
  media_player: group.sonos_all
  delay: 350
  volume_steps: 30
  merge_mapping:
    step_0_1_0_0_0:
      service: media_player.select_source #not sure if select_source is possible
      data: # I tried to make it look like this: https://community.home-assistant.io/t/using-sonos-favourites-sensor/420380/6
        source: {% for media_id, name in state_attr("sensor.sonos_favorites", "items").items() %}
                      {{ name, media_id }}
                      {% endfor %}

```

## Logs

```text
HA Log/Error I get when adding "step_0_1_0_0_0":
2022-05-16 15:28:53 DEBUG (MainThread) [zigpy.zcl] [0xB4F1:1:0x0006] Received ZCL frame: b'\x11\x74\x02'
2022-05-16 15:28:53 DEBUG (MainThread) [zigpy.zcl] [0xB4F1:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=0, is_reply=0, disable_default_response=1, reserved=0, *is_cluster=True, *is_general=False), tsn=116, command_id=2, *is_reply=False)
2022-05-16 15:28:53 DEBUG (MainThread) [zigpy.zcl] [0xB4F1:1:0x0006] Decoded ZCL frame: OnOff:toggle()
2022-05-16 15:28:53 DEBUG (MainThread) [zigpy.zcl] [0xB4F1:1:0x0006] Received command 0x02 (TSN 116): toggle()
2022-05-16 15:28:53 DEBUG (MainThread) [zigpy.zcl] [0xB4F1:1:0x0006] No explicit handler for cluster command 0x02: toggle()
```

## Additional Context

Add any other context or screenshots about the question here.

**Comment by xaviml** [comment]
Hi @immunity-anomaly,

First of all, the `merge_mapping` allows key-values of events (key) and action types (values). Please read more about custom mapping [here](https://xaviml.github.io/controllerx/advanced/).

Second, I am not sure how to easily cycle throught the sensor list, but you could easily change to a random favourite as indicated in the community forum you linked. The configuration would look like:

```yaml
volume_symfonisk:
  module: controllerx
  class: E1744MediaPlayerController
  controller: 68:0a:e2:ff:fe:3e:02:2b
  integration: zha
  media_player: group.sonos_all
  delay: 350
  volume_steps: 30
  merge_mapping:
    step_0_1_0_0_0:
      service: media_player.select_source
      data:
        source: "{{ state_attr('sensor.sonos_favorites', 'items').values() | list | random }}"
```

The service was copied from: https://community.home-assistant.io/t/using-sonos-favourites-sensor/420380/9

If what you want is to cycle through it, it is much complicated, but the idea is to:
- Create an input_select
- Create automation to fill the options on the input_select based on the sensor.sonos_favorites.
    - Trigger: when the sensor.sonos_favorites > items changes
    - Actions: Update the input_select (have not tested this, but it should work):
    ```yaml
    - service: input_select.set_options
      data_template:
         entity_id: input_select.myselect
         options: {{ state_attr('sensor.sonos_favorites', 'items').values() | list }}
    ```
- You can now use the `input_select.select_next` service to cycle through, the `merge_mapping` part would look like:

```yaml
  ....
  merge_mapping:
    step_0_1_0_0_0:
      - service: input_select.select_next
        data:
          entity_id: input_select.sonos_favorites # the newly created input_select
      - service: media_player.select_source
        data:
          source: "{{ states('input_select.sonos_favorites') }}"
```

Regards,
Xavi M.
