### ISSUE TITLE
[FEATURE REQUEST] - Clarify Z2M 'legacy mode' requirement for HueDimmer controller

### ISSUE THREAD

**Issue by southseaboy** [xaviml/controllerx#496]
# Feature Request

### Is your feature request related to a problem? - Yes

Z2M offer 'legacy' and 'current' message structures for the Philips HueDimmer controller (and a few others). Their documentation 'highly' recommends that the 'legacy' mode is disabled, and only describes the message structure for the 'current' mode.  The principle difference appears to be the use of a dash in legacy mode actions vs an underscore e.g. Legacy: `off-press` vs Current: `off_press`

ControllerX currently implements the message structure for 'legacy' mode for the HueDimmer. If 'current' mode is selected in Z2M any implicit mappings will not work.

I spent some time tracking down this issue as I had followed the Z2M recommendation, and had explicitly used the underscore notation in all my defined action mappings, so it was only the implicit mappings (e.g. click/hold) that didn't work.

### Describe the solution / feature you'd like

Add a note to the ControllerX documentation of the HueDimmer controller that Z2M 'legacy' mode is required.  Although 'legacy' is the default Z2M setting, the Z2M documentation's recommendation may be hinting that they change the default in the future.

### Describe alternatives you've considered

The Philips929002398602 controller implementation in ControllerX expects the underscore action notation, so for my case I disabled the Z2M legacy mode for my HueDimmer and used the alternative controller definition in ControllerX

### Additional context

Z2M has a similar change in message structure for other controllers, e.g. Xiaomi WXKG11LM, IKEA E1524/E1810 - I'm not sure if this affects ControllerX as I've not set them up so far.

**Comment by xaviml** [comment]
Hi @southseaboy ,

Thank you for opening the ticket and for the good explanation of the problem. In ControllerX I have the policy to always maintain the the latest mapping available, so although legacy is by default, I would consider that `legacy: false` as the latest mapping. Therefore, I would go with the `Describe alternatives you've considered` option, which is defining the mapping for legacy mode. This is the case of E1744 where the default mapping is for `legacy: false`.

As of now there is no way to add notes to the pages since they are automatically generated from code, so I will work on this too to add a note.

In the meantime, you can use `mapping` to define the default mapping for `legacy: false`. I just created the following since I have this controller:

```yaml
example_app:
  module: controllerx
  class: HueDimmerController
  controller: sensor.your_controller_action
  integration: z2m
  light: light.your_light
  mapping:
    on_press_release: "on"
    on_hold: hold_color_up
    on_hold_release: release
    up_press_release: click_brightness_up
    up_hold: hold_brightness_up
    up_hold_release: release
    down_press_release: click_brightness_down
    down_hold: hold_brightness_down
    down_hold_release: release
    off_press_release: "off"
    off_hold: hold_color_down
    off_hold_release: release
```

Cheers,

**Comment by xaviml** [comment]
Hi @southseaboy ,

I will leave the issue open so I can track it down and change the default mapping for this device to be the same as the legacy false.

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @southseaboy,

I just released a beta version [v4.21.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.21.0b0) with the change of the HueDimmer mapping as mentioned in this ticket.

You can download from HACS enabling beta versions on ControllerX. Please, let me know if you find any problems. I will be releasing the non-beta version next week or the next.

Regards,
Xavi M.

**Comment by southseaboy** [comment]
Hi @xaviml, I installed v4.21.0b0 / restarted Home Assistant, but it doesn't appear to capturing the on_hold_release action.  If I switch back to the alternative controller (commented out in the config below) the app works correctly (as it did with 4.20).

The controller is bound to the zigbee light group at the zigbee level to provide some resilience in the event of HA failures.  So I'm using controllerX for extended actions not available in the zigbee binding.  All the double clicks are explicitly mapped and work fine, but the `on_hold:` mapping requires that `on_hold_release` is implicitly detected and used by the controllerX app.  When I hold the On button the color temp starts cycling, but does not stop when the button is released.

Thanks for looking at this.

My configuration is 

```yaml
bedroom_philips_remote:
  module: controllerx
#  class: Philips929002398602LightController
  class: HueDimmerController
  controller: sensor.bedroom_remote_action
  integration: z2m
  light: light.main_bedroom_lights
  multiple_click_delay: 500
  merge_mapping:
    on_press$2:
      - service: light.turn_on
        data:
          entity_id: light.main_bedroom_lights
          color_temp: 300
          brightness_pct: 100
          transition: 1.5
    on_hold:
      action: hold # [click, hold] This is the predefined action.
      attribute: color_temp # [brightness, color_temp, white_value, color, xy_color]
      direction: down # [up, down, toggle (only for hold)]
      mode: bounce # [stop, loop, bounce (only for hold)] Stepper mode
      #steps: 10 # It overrides the `manual_steps` and `automatic_steps` global attributes
    up_press$2:
      - service: light.turn_on
        data:
          entity_id: light.main_bedroom_lights
          color_temp: 454
          brightness_pct: 50
          transition: 1.5
    down_press$2:
      - service: light.turn_on
        data:
          entity_id: light.main_bedroom_lights
          color_temp: 454
          brightness_pct: 20
          transition: 1.5
```
