### ISSUE TITLE
[FEATURE REQUEST] Detect composite events like double clicks

### ISSUE THREAD

**Issue by chbndrhnns** [xaviml/controllerx#51]
# Feature Request

I have a couple of Hue Dimmer switches. I would like to detect a double press on a button which is not natively supported.

### Is your feature request related to a problem?

For example, in the bathroom, I have motion sensor which cannot see inside the shower. Thus, I'd like to activate a shower mode where the motion sensor is disabled.

### Describe the solution / feature you'd like

Have composite events like double press that are not natively supported.

**Comment by sreknob** [comment]
Hi @chbndrhnns 
How have you integrated the remote into your setup?
Depending on the integration there are different events exposed. ControllerX an only work with what it can see represented from HASS (unless Xavi gets into checking for multiple events).
This is something that, if it's still attached to your hue hub, you could get long on/off press functionality through [Hue Sensor Advanced](https://github.com/robmarkcole/Hue-sensors-HASS) custom component.
Install the custom component and your remote will be visible in HASS and then you can use ControllerX's state integration to grab a long hold of the top or bottom buttons. Below I have an example for you.

```yaml
ShowerRemote:
  module: controllerx
  class: CallServiceController
  integration: state
  controller: remote.my_bathroom_hue_remote
  mapping:
    "1_hold":
      service: switch.toggle
      data:
        entity_id: switch.enable_shower_mode
```

**Comment by chbndrhnns** [comment]
@sreknob I am trying to understand better. I have no hue bridge in place but a deconz stick. Could  the custom component you are mentioning still help me?

Hue remotes in deconz do not show up as sensors in HA but can only be used by listening for their events.

**Comment by sreknob** [comment]
@chbndrhnns gotcha.
No, the custom component won't help for your specific use case.
Deconz (and all the other integrations) only report short and long button presses/releases for these remotes. The actual remote only sends these events and the hue bridge must do some event counting to get the specific effects of double and triple tap.
You can, however, still use a long button press as is for your event - just add an additional app with the service call you want and the appropriate [deconz mapping](https://xaviml.github.io/controllerx/controllers/hue-dimmer-switch). Something like this:
```yaml
ShowerRemote:
  module: controllerx
  class: CallServiceController
  integration: deconz
  controller: remote.my_bathroom_hue_remote
  mapping:
    1001:
      service: switch.toggle
      data:
        entity_id: switch.enable_shower_mode
```

**Comment by xaviml** [comment]
Hi @chbndrhnns 

Could you maybe send the event when double clicking? How does deCONZ comunicates that through HA events?

As @sreknob is saying, right now the `deconz` integration just listens for the event and not anything else. If the double click or triple is sent with a different event id, then it can be handle by ControllerX.

Thank you both for the collaboration :)

**Comment by chbndrhnns** [comment]
I tried this snippet:

```yaml
livingroom_controller2:
  module: controllerx
  class: CallServiceController
  controller: sensor.office_controller_action
  integration: deconz
  mapping: 
    1002:
      service: switch.toggle
      data:
        entity_id: light.office
```

and I am seeing this error message:

```
2020-03-10 09:07:08.213687 WARNING AppDaemon: Unable to find class CallServiceController in module controllerx - 'livingroom_controller2' is not initialized
2020-03-10 09:07:08.218124 WARNING AppDaemon: Unable to find module livingroom_controller2 - initialize() skipped
```

controllerx is up to date (according to HACS) and I also restarted AppDaemon.
