### ISSUE TITLE
[BUG] Error when long pressing the on/off button E1743

### ISSUE THREAD

**Issue by duceduc** [xaviml/controllerx#512]
# Bug report

## Description
I see the blow error in log whenever I long press either the 'on' or 'off' button. The on/off state and dimming seem to be working fine.

## Additional information

- Devices involved:
  - Model: Ikea E1743
- Integration: Choose from `z2m`
- AppDaemon version: [ v0.9.0 ]
- ControllerX version: [ v4.21.0b2 ]
- HACS version (if installed from there): [ v1.25.5 ]
- Home Assistant Core version: [ v2022.6.5 ]

## AppDaemon app configuration

```
controller config:
    shower_room:
      module: controllerx
      class: E1743Z2MLightController
      controller: shower_room
      integration:
        name: z2m
        listen_to: mqtt
      light:
        name: shower
        mode: mqtt
```

## Logs

```
Zigbee2MQTT:error 2022-06-14 14:58:31: No converter available for 'color_temp_move' ("stop")
```
