### ISSUE TITLE
Trying to use the example on using controllerx for color change on E1810

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#52]
# Question
I'm trying to use the example in the docs, as the E1810 is already paired to the bulbs directly, I would like for it to handle the color cycling.

## Additional information

* Devices involved:
  * Model: E1810
  * TRÅDFRI bulb E27 CWS opal 600lm
* Integration: `deconz `
* AppDaemon version: 4.0.3
* ControllerX version: 2.3.1
* HACS version (if installed from there): 0.22.2
* Home Assistant Core version: 0.106.5

## AppDaemon app configuration

```yaml
kitchen_dinnertable:
  module: controllerx
  class: E1810Controller
  controller: dinnertable_control 
  integration: deconz
  light: group.dinnertable
  actions:
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
    - arrow_right_click
    - arrow_left_click ```

## Logs

```text
```

## Additional Context

For some reason the colous doesn't change, I can't figure out what I did wrong?
The controller name is fetched from deconz_event.

**Comment by htvekov** [comment]
Hi' fribse.

Only have z2m integration in house, but here it works with a single bulb.
Have you tested controlling a single bulb, just to rule out any issues with groups ?

Ikea bulbs HAVE issues with multiple attributes in calls (brightness and color change).

For more info on these Ikea bulb issues, you could check this (massive) thread: https://github.com/xaviml/controllerx/issues/45

Ciao !

**Comment by htvekov** [comment]
Just made a group with a single bulb and tested.
Color change ok via z2m integration with exact same bulb and controller.

**Comment by fribse** [comment]
Really weird, I've changed it to a single bulb, and I see the events:

```
{
    "event_type": "deconz_event",
    "data": {
        "id": "dinnertable_control",
        "unique_id": "00:0d:6f:ff:fe:21:83:ac",
        "event": 4002
    },
    "origin": "LOCAL",
    "time_fired": "2020-03-07T16:05:27.754047+00:00",
    "context": {
        "id": "xxx",
        "parent_id": null,
        "user_id": null
    }
}

```

The apps.yaml:

```
kitchen_dinnertable:
  module: controllerx
  class: E1810Controller
  controller: dinnertable_control 
  integration: deconz
  light: light.dinnertable_1
  actions:
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
    - arrow_right_click
    - arrow_left_click  
```
I don't get it?

**Comment by sreknob** [comment]
@fribse - what happens if you remove the `actions`? Unless you're using the remote for multiple things, you shouldn't have to list the actions you want.

**Comment by htvekov** [comment]
@fribse 

Can you change colors at all directly from HA via service calls ?
Just like my test example below (revice to your own entity_id)
The transition attribute is not actually needed unless you're using a Hue bridge for your lights.

![image](https://user-images.githubusercontent.com/45469813/76150092-d6a1ff80-60a6-11ea-922a-e1f2d7051c3a.png)

**Comment by fribse** [comment]
@sreknob If I remove the 'actions' section then the coor change works, but the 'turn off/on' goes bezerk as it both gets the command directly and via the controllerx 😁 
@htvekov I can change colors both via Google and via service calls.

**Comment by sreknob** [comment]
@fribse - do you need it paired directly as well?

I think I see the issue though - you are using z2m actions but using deconz integration. You need to either use the doconz mappings or a custom controller with just the mappings you want.

Try:

```yaml
kitchen_dinnertable:
  module: controllerx
  class: E1810Controller
  controller: dinnertable_control 
  integration: deconz
  light: light.dinnertable_1
  actions:
    - 4001
    - 4002
    - 4003
    - 5001
    - 5002
    - 5003
```
