### ISSUE TITLE
Predefined light action (sync) not working as expected

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#54]
# Bug report

## Description

The `sync` action only changes the brightness to the maximum level, however, we also want the light to be set at 2700K or in a white colour

**Comment by htvekov** [comment]
Hi' Xavi.

Follow up on my 'special' ControlllerX apps to get `sync` working properly 😊

I'm convinced that the following suggested changes in code, would work for `sync` with light from both `on` and` off `position. Have made the last test now with Ikea white spectrum on Hue bridge. This also worked properly from both `on` and `off` positions.

Needed changes to code (I believe):
- Allow transition attribute again. Patch ControllerX beta v2.4.0b3 lightcontroller.py line 301 to: 
`await self.on(add_transition=True, **attributes)`
  This is essential to get the brightness set as well as the color with Ikea bulb on Hue bridge. `transition: 0` in app works. Will accept higher transitions as well. Haven't tested though to find appx. max. useful value of transition attribute.

-  `toggle_hold` from `off` HAS to be called with transition attribute: 0 (zero attribute works for sure)
-  `toggle_hold` from `on` HAS to be made in two calls:
    - First, turn on light (transition and/or brightness attribute can be omitted).
    - Second, turn on light again with transition: 0 (zero attribute works for sure)

Below my 'revised' ControllerX apps that have been tested to work with:

- Ikea color bulb on z2m network
- Hue bulb on Hue bridge
- Ikea white spectrum bulb on Hue bridge
Environment: ControllerX beta v2.4.0b3 _**(patched to allow `transition` attribute)**_

If we can get this to work in z2m networks and on Hue bridges, we will have to get the Deconz/ZHA guys to test as well. And also with other bulbs than Ikea and Philips Hue.

**+++ REVISED cut from issue #45 +++**

Using latest beta v2.4.0b3 (with a small patch), I've made some controllerX apps to 'emulate' toggle_hold from off when light is actually on 😁
It's completely 'quick and dirty' for test purposes, but it works with toggle_hold both from on and off light positions.
I just test if toggle_hold originally came from an light on position. If yes, turn on light again and call toggle_hold via mqtt

```
hallway_light_group_no_toggle:
  # all actions, but toggle_hold for smooth operation with light groups on Hue Bridge
  module: controllerx
  class: E1810Controller
  controller: sensor.0x90fd9ffffe17d796_action
  integration: z2m
  #transition: 500  # Optional but not needed to get `sync` function to work
  smooth_power_on: true
  light: light.mikkel_loft # Ikea White Spectrum bulb on Hue bridge
  actions:
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
    - arrow_right_click
    - arrow_left_click
    - brightness_up_click
    - brightness_down_click
    - brightness_up_release
    - brightness_down_release
    - brightness_up_hold
    - brightness_down_hold
    - toggle

hallway_light_group_toggle_hold_from_off:
  module: controllerx
  class: E1810Controller
  controller: sensor.0x90fd9ffffe17d796_action
  integration: z2m
  transition: 0 #transition attribute works on Hue bridge. *** Needed for Ikea bulbs on Hue Bridge to change color AND brightness on sync !! Otherwise ONLY color will change !! *** 
  light: light.mikkel_loft
  actions:
    - toggle_hold
  constrain_input_boolean: light.mikkel_loft,on #ensure that toggle_hold will only be called when lights was off and has just turned on (toggle_hold from off)

hallway_light_group_toggle_hold_from_on:
  module: controllerx
  class: CallServiceController
  controller: sensor.0x90fd9ffffe17d796_action
  integration: z2m
  mapping:
    toggle_hold:
      - service: light.turn_on
        data:
          entity_id: light.mikkel_loft
          #brightness: 255  # Optional but not needed to get `sync` function to work
          #transition: 0 # Optional but not needed to get `sync` function to work
      - service: mqtt.publish #publish the toggle_hold command again, now with lights on
        data:
          topic: 'zigbee2mqtt/Ikea hallway'
          payload: '{"linkquality":80,"battery":80,"update_available":true,"action":"toggle_hold"}'
      - service: mqtt.publish
        data:
          topic: 'zigbee2mqtt/Ikea hallway'
          payload: '{"linkquality":80,"battery":80,"update_available":true,"action":""}'
  constrain_input_boolean: light.mikkel_loft,off #ensure that toggle_hold will only be called when lights was on and was turned off by first toggle (toggle_hold from on)
```
