### ISSUE TITLE
[QUESTION] "Querying a specific attribute is only possible for a single entity"

### ISSUE THREAD

**Issue by SergioRius** [xaviml/controllerx#547]
# Question

Using direct mqtt publlishing gives that error, while going through HA there's no problem.
This is a double rocker aqara switch and I want to bind to the lights the right one.
Is it not possible or I'm doing something wrong?

## Additional information

- Devices involved:
  - Model: WXKG07LM as Controller
  - Model: Innr RS 227 T as Lights
  - light.despacho_ceiling is a Z2M group of lights.
- Integration: z2m
- AppDaemon version: v4.2.2
- ControllerX version: v4.22.0
- HACS version (if installed from there): standalone
- Home Assistant Core version: v2022.7.7

## AppDaemon app configuration

```yaml
despacho_sw1_right:
  module: controllerx
  class: WXKG07LMLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  # light: light.despacho_ceiling
  light:
    name: despacho_ceiling
    mode: mqtt
  actions:
    - right
    - right_double
    - right_long
```

## Logs

```text
2022-08-10 13:04:04.586847 WARNING despacho_sw1_right: ------------------------------------------------------------
--
2022-08-10 13:04:04.586641 WARNING despacho_sw1_right: Traceback (most recent call last):   File "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app     await init()   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/controller.py", line 104, in initialize     await self.init()   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/type/light_controller.py", line 148, in init     await super().init()   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/type_controller.py", line 57, in init     self.entity = await self._get_entity(self.args[self.entity_arg])   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/type_controller.py", line 100, in _get_entity     entities = await self._get_entities(entity_name) if self.domains else None   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/type_controller.py", line 73, in _get_entities     entities: Optional[Union[str, List[str]]] = await self.get_state(   File "/home/appdaemon/.appdaemon/conf/apps/controllerx/cx_core/controller.py", line 371, in get_state     return await super().get_state(   File "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/adapi.py", line 1511, in get_state     return await self.get_entity_api(namespace, entity_id).get_state(attribute, default, copy, **kwargs)   File "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/entity.py", line 149, in get_state     return await self.AD.state.get_state(self.name, namespace, entity_id, attribute, default, copy)   File "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/state.py", line 500, in get_state     raise ValueError("{}: Querying a specific attribute is only possible for a single entity".format(name)) ValueError: despacho_sw1_right: Querying a specific attribute is only possible for a single entity
2022-08-10 13:04:04.586118 WARNING despacho_sw1_right: ------------------------------------------------------------
2022-08-10 13:04:04.585870 WARNING despacho_sw1_right: Unexpected error running initialize() for despacho_sw1_right
2022-08-10 13:04:04.585619 WARNING despacho_sw1_right: ------------------------------------------------------------
```

**Comment by xaviml** [comment]
Hi @SergioRius ,

It seems that I forgot to give support for Zigbee2MQTT Light controller for this device. So, `WXKG07LMLightController` is a light controller, but you would need to use `WXKG07LMZ2MLightController` which does not exists. I will be adding it for the next release so you can configure it like:

```yaml
despacho_sw1_right:
  module: controllerx
  class: WXKG07LMLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  light:
    name: despacho_ceiling
    mode: mqtt
  actions:
    - right
    - right_double
    - right_long
```

In the meantime, you will need to configure it like:

```yaml
despacho_sw1_right:
  module: controllerx
  class: WXKG07LMLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  light: light.despacho_ceiling
  actions:
    - right
    - right_double
    - right_long
```

Or specify a mapping:

```yaml
despacho_sw1_right:
  module: controllerx
  class: Z2MLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  light:
    name: despacho_ceiling
    mode: mqtt
  mapping:
    right: toggle
    right_double: click_brightess_up
    right_long: click_brightess_down
```

Please, keep this issue open so I can reference it when adding `WXKG07LMZ2MLightController`.

Regards,
Xavi M.

**Comment by xaviml** [comment]
The support for this device has been added to a new beta version, [ControllerX v4.23.0b0](https://github.com/xaviml/controllerx/releases/tag/v4.23.0b0). You can now download it from HACS by enabling the beta versions.

**Comment by xaviml** [comment]
Hola @SergioRius  :)

> Unfortunately my appdaemon is installed standalone, so it's not that easy to install the beta. But I'll place the files there.

I see.. You can grab the changes for this issue here: https://github.com/xaviml/controllerx/commit/e8dbebc841e20ab096ee73e0ad695377ea3b5054

> Could controllerX be programmed so whenever a hold-click is detected it starts a complete dimming cycle, from the current value to full, then to 1%, then to the original value, and if any key is pressed, stops the cycle and leaves the light there?
The current functionality is not practical with switches that don't report the hold duration and that doesn't have a release action.

Yes, this is definitely possible. You can create a custom mapping and program a click with the `hold_brightness_up` for example. Then, you will need to create a mapping for another mapping to do the `release`. Although the action is called `hold`, it can be executed with any action, and be stopped with a `release`. You can also use `hold_release_toggle` from [Light Controller](https://xaviml.github.io/controllerx/start/type-configuration/#light-controller), this will allow you to use any `hold` action as `release` when the hold is in action. If you specify your use case (e.g. when using device XYZ with integration ABC, I would like that when pressing X, Y happens), then I will help you out with the configuration.

> Could the double click be programmed to turn on the light to a certain level (max brightness, higher temp.)? I don't understand mappings and merge mappings. And for all controllers without having to do a map on each (global mapping)?

Yes, it is possible, I recommend you reading [the custom mapping page](https://xaviml.github.io/controllerx/advanced/) and the [multiple click documentation](https://xaviml.github.io/controllerx/advanced/multiple-clicks/). If you specify the device, the integration and the use case, I will help you out with the configuration.

> BTW, shouldn't that be:
>```
>    class: WXKG07LMZ2MLightController
>```

Yes, you are right, the new class is `WXKG07LMZ2MLightController`, so you can use that one.

Regards,
Xavi M.

**Comment by SergioRius** [comment]
> If you specify your use case (e.g. when using device XYZ with integration ABC, I would like that when pressing X, Y happens), then I will help you out with the configuration.

Thank Xavi. Could you please share the example model configuration for the entry I posted above? I only have two types of switches. That Aqara ones and... TS0044 => TS0044LightController

I've already installed the revision and I'll be testing it.

I have a setup that is fastly becoming complicated. I didn't like the existing circadian lighting implementations. The integration worked well but the lighting curves were horrible. The blueprint had better curves, but the automation part failed.
So I wrote a new one in node-red with a rel-world curve and the switching capabilities of the integration.
And this week I'm implementing Automoli for activating lights with motion sensors.

And trying to integrate controllex+circadian+automoli is giving me come headaches. controllerx was first and as I made my circadian myself it's compatible. But automoli.... it's a PITA.

If you let me suggest... **It would be nice that you could specify brightness and mired/kelvin entities for picking the first turn-on state** and that will allow to avoid the "first flash". Also perhaps It'll make direct circadian mqtt integration possible. (It'll have to listen for mqtt for updates).

Then the part that updates the temperature and brightness and the automoli integration is a problem. If you instruct automoli to manage other agent's actions I'll turn off the lights even when you manually swiched them and wanted to stay on. And if you configure the contrary, it never turns the lights off, even when he turned them on, because the circadian automation has updated temperature, and identified as a take-on control.

That's where controllerx enters the stage. I would need **controllerx to also turn on a binary sensor along with the lights. And then turn it off also with the lights.** I would add this binary as a motion sensor to automoli and setup to override other agents. But this binary would tell him that he can't turn the light off.
As per documentation I've tried to setup a group of lights.
**BTW theres a problem there, documentation says that groups can be used but controllerx throws an error that only lights are allowed.
Then if you try to configure a light group with a binary sensor, HA throws not being possible to add a binary sensor to a light group.**

HA
```yaml
input_boolean:
  lighting_workplace_lights_manually_triggered:
    name: Workplace lights manually triggered

light:
  - platform: group
    name: workplace_lights_ceiling
    entities:
      - light.despacho_ceiling
      - input_boolean.lighting_workplace_lights_manually_triggered     # THAT WILL GIVE ERROR
```
cX
```yaml
despacho_sw1_right_toggle:
  module: controllerx
  class: WXKG07LMLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  light: light.workplace_lights_ceiling
  actions:
    - right
```
Any idea in how to solve this?
Ideally controllerX should include **motion sensors as a controller**. That would be awesome.

**Comment by xaviml** [comment]
Hi @SergioRius ,

Sorry for the delay. I am glad you figured a way out to do this. Let comment on your comments:

>  It would be nice that you could specify brightness and mired/kelvin entities for picking the first turn-on state

Not sure what you mean, but you can set for the "on" and "toggle" [predefined actions](https://xaviml.github.io/controllerx/advanced/predefined-actions/) an attribute mapping to specify any attributes you want to pass to the light (brightness, color_temp, etc.). It would be something like:

```yaml
example_app:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.controller_action
  light: light.my_light
  merge_mapping:
    toggle:
      action: toggle
      attributes:
        brightness: 128
        xy_color: [0.323, 0.329]
```

> controllerx to also turn on a binary sensor along with the lights. And then turn it off also with the lights.

I think you solved in a way I would have done if you always want the light be in pair with the input_boolean. Otherwise, you could do:

```yaml
  module: controllerx
  class: WXKG07LMLightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: despacho_sw1
  light: light.controllerx_workplace_lights_ceiling
  mapping:
    right:
      - toggle
      - service: input_boolean.toggle
        entity_id: input_boolean.automoli_override_workplace_lights_ceiling
```

> BTW theres a problem there, documentation says that groups can be used but controllerx throws an error that only lights are allowed.

Only light entities are allowed in light groups, sorry if the documentation was not clear on this.

> Ideally controllerX should include motion sensors as a controller. That would be awesome.

ControllerX is focused to solve one main problem, which is pair controllers with devices with minimal configuration. However, project grew and I was forced on making it as flexible as possible for different use cases. One of them is to control lights with sensors. Although sensors are not added as controllers, it can be easily customised from configuration. I used to have AutoMoLi for my bathroom light to turn on with a sensor, however, since configuration for AutoMoLi was not complicated, I replaced it with ControllerX:

```yaml
bathroom_day:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/bathroom_sensor
  integration:
    name: mqtt
    key: occupancy
  light: light.bathroom_wled
  mapping:
    "true":
      scene: scene.bathroom_light_day
    "false": "off"
  constrain_start_time: "07:30:00"
  constrain_end_time: "23:00:00"

bathroom_night:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/bathroom_sensor
  integration:
    name: mqtt
    key: occupancy
  light: light.bathroom_wled
  mapping:
    "true":
      scene: scene.bathroom_light_night
    "false": "off"
  constrain_start_time: "23:00:00"
  constrain_end_time: "07:30:00"
```

Another use case would be the configuration for the light on a stairway. I wanted to have a light turn on based on 2 sensors and also be able to turn it on and off with a button. All configuration I needed was:

```yaml
stairway:
  module: controllerx
  class: Z2MLightController
  controller:
    - zigbee2mqtt/stairway_sensor01
    - zigbee2mqtt/stairway_sensor02
  light:
    name: stairway_switch02
    mode: mqtt
  integration:
    name: mqtt
    key: occupancy
  mode: restart
  mapping:
    "true":
      - "on"
      - delay: 70
      - "off"

stairway_button:
  module: controllerx
  class: Z2MLightController
  controller: stairway_switch01
  light:
    name: stairway_switch02
    mode: mqtt
  integration:
    name: z2m
    listen_to: mqtt
  mapping:
    single: toggle
```

The `stairway` config turns on the light when there is movement and it turns it off after 70 seconds delay. The second configuration just toggles the same light.

Maybe these configurations and ideas can help you to simplify your solution.

Regards,
Xavi M.

**Comment by xaviml** [comment]
`WXKG07LMZ2MLightController` is ready to be used now on [ControllerX v4.23.0](https://github.com/xaviml/controllerx/releases/tag/v4.23.0). I will mark this issue as closed.

**Comment by SergioRius** [comment]
Hello Xavi, I'm sorry for the delay. The new controller seems OK to me. Probably you already know it.

You have me such nice examples and I'm already playing with them. Thank you. I wonder if there is any public repo with more of those examples of yours.

> Not sure what you mean, but you can set for the "on" and "toggle" [predefined actions](https://xaviml.github.io/controllerx/advanced/predefined-actions/) an attribute mapping to specify any attributes you want to pass to the light (brightness, color_temp, etc.). It would be something like:

In this case, what I want is:
```yaml
example_app:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.controller_action
  light: light.my_light
  merge_mapping:
    toggle:
      action: toggle
      attributes:
        brightness: {{ states('sensor.nr_circadian_pwm') }}
        color_temp: {{ states('sensor.nr_circadian_mireds') }}
```
Is it possible?
