### ISSUE TITLE
[QUESTION] E1810 and lightgroup: only modify color temperature

### ISSUE THREAD

**Issue by bartplessers** [xaviml/controllerx#558]
# Question

Hi,

I have a lightgroup with bulbs with mixed properties:
- some of them can only change color temperature (and brightness)
- some of them can change color, color temperature (and brightness)

my app:
```

# ---------------------------------------------------------------
# GANG
# ---------------------------------------------------------------
# IKEA dimmer 5 buttons
my_n99_p99_switch_r11_dimmer:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.my_n99_p99_switch_r11_testschakelaar_action
  light: light.group_n00_p00

```

The on/off and dim functions work perfect.
However, the left/right button on the E1810 change the color which is -in my case- not wanted. I prefer to have my color temperature changed instead of the color itself.

Can this be done?

kind regards,
B

**Comment by bartplessers** [comment]
OK, found it

```
# ---------------------------------------------------------------
# GANG
# ---------------------------------------------------------------
# IKEA dimmer 5 buttons
my_n99_p99_switch_r11_dimmer:
  module: controllerx
  class: E1810Controller
  integration: z2m
  controller: sensor.my_n99_p99_switch_r11_testschakelaar_action
  light: light.group_n00_p00
  supported_color_modes: ["color_temp"]

```

grtz
B
