### ISSUE TITLE
[NEW DEVICE] TuYa ERS-10TZBVK-AA in Z2M

### ISSUE THREAD

**Issue by domidyon** [xaviml/controllerx#559]
# New Device Support

## Device Information

- Device Model: TuYa ERS-10TZBVK-AA
- Device Description: Smart Knob
- Device Manufacturer: TuYa

#### Actions

- `rotate_right`: Sent when knob is rotated to the right
- `rotate_left`: Sent when knob is rotated to the left
- `single`: Sent when knob is pushed downward
- `double`: Sent when knob is pushed downward twice
- `hold`: Sent when knob is pushed down and kept down for a few seconds

#### Notes

Aforementioned actions were performed when device was in 'event' mode.

**Comment by xaviml** [comment]
Hi @domidyon ,

Thank you for the device information, I will be giving support for this device for next release.

According to documentation, the device exposes more actions: https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html Is that correct?

Regards,
Xavi M.

**Comment by domidyon** [comment]
> Hi @domidyon ,
> 
> Thank you for the device information, I will be giving support for this device for next release.
> 
> According to documentation, the device exposes more actions: https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html Is that correct?
> 
> Regards, Xavi M.

Hi Xavi,

I would love to check that out for you. Unfortunately, i'm having a hard time to figure out how I would perform a scan or whatever to see what else is possible for the device. Do you have a link or article I could dive into and let you know?

**Comment by RedWavve** [comment]
Proper Z2M description is the link you shared, yes.

Device can be set in two modes : Command and Event

Command mode will send:
- ACTION = Brightness_Step_Up
- ACTION = Brightness_Step_Down
- ACTION = Toggle
- ACTION = color_temperature_step_up
- ACTION = color_temperature_step_down
- Action_Step_Size = %Numeric_Value (0_255)
- Action_Rate = N/A

Event mode will send:
- ACTION = rotate_left
- ACTION = rotate_right
- ACTION = single
- ACTION = double
- ACTION = hold

A triple click will toggle betweekn COMMAND and EVENT mode

**Comment by domidyon** [comment]
Ah thanks @RedWavve -- I haven't had mine in 'action' mode. I will report the corresponding actions to button presses/actions in 20 minutes or so - currently doing some maintenance on my Z2M.

**Comment by RedWavve** [comment]
> Ah thanks @RedWavve -- I haven't had mine in 'action' mode. I will report the corresponding actions to button presses/actions in 20 minutes or so - currently doing some maintenance on my Z2M.

I should have them all up, so no need !

You can see or check the mode in Z2M, using the "Expose" tab of the device

**Comment by xaviml** [comment]
Hi @domidyon and @RedWavve ,

Thank you for your input. I am currently implementing the default mapping for this controller and this is what I came up with:
```python
# Command mode
"brightness_step_up": Light.CLICK_BRIGHTNESS_UP,
"brightness_step_down": Light.CLICK_BRIGHTNESS_DOWN,
"toggle": Light.TOGGLE,
"hue_move": Light.HOLD_BRIGHTNESS_TOGGLE,
"hue_stop": Light.RELEASE,
"color_temperature_step_up": Light.CLICK_COLOR_UP,
"color_temperature_step_down": Light.CLICK_COLOR_DOWN,

# Event mode
"rotate_left": Light.CLICK_BRIGHTNESS_DOWN,
"rotate_right": Light.CLICK_BRIGHTNESS_UP,
"single": Light.TOGGLE,
"double": Light.ON_FULL_BRIGHTNESS,
"hold": Light.ON_MIN_BRIGHTNESS,
```

Note that I did not add `hold` actions to the rotations since there are no stop rotation actions. If you want to feel how this would look like after the device is supported, you can try the following configuration:

```yaml
example_app:
    module: controllerx
    class: LightController
    controller: sensor.your_controller_action
    integration: z2m
    light: light.your_light
    mapping:
        # Command mode
        brightness_step_up: click_brightness_up
        brightness_step_down: click_brightness_down
        toggle: toggle
        hue_move: hold_brightness_toggle
        hue_stop: release
        color_temperature_step_up: click_color_up
        color_temperature_step_down: click_color_down
        # Event mode
        rotate_left: click_brightness_down
        rotate_right: click_brightness_up
        single: toggle
        double: on_full_brightness
        hold: on_min_brightness
```

Let me know if there is any action you would change for something different. You can check the [predefined actions here](https://xaviml.github.io/controllerx/advanced/predefined-actions).

Regards,
Xavi M.
