### ISSUE TITLE
[QUESTION] Controlling IKEA light colors with E1810Controller

### ISSUE THREAD

**Issue by Ronnie-J** [xaviml/controllerx#56]
# Question

Hi!

It's not clear to me if it's possible with the `E1810Controller` to controll the different light colors from the IKEA lamps. Nothing happens when pushing the right and left arrow with the following configuration. I tried to manually config actions on the buttons but I havent been able to get anything working. It can turn the light off/on and dim the lights which is great but the last bit is missing - thanks.

## Additional information

* Devices involved:
* Model: IKEA of Sweden, TRADFRI bulb E27 WS opal 1000lm, Version `2.0.022`
* Integration: `deconz`
* AppDaemon version: `v4.0.3`
* ControllerX version: `v2.4.2`
* HACS version `v0.23.2`

## AppDaemon app configuration

```
livingroom_controller:
  module: controllerx
  class: E1810Controller
  controller: tradfri_remote_control
  integration: deconz
  light: light.stue
```
