### ISSUE TITLE
ESPHome Home Assistant API Events [FEATURE REQUEST]

### ISSUE THREAD

**Issue by ashp8i** [xaviml/controllerx#561]
# Feature Request

### Describe the solution / feature you'd like

I have DIY esphome buttons scattered around the house and want to use them with ControllerX

the esphome node has been configured as follows and generates the following home assistant api events: -

```
binary_sensor:
  - platform: gpio
    name: "${device_name} Button 1"
    pin:
      number: GPIO12
      mode:
        input: true
    on_multi_click:
      # double click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          # send double click event
          - homeassistant.event:
              event: esphome.${device_name}
              data:
                title: button 1 double click
        # long click
      - timing:
          - ON for at least 1.5s
        then:
          - homeassistant.event:
              event: esphome.${device_name}
              data:
                title: button 1 long click
        # single click
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.${device_name}
              data:
                title: button 1 short click
    on_release:
      - homeassistant.event:
          event: esphome.${device_name}
          data:
            title: button 1 released
```

Events in Home Assistant Developer Tools - Listen to events

```
event_type: esphome.masterbedroombutton
data:
  device_id: ef8d76417141da3c439b91d97a7cd467
  title: button 1 short click
origin: LOCAL
time_fired: "2022-08-31T11:47:35.401754+00:00"
context:
  id: 01GBSVMSB9WXV4P9BHCWZBTVGZ
  parent_id: null
  user_id: null
```

my wall buttons have 4 buttons and generate short click, long click, double click possibly a triple click and a release

I'd like to be able to use this with LightController and SwitchController where esphome.* is user defined and so may be the structure of the event depending on how the node was setup, but my example's output is the above! 
The payload could be message instead of title

[https://esphome.io/components/api.html?highlight=events](url)

```
homeassistant.event Action

When using the native API with Home Assistant, you can create events in the Home Assistant event bus straight from ESPHome [Automations](https://esphome.io/guides/automations.html#automation).

# In some trigger
on_...:
  # Simple
  - homeassistant.event:
      event: esphome.button_pressed
      data:
        message: Button was pressed

Configuration options:

    event (Required, string): The event to create - must begin with esphome.

    data (Optional, mapping): Optional static data to pass along with the event.

    data_template (Optional, mapping): Optional template data to pass along with the event. This is evaluated on the Home Assistant side with Home Assistant’s templating engine.

    variables (Optional, mapping): Optional variables that can be used in the data_template. Values are [lambdas](https://esphome.io/guides/automations.html#config-lambda) and will be evaluated before sending the request.
```

hopefully this allows some creativity without overcomplication! As well as encourage usage of ESPHome!

apologies to throw another one into the mix, another thing to consider might be MQTT as an alternative of home assistant events.

```
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "2"
```

or 

source: -

[https://www.reddit.com/r/homeassistant/comments/cvllno/comment/ey7o9tb/?utm_source=share&utm_medium=web2x&context=3](url)

```
- platform: gpio
pin: D6
name: "ESP2 touchpad"
filters:
on_multi_click:
- timing:
- ON for at most 1s
- OFF for at most 1s
- ON for 0.1s to 1s
- OFF for at least 0.2s
then:
- logger.log: "Double Click"
- mqtt.publish:
topic: esp2/binary_sensor/esp2_touchpad/state
payload: "Double Click"
- timing:
- ON for 1s to 3s
- OFF for at least 0.5s
then:
- logger.log: "Single Long Click"
- mqtt.publish:
topic: esp2/binary_sensor/esp2_touchpad/state
payload: "Single Long Click"
- timing:
- ON for at most 1s
- OFF for at least 0.5s
then:
- logger.log: "Single Short Click"
- mqtt.publish:
topic: esp2/binary_sensor/esp2_touchpad/state
payload: "Single Short Click"
```

I understand you may need to template payloads for easy configuration/code organisation for multiple buttons.

What I'm after is like Ikea E1524 but done in esphome supported by ControllerX.

### Describe alternatives you've considered

These are currently running as Home Assistant Automations

### Additional context

As always many thanks for this great project,
Ash
