### ISSUE TITLE
Trying to split up/down for cover in z2m

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#563]
# Question

I want to have the 'down' limited depending on a windows sensor. I had this setup with deconz, but I'm slowly moving stuff to z2m, and I want to do the same here.

If I don't have the 'action' limiter (and only 1 app defined for this), the controller can move the blind up / down.
But as soon as I give a list of actions, nothing happens?

## Additional information

- Devices involved:
  - Model: E1766CoverController
  - ...
- Integration: z2m
- AppDaemon version: [ eg. v4.0.1 ]
- ControllerX version: [ eg. v2.2.1 ]
- HACS version (if installed from there): [ eg. v0.21.5 ]
- Home Assistant Core version: 2022.09.1

## AppDaemon app configuration

```yaml
office_cover1_up:
  module: controllerx
  class: E1766CoverController
  controller: sensor.office_cover_action
  integration: z2m
  cover: cover.office
  actions:
    - "on"
    - brightness_stop

office_cover1_down:
  module: controllerx
  class: E1766CoverController
  controller: sensor.sofa_control_action
  integration: z2m
  cover: cover.office
  constrain_input_boolean: binary_sensor.office_window_contact,off
  actions:
    - "off"
    - brightness_stop
  ```

## Logs

```text
```
