### ISSUE TITLE
Toggle (after off with a transition) dont set brightness to previous level

### ISSUE THREAD

**Issue by htvekov** [xaviml/controllerx#58]
Hi' Xavi

There's an issue with `toggle` function for Ikea bulbs on `z2m` integration (perhaps also other integrations as well. Haven't had time yet to check Hue bridge behaviour)

If lights are turned off with any transition period specified, then lights will only come on again at lowest brightness. HA state has correct brightness, but bulb has not !!

Example: Automation for a hallway sensor to turn off a group of hallway lights after a certain period with no movement. This is done with a transition period for eg. 1 seconds
If lights afterwards are turned on again via ControllerX app (toggle button), then previous brightness is not restored to bulbs - only HA states.

Solution: Always call `toggle` event with transition attribute set

```
    @action
    async def off(self, **attributes):
        if "transition" not in attributes:
            attributes["transition"] = self.transition / 1000
        self.call_service("homeassistant/turn_off", entity_id=self.light["name"], transition=attributes["transition"])

    @action
    async def toggle(self, **attributes):
        if "transition" not in attributes:
            attributes["transition"] = self.transition / 1000
        self.call_service("homeassistant/toggle", entity_id=self.light["name"], transition=attributes["transition"])
```

Above change to lightcontroller.py should handle this nicely.
Can't think of any other problems above change would do to other aspects of app ?

I've included transition to `turn_off` function as well, just to make it turn off nicely with a transition - if specified 😊

Tested for now with both Ikea WS (White Spectrum) and Ikea color bulbs on z2m.
Not tested yet: Ikea and Hue bulbs behavior on Hue bridge.

* Devices involved:
* Model: IKEA E1810 as Light Controller
* Integration: `z2m`
* AppDaemon version: v4.0.2.3
* ControllerX version: v2.4.2
* HACS version (if installed from there): v0.23.2
* Home Assistant Core version: v0.106.6

## AppDaemon app configuration

```
office_test:
  module: controllerx
  class: E1810Controller
  controller: sensor.0xec1bbdfffe1b99e8_action #Ikea 5 button remote
  integration: z2m
  #transition: 1000 #transition attribute works on Hue bridge
  smooth_power_on: true
  light: light.0x90fd9ffffe838cb3_light # Color bulb office
  actions:
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
    - arrow_right_click
    - arrow_left_click
    - brightness_up_click
    - brightness_down_click
    - brightness_up_release
    - brightness_down_release
    - brightness_up_hold
    - brightness_down_hold
    - toggle
    - toggle_hold
```
