### ISSUE TITLE
[QUESTION] E2002LightController: is there a way to cycle between color and white temperature mode?

### ISSUE THREAD

**Issue by neuronflow** [xaviml/controllerx#602]
# Question

Is there a way to cycle between color and light temperature mode?

## Additional information

E2002LightController

**Comment by neuronflow** [comment]
I realize I am a bit puzzled how to best controllers.

I have two light groups, for both I can set color or white temperature.

Is it possible to control these with a single E2002?

instead of a simple on/off, the up-down action could cycle through scenes?

```
scene A:
group 1 -> color mode
group 2 -> color mode

scene B:
group 1 -> white mode
group 2 -> white mode

Scene C:
group 1 -> off
group 2 -> white mode
```

**Comment by neuronflow** [comment]
Hmm so far I don't really manage to set the color temperature. My light bulbs support both, color and white temperature. These settings seem to emulate color temperature by switching values in the color mode:

```
  light:
    name: light.office
    color_mode: color_temp
    
...

  color_wheel: color_temp_wheel


```

How can I set the actual white temperature?

**Comment by xaviml** [comment]
Hi @neuronflow ,

I am a little bit confuse on what you would like to achieve, what do you mean that you would like a scene where you can control "white mode", "color mode", and then be "off"? What does it mean to be off? What would you be controlling with the controller?

You can change the whitevalue with [predefined actions](https://xaviml.github.io/controllerx/advanced/predefined-actions/):
- click_white_value_up
- click_white_value_down
- hold_white_value_up
- hold_white_value_down

Through [custom mapping](https://xaviml.github.io/controllerx/advanced/).

For example:
```yaml
example_app:
  module: controllerx
  class: E2002LightController
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.livingroom
  merge_mapping:
    arrow_left_click: click_white_value_down
    arrow_right_click: click_white_value_up
    arrow_left_hold: hold_white_value_down
    arrow_right_hold: hold_white_value_up
```

Regards,
Xavi M.

**Comment by neuronflow** [comment]
Hi @xaviml ,
thanks for taking the time. So my lamps support both color and tuneable white. I would like to regulate both with the Styrbar 4 button remote, so I am looking for an intuitive way to switch between color temperature and color mode.


I realize this might be related to:
https://github.com/xaviml/controllerx/issues/610

**Comment by neuronflow** [comment]
naive idea:

the on button could toggle the lamp on and off.

the off button could cycle between brightness, white temperature, and color wheel for the left/right keys.

I am not sure whether it is possible to realize this with controllerx?

**Comment by neuronflow** [comment]
```
  merge_mapping:
    arrow_left_click: click_white_value_down
    arrow_right_click: click_white_value_up
    arrow_left_hold: hold_white_value_down
    arrow_right_hold: hold_white_value_up
```

this produces the following error when pressing left:
```
appdaemon                  | ValueError: Value for `white_value` attribute could not be retrieved from `light.lr_couch`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
```

**Comment by xaviml** [comment]
Hi @neuronflow ,

Does your light (`light.lr_couch `) supports white value? If so, it should show the white_value in the state attributes. ControllerX needs to know the previous value, so it can know which brightness to set on.

> thanks for taking the time. So my lamps support both color and tuneable white. I would like to regulate both with the Styrbar 4 button remote, so I am looking for an intuitive way to switch between color temperature and color mode.

Correct, this is related to #610. There is an example at the end of the [examples page](https://xaviml.github.io/controllerx/examples), but the example page need a bit of work since it is difficult to find things. To achieve what you want, there might be different way, but the most flexible way would be to be explicit with all the "scenes" you want and configure each "scene" with ControllerX config. First, you need an input select (input_select.my_input_select), which you can create on the UI with following options for example:
- scene_a
- scene_b
- scene_c

Then, in `apps.yaml`, you can define:
```yaml
scene_a:
  module: controllerx
  class: E2002LightController
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.my_light
  merge_mapping:
    "on":
      - service: input_select.select_next
        entity_id: input_select.my_input_select
    "off":
      - service: input_select.select_previous
         entity_id: input_select.my_input_select
    <define here your mapping for scene a>
  constrain_input_select: input_select.my_input_select,scene_a

scene_b:
  module: controllerx
  class: E2002LightController
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.my_light
  merge_mapping:
    "on":
      - service: input_select.select_next
        entity_id: input_select.my_input_select
    "off":
      - service: input_select.select_previous
         entity_id: input_select.my_input_select
    <define here your mapping for scene b>
  constrain_input_select: input_select.my_input_select,scene_b

scene_c:
  module: controllerx
  class: E2002LightController
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.my_light
  merge_mapping:
    "on":
      - service: input_select.select_next
        entity_id: input_select.my_input_select
    "off":
      - service: input_select.select_previous
         entity_id: input_select.my_input_select
    <define here your mapping for scene c>
  constrain_input_select: input_select.my_input_select,scene_c
```

It is a bit verbose, so you can use YAML anchors to have less repeated config:

```yaml
scene_config: &scene_config
  module: controllerx
  class: E2002LightController
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.my_light
  merge_mapping: &scene_config_default_mapping
    "on":
      - service: input_select.select_next
        entity_id: input_select.my_input_select
    "off":
      - service: input_select.select_previous
         entity_id: input_select.my_input_select

scene_a:
  <<: *scene_config
  merge_mapping:
    <<: *scene_config_default_mapping
    <define here your mapping for scene a>
  constrain_input_select: input_select.my_input_select,scene_a

scene_b:
  <<: *scene_config
  merge_mapping:
    <<: *scene_config_default_mapping
    <define here your mapping for scene b>
  constrain_input_select: input_select.my_input_select,scene_b

scene_c:
  <<: *scene_config
  merge_mapping:
    <<: *scene_config_default_mapping
    <define here your mapping for scene c>
  constrain_input_select: input_select.my_input_select,scene_c
```

In the `define here your mapping for scene X`, you can define it like in the example I gave you above. You can reference more about custom mapping [here](https://xaviml.github.io/controllerx/advanced/).

Regards,
Xavi M.
