### ISSUE TITLE
[BUG] E1810 ZHA double click not working

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#607]
# Bug report

## Description

Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

## Additional information

- Devices involved:
  - Model: E1810
  - ...
- Integration: zha
- AppDaemon version: [ 4.1.0 ]
- ControllerX version: [ eg. v4.24 ]
- Home Assistant Core version: [  2022.10.4 ]

## AppDaemon app configuration

```yaml
studio:
  module: controllerx
  class: E1810Controller
  integration: zha
  controller: 84:ba:20:ff:fe:6b:55:ff
  light: light.cc2652_zigbee_usb_3_studio_ceiling_lights_zha_group_0x0005
  smooth_power_on: true
  multiple_click_delay: 500
  merge_mapping:
    toggle$2:
      service: switch.toggle
      data:
        entity_id: switch.studio_work_outlet_local
```

The double click event for ZHA doesn't seem to work. It just flashes the lights on and off quickly. The Home Assistant log just shows 

`turned on triggered by automation triggered by event 'zha_event'`
