### ISSUE TITLE
[QUESTION] z2m groups vs helpers

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#608]
I am testing z2m and have found a small issue when creating light groups using Zigbee2MQTT.

I have setup a Philips controller as follows 👍 

```
hue_dimmer_landing:
  module: controllerx
  class: Philips929002398602LightController
  integration: z2m
  controller: sensor.hue_dimmer_landing_action
  light: light.helper_landing_ceiling_lights
  multiple_click_delay: 300
  merge_mapping:
    on_press_release:
      service: light.toggle
      data:
        entity_id: light.helper_landing_ceiling_lights
    off_press_release:
      service: switch.toggle
      data:
        entity_id: switch.philips_tv_outlet_local
    on_press_release$2:
      service: switch.toggle
      data:
        entity_id: switch.landing_floor_lamp
```
I want to setup the "on" button as a toggle and this works fine.

However, when creating a light group in Z2M, the brightness no longer works by pressing the remote buttons.

If I create a light group helper and assign this helper then the brightness works as expected.

Is this expected behaviour? If not , I can report it as a bug.

As a side note, for some reason, all the z2m versions of this controller incorrectly state the first button is "on" and the last "button" is off. The first button is actually on/off toggle and the last button is Hue - which normally changes the scenes.
