### ISSUE TITLE
[QUESTION] Button toggling to change mapping

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#610]
Thanks for ControllerX. It's a great piece of software that has really streamlined my ability to get my controllers working more satisfactorily than automation blueprints. 

One thing I would really like to do is be able to set up different lights with a Philips Hue controller and use a button to toggle through mappings so I can set the brightness of each light individually.

Is this possible with ControllerX or something that could be possible in the future? I can attempt to program it myself with the right pointers in the code base.

**Comment by xaviml** [comment]
Hi @inertia666 ,

Yes, this is possible, but not all through ControllerX, you would need a setup from HA.

First, you need to create an input_select in HA with the light entities you would like to control:

```yaml
input_select:
  lights:
    options:
      - light.my_light_1
      - light.my_light_2
      - light.my_light_3
```

Then, you can use templating in ControllerX to control your light, and you will need a way to change the light (for example double click on top button):

```yaml
example_app:
  module: controllerx
  class: HueDimmerController
  integration: z2m
  controller: sensor.my_controller_action
  light: "{{ {{ states('input_select.lights') }} }}"
  merge_mapping:
    on_press_release$2:
      - service: input_select.select_next
         data:
           entity_id: input_select.lights
```

Everytime you double press the top button, the controller will be working for a new light with the default mapping for that controller.

Regards,
Xavi M.
