### ISSUE TITLE
[QUESTION] Dim to a threshold minimum brightness

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#617]
One thing I am trying to find a solution for is dimming a lamp so it does not turn off when the dimming towards 0. I want to keep a minimum brightness threshold, say 8% or a certain value.

Is it possible to use ControllerX with a look ahead so that the lamp does not turn off when dimming? I have managed to make it so that the light will go back on if dimmed to 0 but it's very clumsy.

**Comment by xaviml** [comment]
Hi @inertia666 ,

Default minimum brightness for most of the lights is 1, and they should not turn off at that value. However, it could be that some lights turn off when reaching 1. You can change the default minimum (and maximum) brightness with `min_brightness`:

```yaml
livingroom_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.bedroom
  min_brightness: 20
```

Possible values go from 1 to 255.

Regards,
Xavi M.
