### ISSUE TITLE
[QUESTION] "This controller does not support mqtt"

### ISSUE THREAD

**Issue by SergioRius** [xaviml/controllerx#619]
# Question

I'm trying to add a custom configuration for a supposedly non-supported device.
The device involved is a [Xiaomi QBKG23LM](https://www.zigbee2mqtt.io/devices/QBKG23LM.html#xiaomi-qbkg23lm)

So I've added the following configuration and expected to work:
```yaml
workspace_sw2:
  module: controllerx
  class: Z2MLightController
  controller: zigbee2mqtt/workspace_sw2/action
  integration: mqtt
  light: light.workspace_lights_ceiling
```
I've also tried with the LightController and the z2m integration + listening to mqtt with the same result.
What I'm doing wrong?

I've confirmed with MQTT Explorer that those "endpoints" are right:

**zigbee2mqtt/workspace_sw2**
```json
{"action":"single","consumption":0,"device_temperature":27,"energy":0,"last_seen":"2022-10-29T21:11:30+02:00","linkquality":72,"operation_mode":null,"power":0,"power_outage_count":3,"state":"ON","update":{"state":null},"update_available":null,"voltage":null}
```
**zigbee2mqtt/workspace_sw2/action**
`single`

**Comment by xaviml** [comment]
Hi @SergioRius,

ControllerX works with any controller as long as the integration is added (z2m, deconz, zha, etc.), however, that controller will not have any default mapping. This means that user would need to define the mapping themselves since ControllerX does not know which events the controller fires. For this reason, adding "support" to a device in ControllerX means to just specify what the events that the device triggers and assign each event to a specific action (toggle, full brightness, etc).

In your case, you would need to define the mapping with `mapping` attribute:

```yaml
workspace_sw2:
  module: controllerx
  class: Z2MLightController
  controller: zigbee2mqtt/workspace_sw2/action
  integration: mqtt
  light: light.workspace_lights_ceiling
  mapping:
    single: toggle
```

You can read more about custom mappings [here](https://xaviml.github.io/controllerx/advanced/).

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi @SergioRius ,

Sorry, there was a typo in the configuration I sent you. If you use `Z2MLightController`, you need to put the friendly name of your light in the `light` attribute:

```yaml
workspace_sw2:
  module: controllerx
  class: Z2MLightController
  controller: zigbee2mqtt/workspace_sw2/action
  integration: mqtt
  light: workspace_lights_ceiling  # This is the friendly name of your light in Z2M
  mapping:
    single: toggle
```

Otherwise, you can use a regular `LightController`:

```yaml
workspace_sw2:
  module: controllerx
  class: LightController
  controller: zigbee2mqtt/workspace_sw2/action
  integration: mqtt
  light: light.workspace_lights_ceiling 
  mapping:
    single: toggle
```

Finally, the best configuration you can get is to fully communicate with MQTT, and avoid HA:

```yaml
workspace_sw2:
  module: controllerx
  class: Z2MLightController
  controller: workspace_sw2
  integration:
    name: z2m
    listen_to: mqtt
  light:
    name: workspace_lights_ceiling  # This is the friendly name of your light in Z2M
    mode: mqtt
  mapping:
    single: toggle
```

With this last configuration, you should be able to control your light even if HA core is down (e.g. when it's restarting).

I recommend you reading more about `Z2MLightController` [here](https://xaviml.github.io/controllerx/others/zigbee2mqtt-light-controller/).

Regards,
Xavi M.
