### ISSUE TITLE
trouble migrating from zha to mqtt

### ISSUE THREAD

**Issue by neuronflow** [xaviml/controllerx#624]
Hi,

I am having trouble to migrate from zha to mqtt.

I want to migrate this app:
```
livingroom_controller_classic:
  module: controllerx
  class: E2002LightController
  controller: 04:cd:15:ff:fe:8c:8a:a6
  integration: zha
  transition: 800
  light:
    name: light.lr_couch
  color_wheel: color_temp_wheel
  # color_mode: color_temp
  ```
  
  I tried:
  
```
  livingroom_controller:
  module: controllerx
  class: E2002LightController
  integration:
    name: z2m
    # listen_to: mqtt
  controller: zigbee2mqtt/kitchen_styrbar/action
  light:
    name: light.lr_couch
```
    
my device's friendly name is `kitchen_styrbar`.

I tried multiple variations with the leading `zigbee2mqtt/` and with `/action` in the end.
 Also I tried:  ` # listen_to: mqtt`

What am I doing wrong?

the device shows up in HA. It sends packages like this:

```
zigbee2mqtt                | Zigbee2MQTT:info  2022-11-05 11:50:15: MQTT publish: topic 'zigbee2mqtt/kitchen_styrbar/action', payload 'on'
```

**Comment by neuronflow** [comment]
I managed to get it running and the app mqtt app was misconfigured :)

now this works:
```
livingroom_controller:
  module: controllerx
  class: E2002LightController
  integration:
    name: z2m
    listen_to: mqtt
  controller: kitchen_styrbar
  light:
    name: light.lr_couch
 ```
