### ISSUE TITLE
Add `excluded_actions` to complement `actions` attribute

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#63]
# Feature Request

### Is your feature request related to a problem?

If a controller has 10 actions and we want to use all of them except one, we need to add all of them in the `actions` except for the one that we do not want to use. Here is an example of a configuration where we do not want to use the `toggle` action.
```yaml
livingroom_light:
  module: controllerx
  class: E1810Controller
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.livingroom
  smooth_power_on: true
  actions:
    - toggle_hold
    - brightness_up_click
    - brightness_down_click
    - arrow_left_click
    - arrow_right_click
    - brightness_up_hold
    - brightness_up_release
    - brightness_down_hold
    - brightness_down_release
    - arrow_left_hold
    - arrow_left_release
    - arrow_right_hold
    - arrow_right_release
```

### Describe the solution / feature you'd like

What I would like is to have an option of adding the excluded actions, so the opposite of what we have now. The previous configuration would look like:
```yaml
livingroom_light:
  module: controllerx
  class: E1810Controller
  controller: sensor.livingroom_controller_action
  integration: z2m
  light: light.livingroom
  smooth_power_on: true
  excluded_actions:
    - toggle
```

Also, when this feature is added, `actions` and `excluded_actions` won't be able to coexist in the same configuration, so we would be able to use one or the other or none, but not both at the same time.
