### ISSUE TITLE
[QUESTION] Using WXKG01LM as switch

### ISSUE THREAD

**Issue by mathieuric** [xaviml/controllerx#635]
# Question

I wanted to use the [WXKG01LM](https://xaviml.github.io/controllerx/controllers/WXKG01LM/) button to control a smart plug (switch) so I added this to `aqara.py`:

```python
class WXKG01LMSwitchController(SwitchController):
    def get_z2m_actions_mapping(self) -> DefaultActionsMapping:
        return {
            "single": Switch.TOGGLE
        }

    def get_deconz_actions_mapping(self) -> DefaultActionsMapping:
        return {
            1002: Switch.TOGGLE  # single
        }

    def get_zha_actions_mapping(self) -> DefaultActionsMapping:
        return {
            "single": Switch.TOGGLE
        }

    def get_zha_action(self, data: EventData) -> str:
        args = data["args"]
        if "click_type" in args:
            return args["click_type"]
        return data["command"]
```

It works fine so I would like this to be merged into the main branch so I don't lose the functionality on the next update but the `CONTRIBUTING.md` document says 

> Note that this project will only accept the mapping that the original controller would follow with its original hub, or the closest behaviour we can get.

Does it mean I can't submit a PR for this?

Thanks!

## AppDaemon app configuration

```yaml
WXKG01LM_Tuya_Smart_Plug:
  module: controllerx
  class: WXKG01LMSwitchController
  integration: deconz
  controller: smart_switch_WXKG01LM
  switch: switch.smart_socket_3_socket_1
```

**Comment by xaviml** [comment]
Hi @mathieuric,

The note in the contributing file is specifically for controllers that have a specific purpose. So, I will not be adding a mapping to a "power" button to change brightness when the symbol indicates is for turning on/off. However, most of the Aqara devices are DIY, so there is no specific mapping to a controller that the default application from Xiaomi suggests.

Therefore, a PR is more than welcome for this :)

However, note that this can be achieved with the following config with the latest ControllerX version:

```yaml
WXKG01LM_Tuya_Smart_Plug:
  module: controllerx
  class: SwitchController
  integration: deconz
  controller: smart_switch_WXKG01LM
  switch: switch.smart_socket_3_socket_1
  mapping:
    1002: toggle
```

Regards,
Xavi M.
