### ISSUE TITLE
Color temperature action not working

### ISSUE THREAD

**Issue by jeroenbeuz** [xaviml/controllerx#666]
# Bug report

## Description

Action 'hold' with attribute 'color_temp' does not work when the light is in a different 'color_mode', eg 'color_mode: xy'.

## Additional information

- Devices involved:
  - Model: [ Signify LCA006] as [ Light ]
  - Model: [ Signify LCT024] as [ Light ]
- Integration:z2m
- AppDaemon version: [ v0.11.0 ]
- ControllerX version: [ v4.25.0 ]
- HACS version: [v1.29.0 ]
- Home Assistant Core version: [2023.1.0 ]

## AppDaemon app configuration

```yaml
studiekamer_controller:
  module: controllerx
  class: Philips929002398602LightController
  controller: sensor.studiekamer_dimmer_switch
  integration: z2m
  light: light.studiekamer_lamp_beeldscherm_rechts
  merge_mapping:
    "on_hold":
      - action: hold_colortemp_up
    "off_hold":
      - action: hold_colortemp_down
```

## Additional Context
To reproduce: set the light (or light group) to a color within HASS or anywhere else, to make sure the state of the light has 'color_mode: xy'. Execute the action to increase/decrease the color temperature and nothing will happen. I've also tried to set the 'color_mode' to 'color_temp', but that also doesn't fix this issue. Besides, I just want to set the temperature when holding the on or off button.

**Comment by xaviml** [comment]
Hi @jeroenbeuz ,

Thank you for reporting this bug. Could you please also attach the AppDaemon logs with the error (if any) when the lights are not working in the case you mention?

It is most likely that this is a bug with the light. ControllerX needs the `color_temp` attribute to change the color temperature, as well as the light supporting it. In case of having a light that only supports `xy_color` and not `color_temp`, then you can assign the `color_wheel` attribute to `color_temp_wheel`:

```yaml
studiekamer_controller:
  module: controllerx
  class: Philips929002398602LightController
  controller: sensor.studiekamer_dimmer_switch
  integration: z2m
  light: light.studiekamer_lamp_beeldscherm_rechts
  color_wheel: color_temp_wheel
```

Regards,
Xavi M.
