### ISSUE TITLE
[QUESTION] Issuing remote commands with the media controller

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#698]
```
media_remote:
  module: controllerx
  class: E1810MediaPlayerController
  integration:
    name: z2m
    listen_to: mqtt
  controller: 5B_remote_studio
  media_player: media_player.sony_ke_48a9
  multiple_click_delay: 300
  merge_mapping:
    brightness_up_click:
      service: remote.send_command
      data:
        command: "Up"
    brightness_down_click:
      service: remote.send_command
      data:
        command: "Down"
    arrow_left_click:
      service: remote.send_command
      data:
        command: "Left"
    arrow_right_click:
      service: remote.send_command
      data:
        command: "Right"
```
I am trying to replicate some of the functionality of the Sony remote with the Ikea controller. I am trying to issue remote commands to the media player but it's not working. I have tried differen't trigger commings like CursorUp etc but it doesn't help. What am I doing wrong?
