### ISSUE TITLE
[QUESTION] hold with custom mapping

### ISSUE THREAD

**Issue by inertia666** [xaviml/controllerx#705]
This pertains mostly to the E1810 and E2002. I will outline my problem and what I need as a solution

I have a TV and HDMI receiver. Frustratingly, the TV remote issues a single volume change of 0.5db per click to the receiver and cannot be held down. I have a script that issues around 10 clicks with a small delay and have assigned this script to a controller. This means a single click will raise or lower the volume by around 4-6db depending on the action.

I'd like to replace this with something better with custom mapping with ControllerX but haven't cracked how to do this yet.

If I hold down a button on the E1810/2002 it should constantly issue the volume change with a small delay until released. This should be able to be mapped regardless of if I use the light or media controller template. Can this be done with custom mapping?

**Comment by xaviml** [comment]
Hi @inertia666 ,

If you are able to create a media_player entity in Home Assistant, you can create a ControllerX config with it and it will automatically put volume up and down until you release the button. Configuration would look like:

```yaml
example_app:
  module: controllerx
  class: E1810MediaPlayerController
  integration: z2m
  controller: sensor.my_controller_action
  media_player: media_player.my_entity_id
```

I cannot think of any other way to repeatedly call a script through ControllerX until you release a button.

Regards,
Xavi M.
