### ISSUE TITLE
[QUESTION] migrate old ControllerX WXCJKG13LM configuration with Light- and MediaplayerController from v4.18.2 to 4.25.0

### ISSUE THREAD

**Issue by tioan** [xaviml/controllerx#725]
# Question

How i can migrate my old controllerx v4.18.2 configuration with LightController and MediaPlayerController to a recent controllerx version like v4.25.0? 

The [WXCJKG13LM Page](https://xaviml.github.io/controllerx/controllers/WXCJKG13LM) only list an WXCJKG13LMLightController no MediaPlayerController

## Additional information

- Devices involved:
  - Model: 	Xiaomi WXCJKG13LM
- Integration: z2m
- AppDaemon version: 4.2.1
- ControllerX version: 2.4.18.2 / 2.25.0
- HACS version (if installed from there): 1.31.0
- Home Assistant Core version: 2023.2.5

## AppDaemon app configuration

```yaml
Schlafzimmer_Sonos:
  module: controllerx
  class: MediaPlayerController
  controller: sensor.0x04cf8cdf3c7d5f8e_action
  integration: z2m
  media_player: media_player.schlafzimmer_sonos
  volume_steps: 100
  delay: 100
  mapping:
    button_5_double: previous_track
    button_5_hold: hold_volume_down
    button_5_release: release
    button_6_single: play_pause
    button_6_double: next_track
    button_6_hold: hold_volume_up
    button_6_release: release

Schlafzimmer_Deckenbeleuchtung:
  module: controllerx
  class: LightController
  controller: sensor.0x04cf8cdf3c7d5f8e_action
  integration: z2m
  light: light.schlafzimmer_decke
  smooth_power_on: true
  mapping:
    button_1_single: toggle
    button_1_hold: hold_brightness_up
    button_1_release: release
    button_3_hold: hold_brightness_down
    button_3_release: release
    button_3_single: 
      service: fan.toggle
      data:
        entity_id:  fan.bedroom_fan

Schlafzimmer_light2:
  module: controllerx
  class: LightController
  controller: sensor.0x04cf8cdf3c7d5f8e_action
  integration: z2m
  light: light.schlafzimmer
  mapping:
    button_1_double: toggle

Schlafzimmer_Bettkasten:
  module: controllerx
  class: LightController
  controller: sensor.0x04cf8cdf3c7d5f8e_action
  integration: z2m
  light: light.schlafzimmer_bettkasten
  smooth_power_on: true
  mapping:
    button_2_single: toggle
    button_2_hold: hold_brightness_up
    button_2_release: release
    button_4_hold: hold_brightness_down
    button_4_release: release 
```
