### ISSUE TITLE
Documentation typo in controller device pages

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#74]
In the controller device pages (e.g. https://xaviml.github.io/controllerx/controllers/E1766) we have 1 section for each device support (light, switch, cover or media player). Each of them has an example configuration and right now for any device support different than light, we see examples like: 
```
  example_app:
    module: controllerx
    class: E1766CoverController
    controller: < controller_id >
    integration: < deconz >
    light: < light_entity >
```

which `light: < light_entity >` should be: `cover: < cover_entity >`
