### ISSUE TITLE
Trying to use PTM215X for cover control

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#813]
Hi Xavier
I'm trying to use the PTM215X for cover controls.
It's a four button thingimagin, and the top two I use for a light, and I want to use the two at the bottom for a cover.

This is my config:
```
office_sofa_light:
  module: controllerx
  class: PTM215XLightController
  controller: sensor.sofa_control_action
  integration: z2m
  light: light.office_sofa
  mapping:
    press_1: "on"
    release_1: release
    press_3: "off"
    release_3: release

office-sofa-cover_up:
  module: controllerx
  class: PTM215XLightController
  controller: sensor.sofa_control_action
  integration: z2m
  cover: cover.office_blind
  mapping:
    press_2: toggle_open
    release_2: stop

office-sofa-cover-down:
  module: controllerx
  class: PTM215XLightController
  controller: sensor.sofa_control_action
  integration: z2m
  cover: cover.office_blind
  constrain_input_boolean: binary_sensor.office_window_contact,off
  mapping:
    press_4: toggle_close
    release_4: stop
```
But that doesn't work, it complains that it needs a light instead, which is logical, as it's a light controller, and not a cover controller.
If I change it to a E1766CoverController controller, then it works for the cover :-)

**Comment by xaviml** [comment]
Hi @fribse ,

The https://xaviml.github.io/controllerx/controllers/PTM215X is not supported as a CoverController. You would need to use a regular "CoverController" and add the mapping yourself:

```yaml
office-sofa-cover_up:
  module: controllerx
  class: Coverontroller
  controller: sensor.sofa_control_action
  integration: z2m
  cover: cover.office_blind
  mapping:
    press_2: toggle_open
    release_2: stop
```

Regards,
