### ISSUE TITLE
[QUESTION] How to use transitions with Hold / Click Modes?

### ISSUE THREAD

**Issue by sabaatworld** [xaviml/controllerx#836]
# Question

Its not clear from the documentation https://xaviml.github.io/controllerx/advanced/hold-click-modes/ on how to use transitions. I'm looking to force a transition value to all on / off / brightness changes. It always seems to use the default 0.35 value. Can you please help me figure out how to do this?

## Additional information

- Devices involved:
  - Model: LutronPJ23BRLLightController
- Integration: lutron_caseta
- AppDaemon version: 4.4.2
- ControllerX version: 4.26.2
- HACS version (if installed from there): Latest
- Home Assistant Core version: Latest

## AppDaemon app configuration

```yaml
hallway_stairs_remote:
  module: controllerx
  class: LutronPJ23BRLLightController
  controller: 66731596
  integration: lutron_caseta
  light: light.office_lamp
  merge_mapping:
    "button_5_press":
      action: hold
      attribute: brightness
      direction: up
      mode: stop
      transition: 2000
```

## Logs

```text
2023-04-24 07:48:50.174686 INFO hallway_stairs_remote: 🏃 Running `Predefined (release)` now
2023-04-24 07:48:50.171459 INFO hallway_stairs_remote: 🎮 Button event triggered: `button_5_release`
2023-04-24 07:48:49.970449 INFO hallway_stairs_remote: 🤖 Service: [1mlight.turn_on[0m - entity_id: light.office_lamp - transition: 0.35 - brightness: 114
2023-04-24 07:48:49.955306 INFO hallway_stairs_remote: 🏃 Running `Predefined (hold)` now
2023-04-24 07:48:49.952138 INFO hallway_stairs_remote: 🎮 Button event triggered: `button_5_press`
```

## Additional Context

N/A

**Comment by xaviml** [comment]
Hi @sabaatworld , 

That `transition` cannot be configured within the "hold" action. The transition you see in the logs is part of the `delay` which varies in each controller (default 350ms). You can change the delay with the `delay` attribute:

```yaml
hallway_stairs_remote:
  module: controllerx
  class: LutronPJ23BRLLightController
  controller: 66731596
  integration: lutron_caseta
  light: light.office_lamp
  transition: 2000
  merge_mapping:
    "button_5_press":
      action: hold
      attribute: brightness
      direction: up
      mode: stop
      transition: 2000
```

However, you see 0.35 because by default uses the delay (350ms) when holding actions. So you can change `delay` if you want something smoother.

Regards,
Xavi M.
