### ISSUE TITLE
Possible issue with E1743

### ISSUE THREAD

**Issue by tabearu** [xaviml/controllerx#863]
# Question

Hello everyone. First of all, love the project.
I've recently bought an E1743 and have been trying to set it up without access. I've managed to get on/off working but brightness is never working no matter the settings. I always receive `entity unknown` even though the entity exists in homeassistant.

## Additional information

- Devices involved:
  - Model: IKEA E1743 as Controller
  - Sonoff USB 3.0 Dongle Plus

- Integration: z2m 
- AppDaemon version: 4.2.3 & 4.2.1
- ControllerX version: 4.26.2
- HACS version: 1.32.1
- Home Assistant Core version: 2023.5.2

Please note that I'm running everything in docker.

## AppDaemon app configuration

```yaml
# this is working for on/off
ikea_tradfri_switch_1:
  module: controllerx
  class: E1743Controller
  integration: z2m
  controller: sensor.ikea_tradfri_on_off_switch_1_action
  light: light.rooflight
  
# this is not working at all
ikea_tradfri_switch_1:
  module: controllerx
  class: E1743Z2MLightController
  integration: z2m
  controller: sensor.ikea_tradfri_on_off_switch_1_action
  light: light.rooflight # also tested with:   light: rooflight

```

## Logs
Z2M
```text
Zigbee2MQTT:info  MQTT publish: topic 'zigbee2mqtt/IKEA-Tradfri-On-Off-Switch-1/action', payload 'on'
Zigbee2MQTT:error Entity 'rooflight' is unknown
```
ControllerX
```text
Zigbee2MQTT:info MQTT publish: topic 'zigbee2mqtt/IKEA-Tradfri-On-Off-Switch-1', payload '{"action":"on","battery":60,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  MQTT publish: topic 'zigbee2mqtt/IKEA-Tradfri-On-Off-Switch-1', payload '{"action":"","battery":60,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info MQTT publish: topic 'zigbee2mqtt/IKEA-Tradfri-On-Off-Switch-1/action', payload 'on'
Zigbee2MQTT:error Entity 'rooflight' is unknown
```
Homeassistant
```text
WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
```

I'm not sure what I'm doing wrong and would appreciate all help.
