### ISSUE TITLE
Media player (volume control) support for E1743 (IKEA)

### ISSUE THREAD

**Issue by mihalski** [xaviml/controllerx#87]
# Feature Request

### Is your feature request related to a problem?

I'd like to be able to control play/pause and volume using an E1743 (IKEA).

### Describe the solution / feature you'd like

I would like to be able to increase volume by holding on and decrease volume by holding off. Additionally a Single short press of on or off could trigger a play/pause or something else configurable.

### Describe alternatives you've considered

I have considered writing a bunch of scripts, automations and using input_booleans in HA monitor whether a button is pressed, but it seems like ControllerX was created exactly to avoid this sort of jumping through hoops.

### Additional context

I am currently using Deconz but once ConBeeII support in zigbee2mqtt stabilises I may go back to that. I assume that with the way ControllerX works this sort of feature could easily work across all the supported platforms. I am specifically interested in volume control, play/pause (and potentially toggling grouping) of a Sonos media players.

**Comment by xaviml** [comment]
Hi @mihalski,

Thank you for opening this feature request. You are right that ControllerX does not support E1743 controller as a Media Player controller and I will add this for the next release. The behaviour I will implement will be the following:
- click up: play/pause
- click down: skip forward
- hold up: volume up
- hold down: volume down

However, I will be giving a default behaviour to `E1743MediaPlayerController` and it might not be what you are looking for, but this is why you can also use [custom controllers](https://xaviml.github.io/controllerx/others/custom-controllers). This allows you to define the mapping you want for your use case. For example, this is the configuration that you can already use with the behaviour I mentioned above:
```yaml
example_app:
  module: controllerx
  class: CustomMediaPlayerController
  integration: deconz
  media_player: group.all_my_media_players # or media_player.my_media_player
  mapping:
    1002: play_pause # Click "I"
    2002: next_track # Click "O"
    1001: hold_volume_up # Hold "I"
    2001: hold_volume_down # Hold "O"
    1003: release # Release "I"
    2003: release # Release "O"
```
You can see the mapping keys from the [E1743 controller](https://xaviml.github.io/controllerx/controllers/E1743) (on deCONZ section) and the values from the Custom Media Player controller from the [custom controller page](https://xaviml.github.io/controllerx/others/custom-controllers).

Furthermore, notice how you can define a group of media players with the Group HA integration and also, you can see [this](https://xaviml.github.io/controllerx/examples/sonos) nice reading of integrating SONOS devices with ControllerX from @htvekov.

I will leave this issue open in favour of adding a default behaviour to E1743 as media player controller.

Thanks :)

**Comment by xaviml** [comment]
Hi @mihalski again,

This integration has been added to the `dev` branch for now. It will be shipped to the next release. You can download the `dev` branch from HACS if you want to try, this is the configuration you can use for it:

```yaml
  example_app:
    module: controllerx
    class: E1743MediaPlayerController
    controller: < controller_id >
    integration: deconz
    media_player: < media_player entity or group>
```

Cheers!
