### ISSUE TITLE
[NEW DEVICE] Aqara E1 Smart Wireless Switch WXKG17LM

### ISSUE THREAD

**Issue by Bastian007** [xaviml/controllerx#891]
# New Device Support

## Device Information

- Device Model: WXKG17LM
- Device Description: Wireless remote switch E1 (double rocker)
- Device Manufacturer: Aqara

## Integrations

**Zigbee2MQTT	                              -  Predefined actions**
single_both, single_left, single_right     -	toggle
double_left, double_right	              - click_brightness_up
hold_left, hold_right	                      - click_brightness_down

#### Notes
https://www.zigbee2mqtt.io/devices/WXKG17LM.html
https://zigbee.blakadder.com/Aqara_WXKG17LM.html

**Comment by xaviml** [comment]
Hi @Bastian007 ,

Sorry for the late reply. This controller is just a new version of `WXKG02LM`, which is already supported:

https://xaviml.github.io/controllerx/controllers/WXKG02LM/

I see the actions are the same as you specified. Would this work for you?

**Comment by Bastian007** [comment]
Hi @xaviml ,
I've tried with WXKG02LM but it seems only the action toggle is fired, even if I double press or hold.

Log of AppDaemon
```
🤖 Service: mqtt.publish
  - topic: zigbee2mqtt/Hue Iris - Schlafzimmer/set
  - payload: {"state": "TOGGLE"}
2024-04-20 14:02:50.156055 INFO E1_Bastian_Schlafzimmer_Schalter3+4: 🎮 Button event triggered: `single_right`
2024-04-20 14:02:50.166638 INFO E1_Bastian_Schlafzimmer_Schalter3+4: 🏃 Running `Predefined (toggle)` now
2024-04-20 14:02:50.182851 INFO E1_Bastian_Schlafzimmer_Schalter3+4:
```

My config:
```
E1_Bastian_Schlafzimmer_Schalter1+2:
  module: controllerx
  class: WXKG02LMZ2MLightController
  integration: z2m
  controller: sensor.aqara_e1_schlafzimmer_nachttisch_bastian_action
  light: Hue Iris - Schlafzimmer
  mapping:
    single_left: "toggle"
    double_left: "click_brightness_up"
    hold_left: "click_brightness_down"

E1_Bastian_Schlafzimmer_Schalter3+4:
  module: controllerx
  class: WXKG02LMZ2MLightController
  integration: z2m
  controller: sensor.aqara_e1_schlafzimmer_nachttisch_bastian_action
  light: Hue white and color ambiance - Schlafzimmer
  mapping:
    single_right: "toggle"
    double_right: "click_brightness_up"
    hold_right: "click_brightness_down"
```

**Comment by astan00** [comment]
Hi,
I also noticed several issues when using new E1 with WXKG02LMLightController.
My best guess so far is that mapping does not override default actions.
What worked for me is to use dummy light endpoint instead of a real one (I go through ha) and do full service calls in mapping, like:


```
aquara_e1:
  module: controllerx
  class: WXKG02LMLightController
  controller: z2m-e1
  integration: 
    name: z2m
    listen_to: mqtt
  light: light.dummy
mapping:
    single_left: 
      - service: light.toggle
        entity_id: light.z2m_01_white
```

I never used z2m friendly names with spaces in z2m, don't know if this can lead to issues. You call mqtt directly, so I'd check if mqtt message is published for missing actions.

Also noticed E1 is kind of unstable in z2m, it becomes unresponsive from time to time.
