### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by wes1993** [xaviml/controllerx#91]
# Question

Is possible to Use E1810 with Group of ikea LED1537R6/LED1739R5

**Comment by xaviml** [comment]
Hi @wes1993,

ControllerX allows you to use group of lights (any light integrated with HA) with the group integration. The configuration for apps.yaml will look like the following:

```yaml
example_app:
  module: controllerx
  class: E1810Controller
  controller: <controller id depending on the integration>
  integration: <z2m | deconz | zha | mqtt>
  light: group.my_lights
```

You will need to define `group.my_lights` on your groups.yaml or configuration.yaml

Let me know if this answers your question :)
