### ISSUE TITLE
Support for white_value attribute for light controllers

### ISSUE THREAD

**Issue by WiktorBuczko** [xaviml/controllerx#93]
# Feature Request

### Is your feature request related to a problem?

I have a RGBW LED strip (red, green, blue and white LEDs) which is controlled by ESPHome. When I change the brightness of this LED strip, only RGB LEDs are changing brightness. White LEDs are controlled by white_value attribute of the light entity, but Controllerx does not support changing the white_value attribute. Could you add support for this? 

### Describe the solution / feature you'd like

I would like to have white_value equivalents in the values for CustomLightController (for example on_full_white_value, hold_white_value_up, and so on)

### Additional context

![Zrzut ekranu 2020-06-27 o 20 07 36](https://user-images.githubusercontent.com/22473122/85929078-1db03c80-b8b2-11ea-92d6-ae020b644a68.png)

**Comment by xaviml** [comment]
Hey @WiktorBuczko, I will integrate this for the next release. I will be adding the new predefined actions like brightness has.

Thank you for the request :)

**Comment by xaviml** [comment]
Hey @WiktorBuczko, as I typed this, a new beta version for ControllerX is being released v3.0.0b0. This version contains the support for white_value attribute as we currently do with brightness. Try it out and let me know if you encounter any problems with it. To download the beta version, you need to toggle the "Show beta versions" flag when entering to "Reinstall" from the dropdown menu when clicking on ControllerX.

Thank you :)

**Comment by xaviml** [comment]
I updated the documentation, but it is not yet on the website until I do the stable release. You can use everything you were using with `brightness` but it will need to be replaced by `white_value`. For example, you can use `hold_white_value_up`.

**Comment by WiktorBuczko** [comment]
Hi, thank you for lightning fast response. I have installed the beta version but I can not get it to work. Whenever I add white_value to the mapping, whole section (attached below) stops working. I also removed and installed Controllerx but this did not help. I can provide logs but I do not know where to find them. Here is my configuration. 
opple_sypialnia_1_biurko:

> module: controllerx
class: CustomLightController
  controller: sensor.opplesypialnia1_action
  integration: z2m
  light: light.lampa_led_sypialnia_esphome
  automatic_steps: 20
  add_transition: true
  transition: 700
  smooth_power_on: true
  mapping:
    button_2_single: toggle
    button_2_hold: hold_white_value_up
    button_2_release: release
    button_4_hold: hold_white_value_down
    button_4_release: release

I am sorry about yaml formatting, I do not know how to copy it properly.

**Comment by xaviml** [comment]
Hey @WiktorBuczko,

How do you have AppDaemon installed? Through HA addon? Did you restart the AppDaemon addon after installing the beta version? Everytime a new ControllerX version is installed, AppDaemon needs to be restarted.

If you want to show a yaml code in here, you can wrap the code between these 3 symbols: ```

Thanks :)

**Comment by xaviml** [comment]
Also, something that I just noticed is that in this release there is a breaking change related to the transition attribute. Now the `add_transition_turn_toggle` attribute is `false` by default, so the `transition` attribute won't be added to the calls when turning on/off. For the configuration you sent to me, you will need to add the following:

```yaml
opple_sypialnia_1_biurko:
  module: controllerx
  class: CustomLightController
  controller: sensor.opplesypialnia1_action
  integration: z2m
  light: light.lampa_led_sypialnia_esphome
  automatic_steps: 20
  add_transition: true
  add_transition_turn_toggle: true
  transition: 700
  smooth_power_on: true
  mapping:
    button_2_single: toggle
    button_2_hold: hold_white_value_up
    button_2_release: release
    button_4_hold: hold_white_value_down
    button_4_release: release
```
