### ISSUE TITLE
[NEW DEVICE] Legrand double wall switch

### ISSUE THREAD

**Issue by Crocmagnon** [xaviml/controllerx#98]
# New Device Support

## Device Information

* Device Model: Multiple device models (different look & feel). I have a [6 000 88](https://www.legrand.fr/pro/catalogue/43071-version-dooxie-with-netatmo/commande-double-sans-fil-dooxie-with-netatmo-pour-eclairage-ou-prise-connectee-ou-micromodule-blanc)
* Device Description: Legrand double gang switch
* Device Manufacturer: Legrand

Side note: I have a zha implementation ready for the [simple wall switch - 6 000 83](https://www.legrand.fr/pro/catalogue/42796-version-dooxie-with-netatmo/commande-sans-fil-dooxie-with-netatmo-pour-eclairage-ou-prise-connectee-ou-micromodule-blanc), but I'm not sure how to handle the two endpoints in the double switch. Each endpoint (vertical pair of buttons) should be able to control a different light.

<details>
<summary>Implementation</summary>

```python
# cx_devices/legrand.py

from cx_const import Light, TypeActionsMapping
from cx_core import LightController

class SimpleWallSwitchController(LightController):
    # Different states reported from the controller:
    # on, off, brightness_up, brightness_down, brightness_stop

    def get_zha_actions_mapping(self) -> TypeActionsMapping:
        return {
            "on": Light.ON,
            "off": Light.OFF,
            "move_0_255": Light.HOLD_BRIGHTNESS_UP,
            "move_1_255": Light.HOLD_BRIGHTNESS_DOWN,
            "stop": Light.RELEASE,
        }
```
</details>

#### Actions
There are four buttons. The switch recognizes both short and long presses.

Top left short press
```json
"data": {
    "device_ieee": "00:04:74:00:00:92:1d:78",
    "unique_id": "00:04:74:00:00:92:1d:78:1:0x0006",
    "endpoint_id": 1,
    "cluster_id": 6,
    "command": "off",
    "args": []
}
```

Bottom left short press
```json
"data": {
    "device_ieee": "00:04:74:00:00:92:1d:78",
    "unique_id": "00:04:74:00:00:92:1d:78:1:0x0006",
    "endpoint_id": 1,
    "cluster_id": 6,
    "command": "on",
    "args": []
}
```

Top right short press
```json
"data": {
    "device_ieee": "00:04:74:00:00:92:1d:78",
    "unique_id": "00:04:74:00:00:92:1d:78:1:0x0006",
    "endpoint_id": 2,
    "cluster_id": 6,
    "command": "off",
    "args": []
}
```

Bottom right short press
```json
"data": {
    "device_ieee": "00:04:74:00:00:92:1d:78",
    "unique_id": "00:04:74:00:00:92:1d:78:1:0x0006",
    "endpoint_id": 2,
    "cluster_id": 6,
    "command": "on",
    "args": []
}
```

The long press are the same but with `"command": "move"`, `"args": [0, 255]` for the bottom buttons and `"args": [1, 255]` for the top buttons.

**Comment by Crocmagnon** [comment]
🎉
What would the configuration look like to control two different lights from the two buttons?

**Comment by xaviml** [comment]
Well, if you want to control 2 lights, you will need to use CustomLightController. ControllerX configuration aims to bind N controllers to N lights (everything with everything). If you want 1 button to control 1 light and another button to control another light, then you will need the CustomLightController as I mentioned. 

However, ControllerX should give a default behaviour to the controller acting to one light. What I normally do with other controllers like this is:
- press left top button: Turn on light
- press left bottom button: Turn off light
- hold left top button: Change color or color temperature up
- hold left bottom button: Change color or color temperature down
- press right top button: Full brightness
- press right bottom button: Minimum brightness
- hold right top button: Change brightness up
- hold right bottom button: Change brightness down

I can add this to your code if you want, I just need to make sure that endpoint 1 is the left button and endpoint 2 is the right one. Is this true?

Thank you,
Xavi M.

**Comment by Crocmagnon** [comment]
Yep, feel free to add this to the PR :)

> endpoint 1 is the left button and endpoint 2 is the right one. Is this true?

Yes it is!

> you will need to use CustomLightController

Do you have any existing example of how I could configure it to manage two lights? :)

**Comment by xaviml** [comment]
Hi @Crocmagnon I just added both devices and the documentation to your branch. I will proceed with the merge request then. Regarding the configuration for two light, it will look like the following:
```yaml
example_app_light1:
  module: controllerx
  class: CustomLightController
  controller: <controller id>
  integration: <your integration>
  light: light.light1
  mapping:
    1_on: on
    1_off: off
    1_move_up: hold_brightness_up
    1_move_down: hold_brightness_down
    1_stop: release

example_app_light2:
  module: controllerx
  class: CustomLightController
  controller: <controller id>
  integration: <your integration>
  light: light.light2
  mapping:
    2_on: on
    2_off: off
    2_move_up: hold_brightness_up
    2_move_down: hold_brightness_down
    2_stop: release
```

Basically, we map one config with the events from the left button (`1_`) and the other for the right button (`2_`). The configuration uses the hold for brightness, but you can do what ever you want with the button actions. You can see the full predefined actions in [here](https://xaviml.github.io/controllerx/others/custom-controllers#custom-light-controller). However, if you want something even more customised, you can use [`CallServiceController`](https://xaviml.github.io/controllerx/others/custom-controllers#call-service-controller) to map button events with HA services.

Let me know if you need any help :)

Cheers,
Xavi M.

**Comment by xaviml** [comment]
HI @Crocmagnon,

The integration for these 2 controllers is now in ControllerX v3.3.0. However, I just realised that the configuration I sent you earlier it will not work since the ZHA parse is done to the device level and we are not specifying the device, but the `CustomLightController`. I will need to think about how to solve this problem. I will let you know.

**Comment by Crocmagnon** [comment]
Yes, that’s what I thought when I took a glance at it.

An option to override the mapping of any controller class would solve this and may other use cases: we could add classes to support special device features such as my switch with two endpoints but the user could have the final say over the commands mapping?

**Comment by xaviml** [comment]
Hi @Crocmagnon,

You are right. Now the CustomLightController is another class and this could be solved if we could override the mapping with the same Device Controller Class. The possible key-value mapping values are already accessible in the Custom Controllers documentation and the specific device page.

I will let you know about the changes as soon as I get to it. In the meantime, I will leave this issue open to solve this problem.

Thanks,
Xavi M.

**Comment by xaviml** [comment]
Hi @Crocmagnon,

A beta version of the ControllerX v3.4.0 has been released. Now, all the `CustomXYZController` have been deprecated and we can use the device controller to define a custom mapping. For example, if your controller is `Legrand600083LightController`, you can leave it in the `class` attribute and define the `mapping` attribute. Furthermore, if no device is specified for your controller, we can use `Controller`, `LightController`, `MediaPlayerController` to custom map the actions.

In your case, you will need to specify the Legrand device because the ZHA parsed has been specified for this controller, so configuration should be:

```yaml
example_app_light1:
  module: controllerx
  class: Legrand600088LightController
  controller: <controller id>
  integration: <your integration>
  light: light.light1
  mapping:
    1_on: on
    1_off: off
    1_move_up: hold_brightness_up
    1_move_down: hold_brightness_down
    1_stop: release

example_app_light2:
  module: controllerx
  class: Legrand600088LightController
  controller: <controller id>
  integration: <your integration>
  light: light.light2
  mapping:
    2_on: on
    2_off: off
    2_move_up: hold_brightness_up
    2_move_down: hold_brightness_down
    2_stop: release
```

Please, let me know if this works for you if you try. Thank you :)

**Comment by Crocmagnon** [comment]
That looks great! Unfortunately I don't have time to test it right now but I will as soon as possible 😀

**Comment by xaviml** [comment]
Changes have been shipped to ControllerX v3.4.0.

**Comment by Crocmagnon** [comment]
It works like a charm! 🎉❤️ 

I just had to quote the "on"/"off" values from the config you previously posted but otherwise it works great, thank you very much! 🚀

For the sake of completeness, here's a sample config:

```yaml
example_app_light1:
  module: controllerx
  class: Legrand600088LightController
  controller: <controller id>
  integration: zha
  light: light.salon
  mapping:
    1_on: "on"
    1_off: "off"
    1_move_up: hold_brightness_up
    1_move_down: hold_brightness_down
    1_stop: release

example_app_light2:
  module: controllerx
  class: Legrand600088LightController
  controller: <controller id>
  integration: zha
  light: light.bibliotheque
  mapping:
    2_on: "on"
    2_off: "off"
    2_move_up: hold_brightness_up
    2_move_down: hold_brightness_down
    2_stop: release
```
