### ISSUE TITLE
Cannot get double presses to work with an Ikea E1812 button

### ISSUE THREAD

**Issue by harrismck** [xaviml/controllerx#982]
# Question

Hi! I’ve started using ControllerX and it’s pretty great! However, I am having trouble getting double presses to work with an Ikea E1812 button. The single press works perfectly, but the double never does anything. I can’t follow the docs exactly as using toggle doesn’t trigger, only "on" does.

## Additional information

- Devices involved:
  - Model: IKEA E1812 as  Light Controller
- Integration: zha
- AppDaemon version: v4.4.2
- ControllerX version: v4.26.2
- HACS version: v1.34.0
- Home Assistant Core version: 2024.3.3

## AppDaemon app configuration

```yaml
cupboard_led_shortcut_button:
  module: controllerx
  class: E1812LightController
  integration: zha
  controller: <My ID here>
  light: light.wled
  multiple_click_delay: 500
  mapping:
    "on":
      - service: select.select_next
        entity_id: select.wled_preset
        data:
          cycle: true
      - service: notify.persistent_notification
        metadata: {}
        data:
          message: Shortcut button 2 pressed
    "on$2":
      - service: select_previous
        entity_id: select.wled_preset
        data:
          cycle: true
      - service: notify.persistent_notification
        metadata: {}
        data:
          message: Shortcut button 2 DOUBLE pressed
```

**Comment by xaviml** [comment]
Hi @harrismck ,

Try to play around with "multiple_click_delay" attribute. Make it bugger to catch the double click better. You should also check ZHA events to see if 2 events are fired within the time specified in "multiple_click_delay", and the AppDaemon logs to see if there is any issues there (you could enable debug mode).

If you share logs, I might be able to help you better, but configuration looks good to me.

Regards,
Xavi M.

**Comment by harrismck** [comment]
I tried messing with the "multiple_click_delay", doesn't seem to be the issue. As well, double-clicking doesn't activate my single click service calls even a single time. A single ZHA event does fire for double clicks though, it seems that the command being fired is.. "off" though for some reason. Here's the event for reference:
```
event_type: zha_event
data:
  device_ieee: dc:8e:95:ff:fe:89:c9:a8
  unique_id: dc:8e:95:ff:fe:89:c9:a8:1:0x0006
  device_id: 40f8150de0c2c16680d6b9a7b2563451
  endpoint_id: 1
  cluster_id: 6
  command: "on"
  args: []
  params: {}
origin: LOCAL
time_fired: "2024-04-30T04:37:20.377125+00:00"
context:
  id: 01HWPMNZBSYNY7KK0D0NY7G8WX
  parent_id: null
  user_id: null
  ```
  
  And the event from a single press for comparison:
  ```
  event_type: zha_event
data:
  device_ieee: dc:8e:95:ff:fe:89:c9:a8
  unique_id: dc:8e:95:ff:fe:89:c9:a8:1:0x0006
  device_id: 40f8150de0c2c16680d6b9a7b2563451
  endpoint_id: 1
  cluster_id: 6
  command: "on"
  args: []
  params: {}
origin: LOCAL
time_fired: "2024-04-30T04:37:20.377125+00:00"
context:
  id: 01HWPMNZBSYNY7KK0D0NY7G8WX
  parent_id: null
  user_id: null
  ```
